#ifndef __CMDLINE_ERRNO__
#define __CMDLINE_ERRNO__

#include "config.h"
#define ECMDLINE             CMDLINE_ERRNO
#define ECMDLINE_NOTFND      CMDLINE_ERRNO +  1
#define ECMDLINE_INVTYPE     CMDLINE_ERRNO +  2
#define ECMDLINE_INVPARM     CMDLINE_ERRNO +  3
#define ECMDLINE_INVVALUE    CMDLINE_ERRNO +  4
#define ECMDLINE_DUP         CMDLINE_ERRNO +  5
#define ECMDLINE_HELP        CMDLINE_ERRNO + 10
#define ECMDLINE_HELP_DETAIL CMDLINE_ERRNO + 11
#define ECMDLINE_NOMEM       CMDLINE_ERRNO + 20
#endif