.TH "testcmdline/$tool.hpp" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcmdline/$tool.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include 'cmdline\&.hpp'\fP
.br
\fC#include 'types\&.hpp'\fP
.br
\fC#include 'tools\&.hpp'\fP
.br
\fC#include 'cmdline_exceptions\&.hpp'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBTool\fP"
.br
.in -1c
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fB__tool__\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTool\fP \fBtool\fP"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define __tool__"

.PP
Definición en la línea \fB29\fP del archivo \fB$tool\&.hpp\fP\&.
.SH "Documentación de las variables"
.PP 
.SS "\fBTool\fP tool\fC [extern]\fP"

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
