.TH "testcmdline/$tool.hpp" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcmdline/$tool.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include '\&.\&./include/cmdline\&.hpp'\fP
.br
\fC#include '\&.\&./cmdline/include/tools\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTool\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__tool__\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTool\fP \fBtool\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __tool__"

.PP
Definition at line \fB27\fP of file \fB$tool\&.hpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBTool\fP tool\fC [extern]\fP"

.PP
Definition at line \fB8\fP of file \fBmainTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
