.TH "Argument" 3 "Sábado, 6 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Argument
.SH SYNOPSIS
.br
.PP
.PP
Heredado por \fBDefine\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBArgument\fP (\fBArgument\fP *arg)"
.br
.ti -1c
.RI "\fBArgument\fP (\fBParm\fP *parm)"
.br
.ti -1c
.RI "\fBArgument\fP (const char *name, const char *value)"
.br
.ti -1c
.RI "\fBArgument\fP (const char *name, const char *value, Source source)"
.br
.ti -1c
.RI "\fBArgument\fP (const char *name, const char *value, Type type)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBsetFromEnv\fP (const char *value)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBsetValue\fP (bool value)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBsetValue\fP (const char *value)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBsetValue\fP (std::string value)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBaddValue\fP (std::string value)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBaddValues\fP (vector< string > values)"
.br
.ti -1c
.RI "const char * \fBgetValue\fP ()"
.br
.ti -1c
.RI "vector< const char * > \fBgetValues\fP ()"
.br
.ti -1c
.RI "vector< string > \fBgetStringValues\fP ()"
.br
.ti -1c
.RI "bool \fBgetBoolean\fP ()"
.br
.ti -1c
.RI "\fBArgument\fP & \fBinitValues\fP (vector< string > values)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBmakeUpper\fP ()"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "Source \fBsource\fP = Source::DEFAULT"
.br
.ti -1c
.RI "Type \fBtype\fP = Type::STRING"
.br
.ti -1c
.RI "bool \fBmultiple\fP = false"
.br
.ti -1c
.RI "string \fBdefValue\fP"
.br
.ti -1c
.RI "set< string > \fBvalues\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB11\fP del archivo \fBargument\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "~\fBArgument\fP ()"

.PP
Definición en la línea \fB60\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP (\fBArgument\fP * arg)"

.PP
Definición en la línea \fB27\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP (\fBParm\fP * parm)"

.PP
Definición en la línea \fB19\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP (const char * name, const char * value)"

.PP
Definición en la línea \fB39\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP (const char * name, const char * value, Source source)"

.PP
Definición en la línea \fB44\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP (const char * name, const char * value, Type type)"

.PP
Definición en la línea \fB56\fP del archivo \fBargument\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "\fBArgument\fP & addValue (std::string value)"

.PP
Definición en la línea \fB124\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & addValues (vector< string > values)"

.PP
Definición en la línea \fB129\fP del archivo \fBargument\&.cpp\fP\&.
.SS "bool getBoolean ()"

.PP
Definición en la línea \fB81\fP del archivo \fBargument\&.cpp\fP\&.
.SS "vector< string > getStringValues ()"

.PP
Definición en la línea \fB75\fP del archivo \fBargument\&.cpp\fP\&.
.SS "const char * getValue ()"

.PP
Definición en la línea \fB64\fP del archivo \fBargument\&.cpp\fP\&.
.SS "vector< const char * > getValues ()"

.PP
Definición en la línea \fB67\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & initValues (vector< string > values)"

.PP
Definición en la línea \fB95\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & makeUpper ()"

.PP
Definición en la línea \fB134\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & setFromEnv (const char * value)"

.PP
Definición en la línea \fB102\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & setValue (bool value)"

.PP
Definición en la línea \fB113\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & setValue (const char * value)"

.PP
Definición en la línea \fB108\fP del archivo \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & setValue (std::string value)"

.PP
Definición en la línea \fB119\fP del archivo \fBargument\&.cpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "string defValue"

.PP
Definición en la línea \fB17\fP del archivo \fBargument\&.hpp\fP\&.
.SS "bool multiple = false"

.PP
Definición en la línea \fB16\fP del archivo \fBargument\&.hpp\fP\&.
.SS "string name"

.PP
Definición en la línea \fB13\fP del archivo \fBargument\&.hpp\fP\&.
.SS "Source source = Source::DEFAULT"

.PP
Definición en la línea \fB14\fP del archivo \fBargument\&.hpp\fP\&.
.SS "Type type = Type::STRING"

.PP
Definición en la línea \fB15\fP del archivo \fBargument\&.hpp\fP\&.
.SS "set<string> values"

.PP
Definición en la línea \fB18\fP del archivo \fBargument\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
