.TH "_Flag" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Flag
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBlogical\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB34\fP of file \fBcmdline_types\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* _Flag::name"

.PP
Definition at line \fB35\fP of file \fBcmdline_types\&.h\fP\&.
.SS "\fBlogical\fP _Flag::value"

.PP
Definition at line \fB36\fP of file \fBcmdline_types\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
