.TH "_ParmDef" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ParmDef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline_types\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBType\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "\fBlogical\fP \fBmultiple\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBcmdline_types\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBlogical\fP _ParmDef::multiple"

.PP
Definition at line \fB27\fP of file \fBcmdline_types\&.h\fP\&.
.SS "const char* _ParmDef::name"

.PP
Definition at line \fB24\fP of file \fBcmdline_types\&.h\fP\&.
.SS "\fBType\fP _ParmDef::type"

.PP
Definition at line \fB25\fP of file \fBcmdline_types\&.h\fP\&.
.SS "char* _ParmDef::value"

.PP
Definition at line \fB26\fP of file \fBcmdline_types\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
