.TH "_ParmDef" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ParmDef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBType\fP \fBtype\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "\fBlogical\fP \fBmultiple\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB19\fP del archivo \fBtypes\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "\fBlogical\fP _ParmDef::multiple"

.PP
Definición en la línea \fB23\fP del archivo \fBtypes\&.h\fP\&.
.SS "const char * _ParmDef::name"

.PP
Definición en la línea \fB20\fP del archivo \fBtypes\&.h\fP\&.
.SS "\fBType\fP _ParmDef::type"

.PP
Definición en la línea \fB21\fP del archivo \fBtypes\&.h\fP\&.
.SS "char * _ParmDef::value"

.PP
Definición en la línea \fB22\fP del archivo \fBtypes\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
