.TH "_Parameter" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Parameter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.h>\fP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char ** \fBvalues\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB26\fP del archivo \fBtypes\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "const char * _Parameter::name"

.PP
Definición en la línea \fB27\fP del archivo \fBtypes\&.h\fP\&.
.SS "int _Parameter::size"

.PP
Definición en la línea \fB29\fP del archivo \fBtypes\&.h\fP\&.
.SS "const char ** _Parameter::values"

.PP
Definición en la línea \fB28\fP del archivo \fBtypes\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
