.TH "Parm" 3 "Sábado, 6 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parm
.SH SYNOPSIS
.br
.PP
.PP
Heredado por \fBParmFlag\fP y \fBParmOption\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBParm\fP (const char *name)"
.br
.ti -1c
.RI "\fBParm\fP (const char *name, const char *value)"
.br
.ti -1c
.RI "\fBParm\fP (const char *name, const char *value, \fBType\fP type, bool multiple=false)"
.br
.ti -1c
.RI "\fBParm\fP (const char *name, bool value)"
.br
.ti -1c
.RI "bool \fBinstanceOfFlag\fP ()"
.br
.ti -1c
.RI "bool \fBinstanceOfOption\fP ()"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBType\fP \fBtype\fP = \fBType::STRING\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBmultiple\fP = false"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB31\fP del archivo \fBcmdline\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBParm\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB37\fP del archivo \fBcmdline\&.hpp\fP\&.
.SS "\fBParm\fP (const char * name)"

.PP
Definición en la línea \fB5\fP del archivo \fBparm\&.cpp\fP\&.
.SS "\fBParm\fP (const char * name, const char * value)"

.PP
Definición en la línea \fB12\fP del archivo \fBparm\&.cpp\fP\&.
.SS "\fBParm\fP (const char * name, const char * value, \fBType\fP type, bool multiple = \fCfalse\fP)"

.PP
Definición en la línea \fB18\fP del archivo \fBparm\&.cpp\fP\&.
.SS "\fBParm\fP (const char * name, bool value)"

.PP
Definición en la línea \fB25\fP del archivo \fBparm\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "bool instanceOfFlag ()"

.PP
Definición en la línea \fB32\fP del archivo \fBparm\&.cpp\fP\&.
.SS "bool instanceOfOption ()"

.PP
Definición en la línea \fB33\fP del archivo \fBparm\&.cpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "bool multiple = false"

.PP
Definición en la línea \fB36\fP del archivo \fBcmdline\&.hpp\fP\&.
.SS "const char* name"

.PP
Definición en la línea \fB33\fP del archivo \fBcmdline\&.hpp\fP\&.
.SS "\fBType\fP type = \fBType::STRING\fP"

.PP
Definición en la línea \fB34\fP del archivo \fBcmdline\&.hpp\fP\&.
.SS "char* value"

.PP
Definición en la línea \fB35\fP del archivo \fBcmdline\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
