.TH "cmdline::HelpRequested" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline::HelpRequested
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline_exceptions\&.hpp>\fP
.PP
Inherits \fBcmdline::CmdLineException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHelpRequested\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB55\fP of file \fBcmdline_exceptions\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cmdline::HelpRequested::HelpRequested ()\fC [inline]\fP"

.PP
Definition at line \fB57\fP of file \fBcmdline_exceptions\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
