.TH "cmdline::CmdLineValueException" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline::CmdLineValueException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline_exceptions\&.hpp>\fP
.PP
Inherits \fBcmdline::CmdLineException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCmdLineValueException\fP ()=\fBdelete\fP"
.br
.ti -1c
.RI "\fBCmdLineValueException\fP (const char *fmt,\&.\&.\&.)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB42\fP of file \fBcmdline_exceptions\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cmdline::CmdLineValueException::CmdLineValueException ()\fC [delete]\fP"

.SS "cmdline::CmdLineValueException::CmdLineValueException (const char * fmt,  \&.\&.\&.)"

.PP
Definition at line \fB33\fP of file \fBcmdline_exceptions\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
