.TH "ParmFlag" 3 "Sábado, 6 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParmFlag
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline\&.hpp>\fP
.PP
Herencias \fBParm\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBParmFlag\fP (const char *name)"
.br
.ti -1c
.RI "\fBParmFlag\fP (const char *name, bool active)"
.br
.in -1c
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
Utility subclass for defining Flags
.PP
Parm(const char* name) : Name,false Parm(const char* name, const char* value): name/value (false/true) 
.PP
Definición en la línea \fB56\fP del archivo \fBcmdline\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBParmFlag\fP (const char * name)\fC [inline]\fP"

.PP
Definición en la línea \fB59\fP del archivo \fBcmdline\&.hpp\fP\&.
.SS "\fBParmFlag\fP (const char * name, bool active)\fC [inline]\fP"

.PP
Definición en la línea \fB60\fP del archivo \fBcmdline\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
