.TH "CmdLine" 3 "Jueves, 11 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdLine \- Singleton encargado de mantener la informacion pasada por la linea de comandos @detail Aqui ponemos mas cosas\&.  

.SH SYNOPSIS
.br
.PP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "logical(* \fBhasFlag\fP )(const char *name)"
.br
.ti -1c
.RI "logical(* \fBhasOption\fP )(const char *name)"
.br
.ti -1c
.RI "logical(* \fBhasDefine\fP )(const char *name)"
.br
.ti -1c
.RI "logical(* \fBisOptionMultiple\fP )(const char *name)"
.br
.ti -1c
.RI "logical(* \fBisDefineMultiple\fP )(const char *name)"
.br
.ti -1c
.RI "logical(* \fBgetFlag\fP )(const char *name)"
.br
.ti -1c
.RI "int(* \fBgetOptionNumValues\fP )(const char *name)"
.br
.ti -1c
.RI "int(* \fBgetDefineNumValues\fP )(const char *name)"
.br
.ti -1c
.RI "const char *(* \fBgetOption\fP )(const char *name)"
.br
.ti -1c
.RI "const char *(* \fBgetDefine\fP )(const char *name)"
.br
.ti -1c
.RI "const char **(* \fBgetOptionValues\fP )(const char *name)"
.br
.ti -1c
.RI "const char **(* \fBgetDefineValues\fP )(const char *name)"
.br
.ti -1c
.RI "Flag **(* \fBgetDefaultFlags\fP )(logical active)"
.br
.ti -1c
.RI "Flag **(* \fBgetCurrentFlags\fP )(logical active)"
.br
.ti -1c
.RI "Parameter **(* \fBgetDefaultOptions\fP )()"
.br
.ti -1c
.RI "Parameter **(* \fBgetCurrentOptions\fP )()"
.br
.ti -1c
.RI "Parameter **(* \fBgetDefinitions\fP )()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Singleton encargado de mantener la informacion pasada por la linea de comandos @detail Aqui ponemos mas cosas\&. 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
