.TH "libcmdline/include/cmdline.h" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/include/cmdline.h
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBstruct_cmdline\fP"
.br
.in -1c
.SS "typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBstruct_cmdline\fP \fBCmdLine\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "\fBCmdLine\fP * \fBcmdline_create\fP (int argc, char **argv, \fBParmDef\fP \fBparms\fP[])"
.br
.ti -1c
.RI "void \fBcmdline_delete\fP (\fBCmdLine\fP *\fBcmdline\fP)"
.br
.in -1c
.SH "Documentación de los 'typedefs'"
.PP 
.SS "typedef struct \fBstruct_cmdline\fP \fBCmdLine\fP"

.SH "Documentación de las funciones"
.PP 
.SS "\fBCmdLine\fP * cmdline_create (int argc, char ** argv, \fBParmDef\fP parms[])"

.PP
Definición en la línea \fB247\fP del archivo \fBinterface\&.cpp\fP\&.
.SS "void cmdline_delete (\fBCmdLine\fP * cmdline)"

.PP
Definición en la línea \fB277\fP del archivo \fBinterface\&.cpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
