.TH "HelpRequested" 3 "Sábado, 6 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelpRequested
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBHelpException\fP\&.
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
Definición en la línea \fB59\fP del archivo \fBcmdline_exceptions\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBHelpRequested\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB61\fP del archivo \fBcmdline_exceptions\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
