.TH "cmdline::CmdLine" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline::CmdLine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline\&.hpp>\fP
.PP
Inherited by \fBcmdline::CmdLineI\fP, and \fBcmdline::CmdLineS\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCmdLine\fP ()"
.br
.ti -1c
.RI "\fBCmdLine\fP (int argc, char **argv, \fBParameters\fP \fBparms\fP, bool sensitive=false, bool strict=false)"
.br
.ti -1c
.RI "vector< const char * > \fBargs\fP ()"
.br
.ti -1c
.RI "bool \fBhasFlag\fP (const char *name)"
.br
.ti -1c
.RI "bool \fBhasFlag\fP (string name)"
.br
.ti -1c
.RI "\fBFlags\fP \fBgetDefaultFlags\fP (bool all=true)"
.br
.ti -1c
.RI "\fBFlags\fP \fBgetCurrentFlags\fP (bool all=true)"
.br
.ti -1c
.RI "bool \fBhasOption\fP (const char *name)"
.br
.ti -1c
.RI "bool \fBhasOption\fP (string name)"
.br
.ti -1c
.RI "bool \fBisOptionMultiple\fP (const char *name)"
.br
.ti -1c
.RI "bool \fBisOptionMultiple\fP (string name)"
.br
.ti -1c
.RI "const char * \fBgetOption\fP (const char *name)"
.br
.ti -1c
.RI "const char * \fBgetOption\fP (string name)"
.br
.ti -1c
.RI "vector< const char * > \fBgetOptionValues\fP (const char *name)"
.br
.ti -1c
.RI "vector< const char * > \fBgetOptionValues\fP (string name)"
.br
.ti -1c
.RI "int \fBgetOptionNumValues\fP (const char *name)"
.br
.ti -1c
.RI "int \fBgetOptionNumValues\fP (string name)"
.br
.ti -1c
.RI "\fBOptions\fP \fBgetDefaultOptions\fP ()"
.br
.ti -1c
.RI "\fBOptions\fP \fBgetCurrentOptions\fP ()"
.br
.ti -1c
.RI "template<typename T > const T \fBgetOptionAs\fP (T t, const char *name)"
.br
.ti -1c
.RI "template<typename T > const T \fBgetOptionFromType\fP (\fBType\fP t, const char *name)"
.br
.ti -1c
.RI "template<typename T > const T \fBgetOptionAs\fP (const char *name)"
.br
.ti -1c
.RI "template<typename T > const T \fBgetOptionAs\fP (string name)"
.br
.ti -1c
.RI "template<typename T > const vector< T > \fBgetOptionValuesAs\fP (string name)"
.br
.ti -1c
.RI "template<typename T > const vector< T > \fBgetOptionValuesAs\fP (const char *name)"
.br
.ti -1c
.RI "bool \fBhasDefinition\fP (const char *def)"
.br
.ti -1c
.RI "bool \fBhasDefinition\fP (string def)"
.br
.ti -1c
.RI "bool \fBisDefinitionMultiple\fP (const char *name)"
.br
.ti -1c
.RI "bool \fBisDefinitionMultiple\fP (string name)"
.br
.ti -1c
.RI "const char * \fBgetDefinition\fP (const char *name)"
.br
.ti -1c
.RI "const char * \fBgetDefinition\fP (string name)"
.br
.ti -1c
.RI "vector< const char * > \fBgetDefinitionValues\fP (const char *name)"
.br
.ti -1c
.RI "vector< const char * > \fBgetDefinitionValues\fP (string name)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCmdLine\fP \fBgetInstance\fP (int argc, char **argv, \fBParameters\fP \fBparms\fP=\fBParameters\fP())"
.br
.ti -1c
.RI "static \fBCmdLine\fP \fBgetInstance\fP (\fBParameters\fP \fBparms\fP, int argc, char **argv)"
.br
.ti -1c
.RI "static void \fBfreeInstance\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBCmdLine\fP \fBpGetInstance\fP (int argc, char **argv, \fBParameters\fP \fBparms\fP, bool sensitive=false, bool strict=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB54\fP of file \fBcmdline\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cmdline::CmdLine::CmdLine ()\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBcmdline\&.hpp\fP\&.
.SS "CmdLine::CmdLine (int argc, char ** argv, \fBParameters\fP parms, bool sensitive = \fCfalse\fP, bool strict = \fCfalse\fP)"

.PP
Definition at line \fB15\fP of file \fBcmdline\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "vector< const char * > CmdLine::args ()"

.PP
Definition at line \fB38\fP of file \fBcmdline\&.cpp\fP\&.
.SS "void CmdLine::freeInstance ()\fC [static]\fP"

.PP
Definition at line \fB14\fP of file \fBcmdline\&.cpp\fP\&.
.SS "\fBFlags\fP CmdLine::getCurrentFlags (bool all = \fCtrue\fP)"

.PP
Definition at line \fB43\fP of file \fBcmdline\&.cpp\fP\&.
.SS "\fBOptions\fP CmdLine::getCurrentOptions ()"

.PP
Definition at line \fB61\fP of file \fBcmdline\&.cpp\fP\&.
.SS "\fBFlags\fP CmdLine::getDefaultFlags (bool all = \fCtrue\fP)"

.PP
Definition at line \fB42\fP of file \fBcmdline\&.cpp\fP\&.
.SS "\fBOptions\fP CmdLine::getDefaultOptions ()"

.PP
Definition at line \fB60\fP of file \fBcmdline\&.cpp\fP\&.
.SS "const char * CmdLine::getDefinition (const char * name)"

.PP
Definition at line \fB67\fP of file \fBcmdline\&.cpp\fP\&.
.SS "const char * CmdLine::getDefinition (string name)"

.PP
Definition at line \fB68\fP of file \fBcmdline\&.cpp\fP\&.
.SS "vector< const char * > CmdLine::getDefinitionValues (const char * name)"

.PP
Definition at line \fB70\fP of file \fBcmdline\&.cpp\fP\&.
.SS "vector< const char * > CmdLine::getDefinitionValues (string name)"

.PP
Definition at line \fB71\fP of file \fBcmdline\&.cpp\fP\&.
.SS "\fBCmdLine\fP CmdLine::getInstance (int argc, char ** argv, \fBParameters\fP parms = \fC\fBParameters\fP()\fP)\fC [static]\fP"

.PP
Definition at line \fB28\fP of file \fBcmdline\&.cpp\fP\&.
.SS "\fBCmdLine\fP CmdLine::getInstance (\fBParameters\fP parms, int argc, char ** argv)\fC [static]\fP"

.PP
Definition at line \fB23\fP of file \fBcmdline\&.cpp\fP\&.
.SS "const char * CmdLine::getOption (const char * name)"

.PP
Definition at line \fB49\fP of file \fBcmdline\&.cpp\fP\&.
.SS "const char * cmdline::CmdLine::getOption (string name)\fC [inline]\fP"

.PP
Definition at line \fB76\fP of file \fBcmdline\&.hpp\fP\&.
.SS "template<typename T > const T cmdline::CmdLine::getOptionAs (const char * name)\fC [inline]\fP"

.PP
Definition at line \fB149\fP of file \fBcmdline\&.hpp\fP\&.
.SS "template<typename T > const T cmdline::CmdLine::getOptionAs (string name)\fC [inline]\fP"

.PP
Definition at line \fB153\fP of file \fBcmdline\&.hpp\fP\&.
.SS "template<typename T > const T cmdline::CmdLine::getOptionAs (T t, const char * name)\fC [inline]\fP"

.PP
Definition at line \fB85\fP of file \fBcmdline\&.hpp\fP\&.
.SS "template<typename T > const T cmdline::CmdLine::getOptionFromType (\fBType\fP t, const char * name)\fC [inline]\fP"

.PP
Definition at line \fB113\fP of file \fBcmdline\&.hpp\fP\&.
.SS "int CmdLine::getOptionNumValues (const char * name)"

.PP
Definition at line \fB58\fP of file \fBcmdline\&.cpp\fP\&.
.SS "int CmdLine::getOptionNumValues (string name)"

.PP
Definition at line \fB59\fP of file \fBcmdline\&.cpp\fP\&.
.SS "vector< const char * > CmdLine::getOptionValues (const char * name)"

.PP
Definition at line \fB55\fP of file \fBcmdline\&.cpp\fP\&.
.SS "vector< const char * > CmdLine::getOptionValues (string name)"

.PP
Definition at line \fB56\fP of file \fBcmdline\&.cpp\fP\&.
.SS "template<typename T > const vector< T > cmdline::CmdLine::getOptionValuesAs (const char * name)\fC [inline]\fP"

.PP
Definition at line \fB155\fP of file \fBcmdline\&.hpp\fP\&.
.SS "template<typename T > const vector< T > cmdline::CmdLine::getOptionValuesAs (string name)\fC [inline]\fP"

.PP
Definition at line \fB154\fP of file \fBcmdline\&.hpp\fP\&.
.SS "bool CmdLine::hasDefinition (const char * def)"

.PP
Definition at line \fB63\fP of file \fBcmdline\&.cpp\fP\&.
.SS "bool CmdLine::hasDefinition (string def)"

.PP
Definition at line \fB64\fP of file \fBcmdline\&.cpp\fP\&.
.SS "bool CmdLine::hasFlag (const char * name)"
Check if flag name is active 
.PP
Definition at line \fB40\fP of file \fBcmdline\&.cpp\fP\&.
.SS "bool CmdLine::hasFlag (string name)"
Check if flag name is active 
.PP
Definition at line \fB41\fP of file \fBcmdline\&.cpp\fP\&.
.SS "bool CmdLine::hasOption (const char * name)"

.PP
Definition at line \fB45\fP of file \fBcmdline\&.cpp\fP\&.
.SS "bool CmdLine::hasOption (string name)"

.PP
Definition at line \fB46\fP of file \fBcmdline\&.cpp\fP\&.
.SS "bool CmdLine::isDefinitionMultiple (const char * name)"

.PP
Definition at line \fB65\fP of file \fBcmdline\&.cpp\fP\&.
.SS "bool CmdLine::isDefinitionMultiple (string name)"

.PP
Definition at line \fB66\fP of file \fBcmdline\&.cpp\fP\&.
.SS "bool CmdLine::isOptionMultiple (const char * name)"

.PP
Definition at line \fB47\fP of file \fBcmdline\&.cpp\fP\&.
.SS "bool CmdLine::isOptionMultiple (string name)"

.PP
Definition at line \fB48\fP of file \fBcmdline\&.cpp\fP\&.
.SS "\fBCmdLine\fP CmdLine::pGetInstance (int argc, char ** argv, \fBParameters\fP parms, bool sensitive = \fCfalse\fP, bool strict = \fCfalse\fP)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB33\fP of file \fBcmdline\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
