.TH "libcmdline/include/cmdline_exceptions.hpp" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/include/cmdline_exceptions.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdexcept>\fP
.br
\fC#include 'msg_locale\&.hpp'\fP
.br
\fC#include <cstdarg>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBcmdline::CmdLineNotFoundException\fP"
.br
.ti -1c
.RI "class \fBcmdline::CmdLineInvalidTypeException\fP"
.br
.ti -1c
.RI "class \fBcmdline::CmdLineException\fP"
.br
.ti -1c
.RI "class \fBcmdline::CmdLineParameterException\fP"
.br
.ti -1c
.RI "class \fBcmdline::CmdLineValueException\fP"
.br
.ti -1c
.RI "class \fBcmdline::CmdLineDuplicateArgumentException\fP"
.br
.ti -1c
.RI "class \fBcmdline::HelpRequested\fP"
.br
.ti -1c
.RI "class \fBcmdline::HelpDetailedRequested\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcmdline\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
