.TH "ParmFlag" 3 "Lunes, 8 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParmFlag
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline\&.hpp>\fP
.PP
Herencias \fBParm\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBParmFlag\fP (const char *name)"
.br
.ti -1c
.RI "\fBParmFlag\fP (const char *name, bool active)"
.br
.in -1c
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
Utility subclass for defining Flags
.PP
\fBParm(const char* name)\fP : Name,false \fBParm(const char* name, const char* value)\fP: name/value (false/true) 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
