.TH "cmdline" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCmdLine\fP"
.br
.ti -1c
.RI "class \fBCmdLineDuplicateArgumentException\fP"
.br
.ti -1c
.RI "class \fBCmdLineException\fP"
.br
.ti -1c
.RI "class \fBCmdLineI\fP"
.br
.ti -1c
.RI "class \fBCmdLineInvalidTypeException\fP"
.br
.ti -1c
.RI "class \fBCmdLineIS\fP"
.br
.ti -1c
.RI "class \fBCmdLineNotFoundException\fP"
.br
.ti -1c
.RI "class \fBCmdLineParameterException\fP"
.br
.ti -1c
.RI "class \fBCmdLineS\fP"
.br
.ti -1c
.RI "class \fBCmdLineValueException\fP"
.br
.ti -1c
.RI "class \fBHelpDetailedRequested\fP"
.br
.ti -1c
.RI "class \fBHelpRequested\fP"
.br
.ti -1c
.RI "class \fBParm\fP"
.br
.ti -1c
.RI "class \fBParmFlag\fP"
.br
.ti -1c
.RI "class \fBParmOption\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef vector< \fBParm\fP > \fBParameters\fP"
.br
.ti -1c
.RI "using \fBTYPE_STRING\fP = std::string"
.br
.ti -1c
.RI "using \fBTYPE_BOOL\fP = bool"
.br
.ti -1c
.RI "using \fBTYPE_NUMBER\fP = long"
.br
.ti -1c
.RI "using \fBTYPE_LONG\fP = long"
.br
.ti -1c
.RI "using \fBTYPE_INT\fP = int"
.br
.ti -1c
.RI "using \fBTYPE_DECIMAL\fP = float"
.br
.ti -1c
.RI "using \fBTYPE_FLOAT\fP = float"
.br
.ti -1c
.RI "using \fBTYPE_DOUBLE\fP = double"
.br
.ti -1c
.RI "using \fBTYPE_LONGNUMBER\fP = long long"
.br
.ti -1c
.RI "using \fBTYPE_LONGDECIMAL\fP = float"
.br
.ti -1c
.RI "using \fBTYPE_DATE\fP = std::tm"
.br
.ti -1c
.RI "using \fBTYPE_TIME\fP = std::tm"
.br
.ti -1c
.RI "using \fBTYPE_DATETIME\fP = std::tm"
.br
.ti -1c
.RI "using \fBTYPE_TMS\fP = char *"
.br
.ti -1c
.RI "using \fBTYPE_DIR\fP = std::filesystem::path"
.br
.ti -1c
.RI "using \fBTYPE_FILE\fP = std::filesystem::path"
.br
.ti -1c
.RI "using \fBFlags\fP = std::unordered_map< std::string, bool >"
.br
.ti -1c
.RI "using \fBOptions\fP = std::unordered_map< std::string, std::string >"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBType\fP { \fBSTRING\fP, \fBCHAR\fP, \fBBOOL\fP, \fBNUMBER\fP, \fBDECIMAL\fP, \fBLONGNUMBER\fP, \fBLONGDECIMAL\fP, \fBDATE\fP, \fBTIME\fP, \fBDATETIME\fP, \fBTMS\fP, \fBDIR\fP, \fBDIR_EXISTS\fP, \fBFILE\fP, \fBFILE_EXISTS\fP }"
.br
.ti -1c
.RI "enum class \fBSource\fP { \fBDEFAULT\fP, \fBENV\fP, \fBCMDLINE\fP, \fBCODE\fP, \fBAUTO\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_cleanClass\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCmdLine\fP * \fBsingleton_\fP = nullptr"
.br
.ti -1c
.RI "char ** \fB_argv\fP = nullptr"
.br
.ti -1c
.RI "int \fB_nargc\fP"
.br
.ti -1c
.RI "\fBParameters\fP \fB_parms\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for cmdline exceptions
.PP
As library process argument from command line it inherits from invalid_argument
.PP
\fBParameters\fP
.RS 4
\fImsg\fP Text to show 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "using \fBcmdline::Flags\fP = typedef std::unordered_map<std::string, bool>"

.PP
Definition at line \fB28\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::Options\fP = typedef std::unordered_map<std::string, std::string>"

.PP
Definition at line \fB29\fP of file \fBtypes\&.h\fP\&.
.SS "typedef vector<\fBParm\fP> \fBcmdline::Parameters\fP"

.PP
Definition at line \fB53\fP of file \fBcmdline\&.hpp\fP\&.
.SS "using \fBcmdline::TYPE_BOOL\fP = typedef bool"

.PP
Definition at line \fB12\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_DATE\fP = typedef std::tm"

.PP
Definition at line \fB21\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_DATETIME\fP = typedef std::tm"

.PP
Definition at line \fB23\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_DECIMAL\fP = typedef float"

.PP
Definition at line \fB16\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_DIR\fP = typedef std::filesystem::path"

.PP
Definition at line \fB25\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_DOUBLE\fP = typedef double"

.PP
Definition at line \fB18\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_FILE\fP = typedef std::filesystem::path"

.PP
Definition at line \fB26\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_FLOAT\fP = typedef float"

.PP
Definition at line \fB17\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_INT\fP = typedef int"

.PP
Definition at line \fB15\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_LONG\fP = typedef long"

.PP
Definition at line \fB14\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_LONGDECIMAL\fP = typedef float"

.PP
Definition at line \fB20\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_LONGNUMBER\fP = typedef long long"

.PP
Definition at line \fB19\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_NUMBER\fP = typedef long"

.PP
Definition at line \fB13\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_STRING\fP = typedef std::string"

.PP
Definition at line \fB11\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_TIME\fP = typedef std::tm"

.PP
Definition at line \fB22\fP of file \fBtypes\&.h\fP\&.
.SS "using \fBcmdline::TYPE_TMS\fP = typedef char *"

.PP
Definition at line \fB24\fP of file \fBtypes\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBcmdline::Source\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDEFAULT \fP\fP
.TP
\fB\fIENV \fP\fP
.TP
\fB\fICMDLINE \fP\fP
.TP
\fB\fICODE \fP\fP
.TP
\fB\fIAUTO \fP\fP
.PP
Definition at line \fB9\fP of file \fBtypes\&.h\fP\&.
.SS "enum class \fBcmdline::Type\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTRING \fP\fP
.TP
\fB\fICHAR \fP\fP
.TP
\fB\fIBOOL \fP\fP
.TP
\fB\fINUMBER \fP\fP
.TP
\fB\fIDECIMAL \fP\fP
.TP
\fB\fILONGNUMBER \fP\fP
.TP
\fB\fILONGDECIMAL \fP\fP
.TP
\fB\fIDATE \fP\fP
.TP
\fB\fITIME \fP\fP
.TP
\fB\fIDATETIME \fP\fP
.TP
\fB\fITMS \fP\fP
.TP
\fB\fIDIR \fP\fP
.TP
\fB\fIDIR_EXISTS \fP\fP
.TP
\fB\fIFILE \fP\fP
.TP
\fB\fIFILE_EXISTS \fP\fP
.PP
Definition at line \fB8\fP of file \fBtypes\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void cmdline::_cleanClass ()"

.PP
Definition at line \fB14\fP of file \fBcmdline_flavors\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char** cmdline::_argv = nullptr"

.PP
Definition at line \fB10\fP of file \fBcmdline_flavors\&.cpp\fP\&.
.SS "int cmdline::_nargc"

.PP
Definition at line \fB11\fP of file \fBcmdline_flavors\&.cpp\fP\&.
.SS "\fBParameters\fP cmdline::_parms"

.PP
Definition at line \fB12\fP of file \fBcmdline_flavors\&.cpp\fP\&.
.SS "\fBCmdLine\fP* cmdline::singleton_ = nullptr"

.PP
Definition at line \fB11\fP of file \fBcmdline\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
