.TH "cmdline/include/cmdline_errno.h" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline/include/cmdline_errno.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBERR_CMDLINE_EXCEPTION\fP   16000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERR_CMDLINE_EXCEPTION   16000"

.PP
Definition at line \fB3\fP of file \fBcmdline_errno\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
