.TH "CmdLineException" 3 "Sábado, 6 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdLineException
.SH SYNOPSIS
.br
.PP
.PP
Herencias invalid_argument\&.
.PP
Heredado por \fBCmdLineDuplicateArgumentException\fP, \fBCmdLineParameterException\fP, \fBCmdLineValueException\fP y \fBHelpException\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBCmdLineException\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "\fBCmdLineException\fP (char *txt)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB27\fP del archivo \fBcmdline_exceptions\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBCmdLineException\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB29\fP del archivo \fBcmdline_exceptions\&.hpp\fP\&.
.SS "~\fBCmdLineException\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB30\fP del archivo \fBcmdline_exceptions\&.hpp\fP\&.
.SS "\fBCmdLineException\fP (const char * fmt,  \&.\&.\&.)"

.PP
Definición en la línea \fB19\fP del archivo \fBcmdline_exceptions\&.cpp\fP\&.
.SS "\fBCmdLineException\fP (char * txt)"

.PP
Definición en la línea \fB18\fP del archivo \fBcmdline_exceptions\&.cpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
