.TH "libcmdline/include/cmdline.h" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/include/cmdline.h
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstruct_cmdline\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBstruct_cmdline\fP \fBCmdLine\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCmdLine\fP * \fBcmdline_create\fP (int argc, const char **argv, \fBParmDef\fP \fBparms\fP[])"
.br
.ti -1c
.RI "void \fBcmdline_delete\fP (\fBCmdLine\fP *\fBcmdline\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBstruct_cmdline\fP \fBCmdLine\fP"

.SH "Function Documentation"
.PP 
.SS "\fBCmdLine\fP * cmdline_create (int argc, const char ** argv, \fBParmDef\fP parms[])"

.PP
Definition at line \fB254\fP of file \fBinterface\&.cpp\fP\&.
.SS "void cmdline_delete (\fBCmdLine\fP * cmdline)"

.PP
Definition at line \fB284\fP of file \fBinterface\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
