.TH "cmdline::ParmOption" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline::ParmOption
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline\&.hpp>\fP
.PP
Inherits \fBcmdline::Parm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParmOption\fP ()=\fBdelete\fP"
.br
.ti -1c
.RI "\fBParmOption\fP (const char *\fBname\fP, const char *\fBvalue\fP)"
.br
.ti -1c
.RI "\fBParmOption\fP (const char *\fBname\fP, \fBType\fP \fBtype\fP)"
.br
.ti -1c
.RI "\fBParmOption\fP (const char *\fBname\fP, const char *\fBvalue\fP, bool \fBmultiple\fP)"
.br
.ti -1c
.RI "\fBParmOption\fP (const char *\fBname\fP, const char *\fBvalue\fP, \fBType\fP \fBtype\fP, bool \fBmultiple\fP=false)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB45\fP of file \fBcmdline\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cmdline::ParmOption::ParmOption ()\fC [delete]\fP"

.SS "cmdline::ParmOption::ParmOption (const char * name, const char * value)\fC [inline]\fP"

.PP
Definition at line \fB48\fP of file \fBcmdline\&.hpp\fP\&.
.SS "cmdline::ParmOption::ParmOption (const char * name, \fBType\fP type)\fC [inline]\fP"

.PP
Definition at line \fB49\fP of file \fBcmdline\&.hpp\fP\&.
.SS "cmdline::ParmOption::ParmOption (const char * name, const char * value, bool multiple)\fC [inline]\fP"

.PP
Definition at line \fB50\fP of file \fBcmdline\&.hpp\fP\&.
.SS "cmdline::ParmOption::ParmOption (const char * name, const char * value, \fBType\fP type, bool multiple = \fCfalse\fP)\fC [inline]\fP"

.PP
Definition at line \fB51\fP of file \fBcmdline\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
