.TH "CmdLineI" 3 "Sábado, 6 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdLineI
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBCmdLine\fP\&.
.PP
Heredado por \fBCmdLineIS\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBCmdLineI\fP (int argc, char **argv, Parameters parms)"
.br
.ti -1c
.RI "\fBCmdLineI\fP (int argc, char **argv, cmdline::Parameters parms, bool strict)"
.br
.in -1c
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static \fBCmdLine\fP \fBgetInstance\fP (int argc, char **argv, Parameters parms)"
.br
.in -1c
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 
Definición en la línea \fB153\fP del archivo \fBcmdline\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "\fBCmdLineI\fP (int argc, char ** argv, cmdline::Parameters parms)"

.PP
Definición en la línea \fB21\fP del archivo \fBcmdline_flavors\&.cpp\fP\&.
.SS "\fBCmdLineI\fP (int argc, char ** argv, cmdline::Parameters parms, bool strict)"

.PP
Definición en la línea \fB22\fP del archivo \fBcmdline_flavors\&.cpp\fP\&.
.SS "~\fBCmdLineI\fP ()"

.PP
Definición en la línea \fB18\fP del archivo \fBcmdline_flavors\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "\fBCmdLine\fP getInstance (int argc, char ** argv, cmdline::Parameters parms)\fC [static]\fP"

.PP
Definición en la línea \fB23\fP del archivo \fBcmdline_flavors\&.cpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
