.TH "libcmdline/src/commandline.cpp" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/src/commandline.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'config\&.h'\fP
.br
\fC#include 'commandline\&.hpp'\fP
.br
\fC#include 'argument\&.hpp'\fP
.br
\fC#include 'tools\&.hpp'\fP
.br
\fC#include 'validations\&.hpp'\fP
.br
\fC#include 'cmdline_exceptions\&.hpp'\fP
.br
\fC#include 'defines\&.hpp'\fP
.br
\fC#include 'commandline_aux\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_cmdline\fP"
.br
.RI "Private namespace\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_CRT_SECURE_NO_WARNINGS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_cmdline::launchHelpIfActive\fP (CommandLine *ptr)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr auto \fB_cmdline::OPTION_OR_DEFINITION\fP = '/'"
.br
.ti -1c
.RI "constexpr auto \fB_cmdline::FLAG_ACTIVE\fP = '+'"
.br
.ti -1c
.RI "constexpr auto \fB_cmdline::FLAG_INACTIVE\fP = '\-'"
.br
.ti -1c
.RI "ParameterTree * \fB_cmdline::rootOptions\fP [128]"
.br
.ti -1c
.RI "ParameterTree * \fB_cmdline::rootFlags\fP [128]"
.br
.ti -1c
.RI "char * \fB_cmdline::programName\fP = nullptr"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _CRT_SECURE_NO_WARNINGS"

.PP
Definition at line \fB1\fP of file \fBcommandline\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
