.TH "libcmdline/include/commandline.hpp" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/include/commandline.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.hpp'\fP
.br
\fC#include 'group\&.hpp'\fP
.br
\fC#include 'parameter_tree\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_cmdline::CommandLine\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_cmdline\fP"
.br
.RI "Private namespace\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENV_PREFFIX\fP   'env_preffix'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENV_PREFFIX   'env_preffix'"

.PP
Definition at line \fB4\fP of file \fBcommandline\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
