.TH "libcmdline/src/commandline.cpp" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/src/commandline.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'commandline\&.hpp'\fP
.br
\fC#include 'argument\&.hpp'\fP
.br
\fC#include 'tools\&.hpp'\fP
.br
\fC#include 'validations\&.hpp'\fP
.br
\fC#include 'cmdline_exceptions\&.hpp'\fP
.br
\fC#include 'defines\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_cmdline\fP"
.br
.in -1c
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fB_CRT_SECURE_NO_WARNINGS\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ParameterTree * \fB_cmdline::rootOptions\fP [128]"
.br
.ti -1c
.RI "ParameterTree * \fB_cmdline::rootFlags\fP [128]"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define _CRT_SECURE_NO_WARNINGS"

.PP
Definición en la línea \fB1\fP del archivo \fBcommandline\&.cpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
