.TH "cmdline/src/commandline.cpp" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline/src/commandline.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <any>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'parameter_tree\&.hpp'\fP
.br
\fC#include 'tools\&.h'\fP
.br
\fC#include 'defines\&.hpp'\fP
.br
\fC#include 'cmdline_exceptions\&.hpp'\fP
.br
\fC#include 'validations\&.h'\fP
.br
\fC#include 'commandline\&.hpp'\fP
.br
\fC#include 'msg_locale\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_cmdline\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENV_PREFFIX\fP   'env_preffix'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fB_cmdline::makeUpper\fP (const char *str)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ParameterTree * \fB_cmdline::rootOptions\fP [128]"
.br
.ti -1c
.RI "ParameterTree * \fB_cmdline::rootFlags\fP [128]"
.br
.ti -1c
.RI "char \fB_cmdline::_upper\fP [64] = ''"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENV_PREFFIX   'env_preffix'"

.PP
Definition at line \fB29\fP of file \fBcommandline\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
