.TH "libcmdline/src/config_ini.cpp" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/src/config_ini.cpp
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprocessIni\fP (char *file)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void processIni (char * file)"

.PP
Definition at line \fB1\fP of file \fBconfig_ini\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
