.TH "libcmdline/include/config.h" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/include/config.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCMDLINE_ERRNO\fP   16000"
.br
.ti -1c
.RI "#define \fBCMDLINE_CONFIG\fP   '/config'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CMDLINE_CONFIG   '/config'"

.PP
Definition at line \fB9\fP of file \fBconfig\&.h\fP\&.
.SS "#define CMDLINE_ERRNO   16000"

.PP
Definition at line \fB5\fP of file \fBconfig\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
