.TH "testcmdline/defaultsTest.cpp" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcmdline/defaultsTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'pch\&.h'\fP
.br
\fC#include '$tool\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (Defaults, Flags_2)"
.br
.ti -1c
.RI "\fBTEST\fP (Defaults, Flags_3)"
.br
.ti -1c
.RI "\fBTEST\fP (Defaults, Flags_0)"
.br
.ti -1c
.RI "\fBTEST\fP (Defaults, Options_0)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (Defaults, Flags_0)"

.PP
Definition at line \fB28\fP of file \fBdefaultsTest\&.cpp\fP\&.
.SS "TEST (Defaults, Flags_2)"

.PP
Definition at line \fB5\fP of file \fBdefaultsTest\&.cpp\fP\&.
.SS "TEST (Defaults, Flags_3)"

.PP
Definition at line \fB16\fP of file \fBdefaultsTest\&.cpp\fP\&.
.SS "TEST (Defaults, Options_0)"

.PP
Definition at line \fB35\fP of file \fBdefaultsTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
