.TH "testcmdline/definesTest.cpp" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcmdline/definesTest.cpp \- Test for definitions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pch\&.h'\fP
.br
\fC#include '$tool\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (Defines, Define_01)"
.br
.ti -1c
.RI "\fBTEST\fP (Defines, Define_02)"
.br
.ti -1c
.RI "\fBTEST\fP (Defines, Define_03)"
.br
.ti -1c
.RI "\fBTEST\fP (Defines, Define_multiple)"
.br
.ti -1c
.RI "\fBTEST\fP (Defines, Define_quoted)"
.br
.ti -1c
.RI "\fBTEST\fP (Defines, Define_KO_1)"
.br
.ti -1c
.RI "\fBTEST\fP (Defines, Define_KO_2)"
.br
.ti -1c
.RI "\fBTEST\fP (Defines, Define_KO_3)"
.br
.ti -1c
.RI "\fBTEST\fP (Defines, Define_multiple_1)"
.br
.ti -1c
.RI "\fBTEST\fP (Defines, Define_multiple_2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test for definitions\&. 


.PP
\fBAuthor\fP
.RS 4
Grandez 
.RE
.PP
\fBDate\fP
.RS 4
09/2021 
.RE
.PP

.PP
Definition in file \fBdefinesTest\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "TEST (Defines, Define_01)"

.PP
Definition at line \fB12\fP of file \fBdefinesTest\&.cpp\fP\&.
.SS "TEST (Defines, Define_02)"

.PP
Definition at line \fB19\fP of file \fBdefinesTest\&.cpp\fP\&.
.SS "TEST (Defines, Define_03)"

.PP
Definition at line \fB28\fP of file \fBdefinesTest\&.cpp\fP\&.
.SS "TEST (Defines, Define_KO_1)"

.PP
Definition at line \fB54\fP of file \fBdefinesTest\&.cpp\fP\&.
.SS "TEST (Defines, Define_KO_2)"

.PP
Definition at line \fB60\fP of file \fBdefinesTest\&.cpp\fP\&.
.SS "TEST (Defines, Define_KO_3)"

.PP
Definition at line \fB66\fP of file \fBdefinesTest\&.cpp\fP\&.
.SS "TEST (Defines, Define_multiple)"

.PP
Definition at line \fB36\fP of file \fBdefinesTest\&.cpp\fP\&.
.SS "TEST (Defines, Define_multiple_1)"

.PP
Definition at line \fB72\fP of file \fBdefinesTest\&.cpp\fP\&.
.SS "TEST (Defines, Define_multiple_2)"

.PP
Definition at line \fB81\fP of file \fBdefinesTest\&.cpp\fP\&.
.SS "TEST (Defines, Define_quoted)"

.PP
Definition at line \fB45\fP of file \fBdefinesTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
