.TH "driver_c/driver_c.c" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
driver_c/driver_c.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'cmdline\&.h'\fP
.br
\fC#include 'cmdline_types\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBParmDef\fP \fBparms\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB14\fP of file \fBdriver_c\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBParmDef\fP parms[]"
\fBInitial value:\fP
.PP
.nf
= {
     {"verbose", FLAG, "false", FALSE}
    ,{"output",  STRING, "", FALSE}
    ,0x0
}
.fi
.PP
Definition at line \fB8\fP of file \fBdriver_c\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
