.TH "testcmdline/exceptionsTest.cpp" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcmdline/exceptionsTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'pch\&.h'\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include '$tool\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (Exceptions, mistype)"
.br
.ti -1c
.RI "\fBTEST\fP (Exceptions, overtype)"
.br
.ti -1c
.RI "\fBTEST\fP (Exceptions, notfound)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (Exceptions, mistype)"

.PP
Definition at line \fB6\fP of file \fBexceptionsTest\&.cpp\fP\&.
.SS "TEST (Exceptions, notfound)"

.PP
Definition at line \fB40\fP of file \fBexceptionsTest\&.cpp\fP\&.
.SS "TEST (Exceptions, overtype)"

.PP
Definition at line \fB23\fP of file \fBexceptionsTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
