.TH "Flag" 3 "Sábado, 6 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Flag
.SH SYNOPSIS
.br
.PP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "logical \fBvalue\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB31\fP del archivo \fBtypes\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "const char* name"

.PP
Definición en la línea \fB32\fP del archivo \fBtypes\&.h\fP\&.
.SS "logical value"

.PP
Definición en la línea \fB33\fP del archivo \fBtypes\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
