.TH "packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1.4/build/native/include/gtest/gtest_prod.h" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1.4/build/native/include/gtest/gtest_prod.h
.SH SYNOPSIS
.br
.PP
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fBFRIEND_TEST\fP(test_case_name,  test_name)   friend class test_case_name##_##test_name##_Test"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define FRIEND_TEST(test_case_name, test_name)   friend class test_case_name##_##test_name##_Test"

.PP
Definición en la línea \fB58\fP del archivo \fBgtest_prod\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
