.TH "packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1.4/build/native/include/gtest/internal/gtest-string.h" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1.4/build/native/include/gtest/internal/gtest-string.h
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBtesting::internal::String\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtesting\fP"
.br
.ti -1c
.RI "namespace \fBtesting::internal\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "\fBGTEST_API_\fP std::string \fBtesting::internal::StringStreamToString\fP (::std::stringstream *stream)"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
