.TH "packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1.4/build/native/include/gtest/gtest-death-test.h" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1.4/build/native/include/gtest/gtest-death-test.h
.SH SYNOPSIS
.br
.PP
\fC#include 'gtest/internal/gtest\-death\-test\-internal\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtesting\fP"
.br
.in -1c
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fBGTEST_UNSUPPORTED_DEATH_TEST\fP(statement,  regex,  terminator)"
.br
.ti -1c
.RI "#define \fBEXPECT_DEATH_IF_SUPPORTED\fP(statement,  regex)       \fBGTEST_UNSUPPORTED_DEATH_TEST\fP(statement, regex, )"
.br
.ti -1c
.RI "#define \fBASSERT_DEATH_IF_SUPPORTED\fP(statement,  regex)       \fBGTEST_UNSUPPORTED_DEATH_TEST\fP(statement, regex, return)"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "\fBtesting::GTEST_DECLARE_string_\fP (death_test_style)"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define ASSERT_DEATH_IF_SUPPORTED(statement, regex)       \fBGTEST_UNSUPPORTED_DEATH_TEST\fP(statement, regex, return)"

.PP
Definición en la línea \fB338\fP del archivo \fBgtest\-death\-test\&.h\fP\&.
.SS "#define EXPECT_DEATH_IF_SUPPORTED(statement, regex)       \fBGTEST_UNSUPPORTED_DEATH_TEST\fP(statement, regex, )"

.PP
Definición en la línea \fB336\fP del archivo \fBgtest\-death\-test\&.h\fP\&.
.SS "#define GTEST_UNSUPPORTED_DEATH_TEST(statement, regex, terminator)"
\fBValor:\fP
.PP
.nf
    GTEST_AMBIGUOUS_ELSE_BLOCKER_ \
    if (::testing::internal::AlwaysTrue()) { \
      GTEST_LOG_(WARNING) \
          << "Death tests are not supported on this platform\&.\n" \
          << "Statement '" #statement "' cannot be verified\&."; \
    } else if (::testing::internal::AlwaysFalse()) { \\
      ::testing::internal::RE::PartialMatch("\&.*", (regex)); \
      GTEST_SUPPRESS_UNREACHABLE_CODE_WARNING_BELOW_(statement); \
      terminator; \
    } else \
      ::testing::Message()
.fi
.PP
Definición en la línea \fB312\fP del archivo \fBgtest\-death\-test\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
