.TH "HelpRequested" 3 "Jueves, 11 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelpRequested \- Excepcion generica sobre el parametro \fBhelp\fP  

.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 
Excepcion generica sobre el parametro \fBhelp\fP 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
