.TH "libcmdline/include/interface.cpp" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/include/interface.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'cmdline\&.hpp'\fP
.br
\fC#include 'cmdline\&.h'\fP
.br
\fC#include 'cmdline_exceptions\&.hpp'\fP
.br
\fC#include 'types\&.h'\fP
.br
\fC#include 'types\&.hpp'\fP
.br
\fC#include 'interface\&.hpp'\fP
.br
\fC#include 'cmdline_errno\&.h'\fP
.br
\fC#include 'tools\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > void * \fBcheckException\fP (T &ex)"
.br
.ti -1c
.RI "\fBlogical\fP \fBhasValue\fP (int target, const char *name)"
.br
.ti -1c
.RI "\fBlogical\fP \fBisMultiple\fP (bool option, const char *name)"
.br
.ti -1c
.RI "\fBcmdline::Parameters\fP \fBmakeParameters\fP (\fBParmDef\fP cparms[])"
.br
.ti -1c
.RI "const char ** \fB_makeArray\fP (vector< const char * > data)"
.br
.ti -1c
.RI "const char ** \fB_makeArray\fP (vector< string > data)"
.br
.ti -1c
.RI "\fBParameter\fP ** \fB_makeArrayParameter\fP (\fBcmdline::Options\fP data)"
.br
.ti -1c
.RI "const char * \fBgetValue\fP (bool option, const char *name)"
.br
.ti -1c
.RI "int \fBgetNumValues\fP (bool option, const char *name)"
.br
.ti -1c
.RI "const char ** \fBgetAllValues\fP (bool option, const char *name)"
.br
.ti -1c
.RI "\fBParameter\fP ** \fB_getOptions\fP (bool def)"
.br
.ti -1c
.RI "\fBFlag\fP ** \fBmakeFlags\fP (\fBcmdline::Flags\fP flags)"
.br
.ti -1c
.RI "\fBlogical\fP \fBcHasFlag\fP (const char *name)"
.br
.ti -1c
.RI "\fBlogical\fP \fBcHasOption\fP (const char *name)"
.br
.ti -1c
.RI "\fBlogical\fP \fBcHasDefine\fP (const char *name)"
.br
.ti -1c
.RI "\fBlogical\fP \fBcIsOptionMultiple\fP (const char *name)"
.br
.ti -1c
.RI "\fBlogical\fP \fBcIsDefineMultiple\fP (const char *name)"
.br
.ti -1c
.RI "int \fBcGetOptionNumValues\fP (const char *name)"
.br
.ti -1c
.RI "int \fBcGetDefineNumValues\fP (const char *name)"
.br
.ti -1c
.RI "const char * \fBcGetOption\fP (const char *name)"
.br
.ti -1c
.RI "const char * \fBcGetDefine\fP (const char *name)"
.br
.ti -1c
.RI "const char ** \fBcGetOptionValues\fP (const char *name)"
.br
.ti -1c
.RI "const char ** \fBcGetDefineValues\fP (const char *name)"
.br
.ti -1c
.RI "\fBFlag\fP ** \fBcGetDefaultFlags\fP (\fBlogical\fP active)"
.br
.ti -1c
.RI "\fBFlag\fP ** \fBcGetCurrentFlags\fP (\fBlogical\fP active)"
.br
.ti -1c
.RI "\fBParameter\fP ** \fBcGetDefaultOptions\fP ()"
.br
.ti -1c
.RI "\fBParameter\fP ** \fBcGetCurrentOptions\fP ()"
.br
.ti -1c
.RI "\fBParameter\fP ** \fBcGetDefinitions\fP ()"
.br
.ti -1c
.RI "\fBCmdLine\fP * \fBcmdline_create\fP (int argc, const char **arg, \fBParmDef\fP cparms[])"
.br
.ti -1c
.RI "void \fBcmdline_delete\fP (\fBCmdLine\fP *\fBcmdline\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBParameter\fP ** _getOptions (bool def)"

.PP
Definition at line \fB158\fP of file \fBinterface\&.cpp\fP\&.
.SS "const char ** _makeArray (vector< const char * > data)"

.PP
Definition at line \fB75\fP of file \fBinterface\&.cpp\fP\&.
.SS "const char ** _makeArray (vector< string > data)"

.PP
Definition at line \fB88\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBParameter\fP ** _makeArrayParameter (\fBcmdline::Options\fP data)"

.PP
Definition at line \fB102\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBFlag\fP ** cGetCurrentFlags (\fBlogical\fP active)"

.PP
Definition at line \fB233\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBParameter\fP ** cGetCurrentOptions ()"

.PP
Definition at line \fB246\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBFlag\fP ** cGetDefaultFlags (\fBlogical\fP active)"

.PP
Definition at line \fB223\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBParameter\fP ** cGetDefaultOptions ()"

.PP
Definition at line \fB243\fP of file \fBinterface\&.cpp\fP\&.
.SS "const char * cGetDefine (const char * name)"

.PP
Definition at line \fB219\fP of file \fBinterface\&.cpp\fP\&.
.SS "int cGetDefineNumValues (const char * name)"

.PP
Definition at line \fB217\fP of file \fBinterface\&.cpp\fP\&.
.SS "const char ** cGetDefineValues (const char * name)"

.PP
Definition at line \fB221\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBParameter\fP ** cGetDefinitions ()"

.PP
Definition at line \fB249\fP of file \fBinterface\&.cpp\fP\&.
.SS "const char * cGetOption (const char * name)"

.PP
Definition at line \fB218\fP of file \fBinterface\&.cpp\fP\&.
.SS "int cGetOptionNumValues (const char * name)"

.PP
Definition at line \fB216\fP of file \fBinterface\&.cpp\fP\&.
.SS "const char ** cGetOptionValues (const char * name)"

.PP
Definition at line \fB220\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBlogical\fP cHasDefine (const char * name)"

.PP
Definition at line \fB213\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBlogical\fP cHasFlag (const char * name)"

.PP
Definition at line \fB211\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBlogical\fP cHasOption (const char * name)"

.PP
Definition at line \fB212\fP of file \fBinterface\&.cpp\fP\&.
.SS "template<typename T > void * checkException (T & ex)"

.PP
Definition at line \fB22\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBlogical\fP cIsDefineMultiple (const char * name)"

.PP
Definition at line \fB215\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBlogical\fP cIsOptionMultiple (const char * name)"

.PP
Definition at line \fB214\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBCmdLine\fP * cmdline_create (int argc, const char ** arg, \fBParmDef\fP cparms[])"

.PP
Definition at line \fB254\fP of file \fBinterface\&.cpp\fP\&.
.SS "void cmdline_delete (\fBCmdLine\fP * cmdline)"

.PP
Definition at line \fB284\fP of file \fBinterface\&.cpp\fP\&.
.SS "const char ** getAllValues (bool option, const char * name)"

.PP
Definition at line \fB147\fP of file \fBinterface\&.cpp\fP\&.
.SS "int getNumValues (bool option, const char * name)"

.PP
Definition at line \fB134\fP of file \fBinterface\&.cpp\fP\&.
.SS "const char * getValue (bool option, const char * name)"

.PP
Definition at line \fB123\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBlogical\fP hasValue (int target, const char * name)"

.PP
Definition at line \fB37\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBlogical\fP isMultiple (bool option, const char * name)"

.PP
Definition at line \fB52\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBFlag\fP ** makeFlags (\fBcmdline::Flags\fP flags)"

.PP
Definition at line \fB193\fP of file \fBinterface\&.cpp\fP\&.
.SS "\fBcmdline::Parameters\fP makeParameters (\fBParmDef\fP cparms[])"

.PP
Definition at line \fB64\fP of file \fBinterface\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
