.TH "testcmdline/mainTest.cpp" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcmdline/mainTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'pch\&.h'\fP
.br
\fC#include '$tool\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBTool\fP \fBtool\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line \fB22\fP of file \fBmainTest\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBTool\fP tool"

.PP
Definition at line \fB8\fP of file \fBmainTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
