.TH "libcmdline/include/msg_locale.hpp" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/include/msg_locale.hpp
.SH SYNOPSIS
.br
.PP
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fBTXT_HELP\fP   'Help requested'"
.br
.ti -1c
.RI "#define \fBTXT_HELP_DETAIL\fP   'Help detailed requested'"
.br
.ti -1c
.RI "#define \fBTXT_ARG_INVALID\fP   'Invalid argument: '%s''"
.br
.ti -1c
.RI "#define \fBTXT_ARG_EXPECTED\fP   'Invalid argument: '%s'\&. Expected '%s''"
.br
.ti -1c
.RI "#define \fBTXT_VAL_INVALID\fP   'Invalid value: %s'"
.br
.ti -1c
.RI "#define \fBTXT_VAL_EXPECTED\fP   'Invalid value: %s\&. Expected '%s''"
.br
.ti -1c
.RI "#define \fBTXT_ARG_SET\fP   'Parameter already set: %s'"
.br
.ti -1c
.RI "#define \fBTXT_ARG_NFND\fP   ''%s' Not found'"
.br
.ti -1c
.RI "#define \fBTXT_ARG_NFND1\fP   ''%s' Not found\&. Maybe you tried '%s''"
.br
.ti -1c
.RI "#define \fBTXT_ARG_NFND2\fP   ''%s' Not found\&. Maybe you tried '%s%s''"
.br
.ti -1c
.RI "#define \fBTXT_ARG_NFND3\fP   ''%s' Not found\&. Maybe is  incomplete'"
.br
.ti -1c
.RI "#define \fBINV_DEFINITION\fP   'Invalid definition: '%s''"
.br
.ti -1c
.RI "#define \fBERR_ARG_MISSING\fP   'Missing value for: '%s''"
.br
.ti -1c
.RI "#define \fBERR_ARG_ERR\fP   'Invalid argument: '%s''"
.br
.ti -1c
.RI "#define \fBERR_INV_OPTION\fP   'Invalid option: '%s''"
.br
.ti -1c
.RI "#define \fBERR_NOT_FND\fP   'Parameter not found: '%s''"
.br
.ti -1c
.RI "#define \fBERR_INV_TYPE\fP   'Invalid type\&. Expected '%s''"
.br
.ti -1c
.RI "#define \fBERR_ARG_DUP\fP   'Parameter already set: '%s''"
.br
.ti -1c
.RI "#define \fBTXT_NO_DIR\fP   'Is not a directory'"
.br
.ti -1c
.RI "#define \fBTXT_DIR_NOTFND\fP   'Directory not found'"
.br
.ti -1c
.RI "#define \fBTXT_FILE_NOTFND\fP   'File not found'"
.br
.ti -1c
.RI "#define \fBTXT_FILE_DIR\fP   'Is a directory'"
.br
.ti -1c
.RI "#define \fBTXT_DATE\fP   'Date'"
.br
.ti -1c
.RI "#define \fBTXT_TIME\fP   'Time'"
.br
.ti -1c
.RI "#define \fBTXT_DATETIME\fP   'Datetime'"
.br
.ti -1c
.RI "#define \fBTXT_TMS\fP   'Timestamp'"
.br
.ti -1c
.RI "#define \fBTXT_NUMBER\fP   'Number'"
.br
.ti -1c
.RI "#define \fBTXT_DECIMAL\fP   'Decimal'"
.br
.ti -1c
.RI "#define \fBTXT_LONGNUMBER\fP   'Long Number'"
.br
.ti -1c
.RI "#define \fBTXT_LONGDECIMAL\fP   'Long Decimal'"
.br
.ti -1c
.RI "#define \fBTXT_DIR\fP   'Directory'"
.br
.ti -1c
.RI "#define \fBTXT_FILE\fP   'File'"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define ERR_ARG_DUP   'Parameter already set: '%s''"

.PP
Definición en la línea \fB20\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define ERR_ARG_ERR   'Invalid argument: '%s''"

.PP
Definición en la línea \fB16\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define ERR_ARG_MISSING   'Missing value for: '%s''"

.PP
Definición en la línea \fB15\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define ERR_INV_OPTION   'Invalid option: '%s''"

.PP
Definición en la línea \fB17\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define ERR_INV_TYPE   'Invalid type\&. Expected '%s''"

.PP
Definición en la línea \fB19\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define ERR_NOT_FND   'Parameter not found: '%s''"

.PP
Definición en la línea \fB18\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define INV_DEFINITION   'Invalid definition: '%s''"

.PP
Definición en la línea \fB14\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_ARG_EXPECTED   'Invalid argument: '%s'\&. Expected '%s''"

.PP
Definición en la línea \fB6\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_ARG_INVALID   'Invalid argument: '%s''"

.PP
Definición en la línea \fB5\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_ARG_NFND   ''%s' Not found'"

.PP
Definición en la línea \fB10\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_ARG_NFND1   ''%s' Not found\&. Maybe you tried '%s''"

.PP
Definición en la línea \fB11\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_ARG_NFND2   ''%s' Not found\&. Maybe you tried '%s%s''"

.PP
Definición en la línea \fB12\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_ARG_NFND3   ''%s' Not found\&. Maybe is  incomplete'"

.PP
Definición en la línea \fB13\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_ARG_SET   'Parameter already set: %s'"

.PP
Definición en la línea \fB9\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_DATE   'Date'"

.PP
Definición en la línea \fB26\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_DATETIME   'Datetime'"

.PP
Definición en la línea \fB28\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_DECIMAL   'Decimal'"

.PP
Definición en la línea \fB31\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_DIR   'Directory'"

.PP
Definición en la línea \fB34\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_DIR_NOTFND   'Directory not found'"

.PP
Definición en la línea \fB22\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_FILE   'File'"

.PP
Definición en la línea \fB35\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_FILE_DIR   'Is a directory'"

.PP
Definición en la línea \fB24\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_FILE_NOTFND   'File not found'"

.PP
Definición en la línea \fB23\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_HELP   'Help requested'"

.PP
Definición en la línea \fB3\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_HELP_DETAIL   'Help detailed requested'"

.PP
Definición en la línea \fB4\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_LONGDECIMAL   'Long Decimal'"

.PP
Definición en la línea \fB33\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_LONGNUMBER   'Long Number'"

.PP
Definición en la línea \fB32\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_NO_DIR   'Is not a directory'"

.PP
Definición en la línea \fB21\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_NUMBER   'Number'"

.PP
Definición en la línea \fB30\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_TIME   'Time'"

.PP
Definición en la línea \fB27\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_TMS   'Timestamp'"

.PP
Definición en la línea \fB29\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_VAL_EXPECTED   'Invalid value: %s\&. Expected '%s''"

.PP
Definición en la línea \fB8\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SS "#define TXT_VAL_INVALID   'Invalid value: %s'"

.PP
Definición en la línea \fB7\fP del archivo \fBmsg_locale\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
