.TH "docs/doxygen/namespaces.dox" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docs/doxygen/namespaces.dox
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcmdline\fP"
.br
.RI "Public namespace to avoid naming mangling\&. "
.ti -1c
.RI "namespace \fB_cmdline\fP"
.br
.RI "Private namespace\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
