.TH "CmdLineException" 3 "Jueves, 11 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CmdLineException
.SH SYNOPSIS
.br
.PP
.PP
Herencias invalid_argument\&.
.PP
Heredado por \fBCmdLineDuplicateArgumentException\fP, \fBCmdLineParameterException\fP, \fBCmdLineValueException\fP y \fBHelpRequested\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBCmdLineException\fP (const char *fmt,\&.\&.\&.)"
.br
.ti -1c
.RI "\fBCmdLineException\fP (char *txt)"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "string \fBtype\fP"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
