.TH "Define" 3 "Jueves, 11 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Define
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBArgument\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBDefine\fP (const char *name, const char *value)"
.br
.ti -1c
.RI "\fBDefine\fP (const char *name)"
.br
.ti -1c
.RI "void \fBinitValues\fP (vector< string > values)"
.br
.in -1c
.SS "Otros miembros heredados"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
