.TH "libcmdline/include/parameter_tree.hpp" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/include/parameter_tree.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <unordered_map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_cmdline::ParameterTree\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_cmdline\fP"
.br
.RI "Private namespace\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
