.TH "ParmFlag" 3 "Lunes, 8 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParmFlag \- Wrapper of \fBParm\fP to define Flags 
.br
  

.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 
Wrapper of \fBParm\fP to define Flags 
.br
 

A parm has 4 properties:
.PP
.IP "\(bu" 2
\fBname\fP: Name of parameter 
.br

.IP "\(bu" 2
\fBvalue\fP: active o disabled (default) 
.PP


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
