.TH "std" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtr1\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
