.TH "std::tr1" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgtest_internal\fP"
.br
.in -1c
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBtuple\fP"
.br
.ti -1c
.RI "class \fBtuple<>\fP"
.br
.ti -1c
.RI "struct \fBtuple_element\fP"
.br
.ti -1c
.RI "struct \fBtuple_size\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_0_TUPLE_(T) >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_10_TUPLE_(T) >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_1_TUPLE_(T) >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_2_TUPLE_(T) >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_3_TUPLE_(T) >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_4_TUPLE_(T) >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_5_TUPLE_(T) >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_6_TUPLE_(T) >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_7_TUPLE_(T) >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_8_TUPLE_(T) >\fP"
.br
.ti -1c
.RI "struct \fBtuple_size< GTEST_9_TUPLE_(T) >\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "template<\fBGTEST_1_TYPENAMES_\fP(T) > class \fBGTEST_1_TUPLE_\fP (T)"
.br
.ti -1c
.RI "template<\fBGTEST_2_TYPENAMES_\fP(T) > class \fBGTEST_2_TUPLE_\fP (T)"
.br
.ti -1c
.RI "template<\fBGTEST_3_TYPENAMES_\fP(T) > class \fBGTEST_3_TUPLE_\fP (T)"
.br
.ti -1c
.RI "template<\fBGTEST_4_TYPENAMES_\fP(T) > class \fBGTEST_4_TUPLE_\fP (T)"
.br
.ti -1c
.RI "template<\fBGTEST_5_TYPENAMES_\fP(T) > class \fBGTEST_5_TUPLE_\fP (T)"
.br
.ti -1c
.RI "template<\fBGTEST_6_TYPENAMES_\fP(T) > class \fBGTEST_6_TUPLE_\fP (T)"
.br
.ti -1c
.RI "template<\fBGTEST_7_TYPENAMES_\fP(T) > class \fBGTEST_7_TUPLE_\fP (T)"
.br
.ti -1c
.RI "template<\fBGTEST_8_TYPENAMES_\fP(T) > class \fBGTEST_8_TUPLE_\fP (T)"
.br
.ti -1c
.RI "template<\fBGTEST_9_TYPENAMES_\fP(T) > class \fBGTEST_9_TUPLE_\fP (T)"
.br
.ti -1c
.RI "\fBtuple\fP \fBmake_tuple\fP ()"
.br
.ti -1c
.RI "template<\fBGTEST_1_TYPENAMES_\fP(T) > \fBGTEST_1_TUPLE_\fP (T) \fBmake_tuple\fP(const T0 &f0)"
.br
.ti -1c
.RI "template<\fBGTEST_2_TYPENAMES_\fP(T) > \fBGTEST_2_TUPLE_\fP (T) \fBmake_tuple\fP(const T0 &f0"
.br
.ti -1c
.RI "template<\fBGTEST_3_TYPENAMES_\fP(T) > \fBGTEST_3_TUPLE_\fP (T) \fBmake_tuple\fP(const T0 &f0"
.br
.ti -1c
.RI "template<\fBGTEST_4_TYPENAMES_\fP(T) > \fBGTEST_4_TUPLE_\fP (T) \fBmake_tuple\fP(const T0 &f0"
.br
.ti -1c
.RI "template<\fBGTEST_5_TYPENAMES_\fP(T) > \fBGTEST_5_TUPLE_\fP (T) \fBmake_tuple\fP(const T0 &f0"
.br
.ti -1c
.RI "template<\fBGTEST_6_TYPENAMES_\fP(T) > \fBGTEST_6_TUPLE_\fP (T) \fBmake_tuple\fP(const T0 &f0"
.br
.ti -1c
.RI "template<\fBGTEST_7_TYPENAMES_\fP(T) > \fBGTEST_7_TUPLE_\fP (T) \fBmake_tuple\fP(const T0 &f0"
.br
.ti -1c
.RI "template<\fBGTEST_8_TYPENAMES_\fP(T) > \fBGTEST_8_TUPLE_\fP (T) \fBmake_tuple\fP(const T0 &f0"
.br
.ti -1c
.RI "template<\fBGTEST_9_TYPENAMES_\fP(T) > \fBGTEST_9_TUPLE_\fP (T) \fBmake_tuple\fP(const T0 &f0"
.br
.ti -1c
.RI "template<\fBGTEST_10_TYPENAMES_\fP(T) > \fBGTEST_10_TUPLE_\fP (T) \fBmake_tuple\fP(const T0 &f0"
.br
.ti -1c
.RI "template<int k, \fBGTEST_10_TYPENAMES_\fP(T) > \fBGTEST_ADD_REF_\fP (\fBGTEST_TUPLE_ELEMENT_\fP(k, \fBGTEST_10_TUPLE_\fP(T))) get(\fBGTEST_10_TUPLE_\fP(T) &t)"
.br
.ti -1c
.RI "template<int k, \fBGTEST_10_TYPENAMES_\fP(T) > \fBGTEST_BY_REF_\fP (\fBGTEST_TUPLE_ELEMENT_\fP(k, \fBGTEST_10_TUPLE_\fP(T))) get(const \fBGTEST_10_TUPLE_\fP(T) &t)"
.br
.ti -1c
.RI "template<\fBGTEST_10_TYPENAMES_\fP(T) , \fBGTEST_10_TYPENAMES_\fP(U) > bool \fBoperator==\fP (const \fBGTEST_10_TUPLE_\fP(T)&t, const \fBGTEST_10_TUPLE_\fP(U)&u)"
.br
.ti -1c
.RI "template<\fBGTEST_10_TYPENAMES_\fP(T) , \fBGTEST_10_TYPENAMES_\fP(U) > bool \fBoperator!=\fP (const \fBGTEST_10_TUPLE_\fP(T)&t, const \fBGTEST_10_TUPLE_\fP(U)&u)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const T1 & \fBf1\fP"
.br
.ti -1c
.RI "const T1 const T2 & \fBf2\fP"
.br
.ti -1c
.RI "const T1 const T2 const T3 & \fBf3\fP"
.br
.ti -1c
.RI "const T1 const T2 const T3 const T4 & \fBf4\fP"
.br
.ti -1c
.RI "const T1 const T2 const T3 const T4 const T5 & \fBf5\fP"
.br
.ti -1c
.RI "const T1 const T2 const T3 const T4 const T5 const T6 & \fBf6\fP"
.br
.ti -1c
.RI "const T1 const T2 const T3 const T4 const T5 const T6 const T7 & \fBf7\fP"
.br
.ti -1c
.RI "const T1 const T2 const T3 const T4 const T5 const T6 const T7 const T8 & \fBf8\fP"
.br
.ti -1c
.RI "const T1 const T2 const T3 const T4 const T5 const T6 const T7 const T8 const T9 & \fBf9\fP"
.br
.in -1c
.SH "Documentación de las funciones"
.PP 
.SS "template<\fBGTEST_10_TYPENAMES_\fP(T) > std::tr1::GTEST_10_TUPLE_ (T) const &\fC [inline]\fP"

.SS "template<\fBGTEST_1_TYPENAMES_\fP(T) > class std::tr1::GTEST_1_TUPLE_ (T)"

.PP
Definición en la línea \fB1\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_1_TYPENAMES_\fP(T) > std::tr1::GTEST_1_TUPLE_ (T) const &\fC [inline]\fP"

.PP
Definición en la línea \fB679\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_2_TYPENAMES_\fP(T) > class std::tr1::GTEST_2_TUPLE_ (T)"

.PP
Definición en la línea \fB1\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_2_TYPENAMES_\fP(T) > std::tr1::GTEST_2_TUPLE_ (T) const &\fC [inline]\fP"

.SS "template<\fBGTEST_3_TYPENAMES_\fP(T) > class std::tr1::GTEST_3_TUPLE_ (T)"

.PP
Definición en la línea \fB1\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_3_TYPENAMES_\fP(T) > std::tr1::GTEST_3_TUPLE_ (T) const &\fC [inline]\fP"

.SS "template<\fBGTEST_4_TYPENAMES_\fP(T) > class std::tr1::GTEST_4_TUPLE_ (T)"

.PP
Definición en la línea \fB1\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_4_TYPENAMES_\fP(T) > std::tr1::GTEST_4_TUPLE_ (T) const &\fC [inline]\fP"

.SS "template<\fBGTEST_5_TYPENAMES_\fP(T) > class std::tr1::GTEST_5_TUPLE_ (T)"

.PP
Definición en la línea \fB1\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_5_TYPENAMES_\fP(T) > std::tr1::GTEST_5_TUPLE_ (T) const &\fC [inline]\fP"

.SS "template<\fBGTEST_6_TYPENAMES_\fP(T) > class std::tr1::GTEST_6_TUPLE_ (T)"

.PP
Definición en la línea \fB1\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_6_TYPENAMES_\fP(T) > std::tr1::GTEST_6_TUPLE_ (T) const &\fC [inline]\fP"

.SS "template<\fBGTEST_7_TYPENAMES_\fP(T) > class std::tr1::GTEST_7_TUPLE_ (T)"

.PP
Definición en la línea \fB1\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_7_TYPENAMES_\fP(T) > std::tr1::GTEST_7_TUPLE_ (T) const &\fC [inline]\fP"

.SS "template<\fBGTEST_8_TYPENAMES_\fP(T) > class std::tr1::GTEST_8_TUPLE_ (T)"

.PP
Definición en la línea \fB1\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_8_TYPENAMES_\fP(T) > std::tr1::GTEST_8_TUPLE_ (T) const &\fC [inline]\fP"

.SS "template<\fBGTEST_9_TYPENAMES_\fP(T) > class std::tr1::GTEST_9_TUPLE_ (T)"

.PP
Definición en la línea \fB1\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_9_TYPENAMES_\fP(T) > std::tr1::GTEST_9_TUPLE_ (T) const &\fC [inline]\fP"

.SS "template<int k, \fBGTEST_10_TYPENAMES_\fP(T) > std::tr1::GTEST_ADD_REF_ (\fBGTEST_TUPLE_ELEMENT_\fP(k, \fBGTEST_10_TUPLE_\fP(T))) &"

.PP
Definición en la línea \fB931\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<int k, \fBGTEST_10_TYPENAMES_\fP(T) > std::tr1::GTEST_BY_REF_ (\fBGTEST_TUPLE_ELEMENT_\fP(k, \fBGTEST_10_TUPLE_\fP(T))) const &"

.PP
Definición en la línea \fB937\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "\fBtuple\fP std::tr1::make_tuple ()\fC [inline]\fP"

.PP
Definición en la línea \fB676\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_10_TYPENAMES_\fP(T) , \fBGTEST_10_TYPENAMES_\fP(U) > bool std::tr1::operator!= (const \fBGTEST_10_TUPLE_\fP(T)& t, const \fBGTEST_10_TUPLE_\fP(U)& u)\fC [inline]\fP"

.PP
Definición en la línea \fB983\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<\fBGTEST_10_TYPENAMES_\fP(T) , \fBGTEST_10_TYPENAMES_\fP(U) > bool std::tr1::operator== (const \fBGTEST_10_TUPLE_\fP(T)& t, const \fBGTEST_10_TUPLE_\fP(U)& u)\fC [inline]\fP"

.PP
Definición en la línea \fB975\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SH "Documentación de las variables"
.PP 
.SS "const T1 & std::tr1::f1"
\fBValor inicial:\fP
.PP
.nf
{
  return GTEST_2_TUPLE_(T)(f0, f1)
.fi
.PP
Definición en la línea \fB684\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "const T1 const T2 & std::tr1::f2"
\fBValor inicial:\fP
.PP
.nf
{
  return GTEST_3_TUPLE_(T)(f0, f1, f2)
.fi
.PP
Definición en la línea \fB689\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "const T1 const T2 const T3 & std::tr1::f3"
\fBValor inicial:\fP
.PP
.nf
{
  return GTEST_4_TUPLE_(T)(f0, f1, f2, f3)
.fi
.PP
Definición en la línea \fB695\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "const T1 const T2 const T3 const T4 & std::tr1::f4"
\fBValor inicial:\fP
.PP
.nf
{
  return GTEST_5_TUPLE_(T)(f0, f1, f2, f3, f4)
.fi
.PP
Definición en la línea \fB701\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "const T1 const T2 const T3 const T4 const T5 & std::tr1::f5"
\fBValor inicial:\fP
.PP
.nf
{
  return GTEST_6_TUPLE_(T)(f0, f1, f2, f3, f4, f5)
.fi
.PP
Definición en la línea \fB707\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "const T1 const T2 const T3 const T4 const T5 const T6 & std::tr1::f6"
\fBValor inicial:\fP
.PP
.nf
{
  return GTEST_7_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6)
.fi
.PP
Definición en la línea \fB713\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "const T1 const T2 const T3 const T4 const T5 const T6 const T7 & std::tr1::f7"
\fBValor inicial:\fP
.PP
.nf
{
  return GTEST_8_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6, f7)
.fi
.PP
Definición en la línea \fB719\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "const T1 const T2 const T3 const T4 const T5 const T6 const T7 const T8 & std::tr1::f8"
\fBValor inicial:\fP
.PP
.nf
{
  return GTEST_9_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6, f7, f8)
.fi
.PP
Definición en la línea \fB726\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "const T1 const T2 const T3 const T4 const T5 const T6 const T7 const T8 const T9& std::tr1::f9"
\fBValor inicial:\fP
.PP
.nf
{
  return GTEST_10_TUPLE_(T)(f0, f1, f2, f3, f4, f5, f6, f7, f8, f9)
.fi
.PP
Definición en la línea \fB733\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
