.TH "std::tr1::gtest_internal::SameSizeTuplePrefixComparator< 0, 0 >" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::gtest_internal::SameSizeTuplePrefixComparator< 0, 0 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class Tuple1 , class Tuple2 > static bool \fBEq\fP (const Tuple1 &, const Tuple2 &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB956\fP of file \fBgtest\-tuple\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class Tuple1 , class Tuple2 > static bool \fBstd::tr1::gtest_internal::SameSizeTuplePrefixComparator\fP< 0, 0 >::Eq (const Tuple1 &, const Tuple2 &)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB958\fP of file \fBgtest\-tuple\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
