.TH "std::tr1::gtest_internal::SameSizeTuplePrefixComparator< 0, 0 >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::gtest_internal::SameSizeTuplePrefixComparator< 0, 0 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "template<class Tuple1 , class Tuple2 > static bool \fBEq\fP (const Tuple1 &, const Tuple2 &)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB956\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<class Tuple1 , class Tuple2 > static bool \fBstd::tr1::gtest_internal::SameSizeTuplePrefixComparator\fP< 0, 0 >::Eq (const Tuple1 &, const Tuple2 &)\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB958\fP del archivo \fBgtest\-tuple\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
