.TH "std::tr1::tuple<>" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::tuple<>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtuple\fP ()"
.br
.ti -1c
.RI "\fBtuple\fP (const \fBtuple\fP &)"
.br
.ti -1c
.RI "\fBtuple\fP & \fBoperator=\fP (const \fBtuple\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB206\fP of file \fBgtest\-tuple\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBstd::tr1::tuple\fP<>::\fBtuple\fP ()\fC [inline]\fP"

.PP
Definition at line \fB208\fP of file \fBgtest\-tuple\&.h\fP\&.
.SS "\fBstd::tr1::tuple\fP<>::\fBtuple\fP (const \fBtuple\fP<> &)\fC [inline]\fP"

.PP
Definition at line \fB209\fP of file \fBgtest\-tuple\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBtuple\fP & \fBstd::tr1::tuple\fP<>::operator= (const \fBtuple\fP<> &)\fC [inline]\fP"

.PP
Definition at line \fB210\fP of file \fBgtest\-tuple\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
