.TH "std::tr1::tuple_size< GTEST_10_TUPLE_(T) >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::tuple_size< GTEST_10_TUPLE_(T) >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static const int \fBvalue\fP = 10"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<\fBGTEST_10_TYPENAMES_\fP(T)>
.br
struct std::tr1::tuple_size< GTEST_10_TUPLE_(T) >"
.PP
Definición en la línea \fB792\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<\fBGTEST_10_TYPENAMES_\fP(T) > const int \fBstd::tr1::tuple_size\fP< \fBGTEST_10_TUPLE_\fP(T) >::value = 10\fC [static]\fP"

.PP
Definición en la línea \fB793\fP del archivo \fBgtest\-tuple\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
