.TH "std::tr1::gtest_internal::Get< 3 >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::gtest_internal::Get< 3 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "template<class Tuple > static \fBGTEST_ADD_REF_\fP (\fBGTEST_TUPLE_ELEMENT_\fP(3, Tuple)) Field(Tuple &t)"
.br
.ti -1c
.RI "template<class Tuple > static \fBGTEST_BY_REF_\fP (\fBGTEST_TUPLE_ELEMENT_\fP(3, Tuple)) ConstField(const Tuple &t)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB845\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<class Tuple > static \fBstd::tr1::gtest_internal::Get\fP< 3 >::GTEST_ADD_REF_ (\fBGTEST_TUPLE_ELEMENT_\fP(3, Tuple)) &\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB848\fP del archivo \fBgtest\-tuple\&.h\fP\&.
.SS "template<class Tuple > static \fBstd::tr1::gtest_internal::Get\fP< 3 >::GTEST_BY_REF_ (\fBGTEST_TUPLE_ELEMENT_\fP(3, Tuple)) const &\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB852\fP del archivo \fBgtest\-tuple\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
