.TH "std::tr1::gtest_internal::SameSizeTuplePrefixComparator< k, k >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::gtest_internal::SameSizeTuplePrefixComparator< k, k >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-tuple\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<class Tuple1 , class Tuple2 > static bool \fBEq\fP (const Tuple1 &t1, const Tuple2 &t2)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int k>
.br
struct std::tr1::gtest_internal::SameSizeTuplePrefixComparator< k, k >"
.PP
Definition at line \fB964\fP of file \fBgtest\-tuple\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<int k> template<class Tuple1 , class Tuple2 > static bool \fBstd::tr1::gtest_internal::SameSizeTuplePrefixComparator\fP< k, k >::Eq (const Tuple1 & t1, const Tuple2 & t2)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB966\fP of file \fBgtest\-tuple\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
