.TH "testing::WithParamInterface< T >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::WithParamInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.PP
Inherited by \fBtesting::TestWithParam< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBParamType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~WithParamInterface\fP ()"
.br
.ti -1c
.RI "const \fBParamType\fP & \fBGetParam\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class TestClass > class \fBinternal::ParameterizedTestFactory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class testing::WithParamInterface< T >"
.PP
Definition at line \fB1795\fP of file \fBgtest\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef T \fBtesting::WithParamInterface\fP< T >::\fBParamType\fP"

.PP
Definition at line \fB1797\fP of file \fBgtest\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > virtual \fBtesting::WithParamInterface\fP< T >::~\fBWithParamInterface\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB1798\fP of file \fBgtest\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > const \fBParamType\fP & \fBtesting::WithParamInterface\fP< T >::GetParam () const\fC [inline]\fP"

.PP
Definition at line \fB1805\fP of file \fBgtest\&.h\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename T > template<class TestClass > friend class \fBinternal::ParameterizedTestFactory\fP\fC [friend]\fP"

.PP
Definition at line \fB1823\fP of file \fBgtest\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
