.TH "testing::internal::ParameterizedTestCaseRegistry" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParameterizedTestCaseRegistry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBParameterizedTestCaseRegistry\fP ()"
.br
.ti -1c
.RI "\fB~ParameterizedTestCaseRegistry\fP ()"
.br
.ti -1c
.RI "template<class \fBTestCase\fP > \fBParameterizedTestCaseInfo\fP< \fBTestCase\fP > * \fBGetTestCasePatternHolder\fP (const char *test_case_name, \fBCodeLocation\fP code_location)"
.br
.ti -1c
.RI "void \fBRegisterTests\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB663\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "testing::internal::ParameterizedTestCaseRegistry::ParameterizedTestCaseRegistry ()\fC [inline]\fP"

.PP
Definición en la línea \fB665\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "testing::internal::ParameterizedTestCaseRegistry::~ParameterizedTestCaseRegistry ()\fC [inline]\fP"

.PP
Definición en la línea \fB666\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<class \fBTestCase\fP > \fBParameterizedTestCaseInfo\fP< \fBTestCase\fP > * testing::internal::ParameterizedTestCaseRegistry::GetTestCasePatternHolder (const char * test_case_name, \fBCodeLocation\fP code_location)\fC [inline]\fP"

.PP
Definición en la línea \fB676\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "void testing::internal::ParameterizedTestCaseRegistry::RegisterTests ()\fC [inline]\fP"

.PP
Definición en la línea \fB706\fP del archivo \fBgtest\-param\-util\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
