.TH "testing::internal::ParamGeneratorInterface< T >" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamGeneratorInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.PP
Inherited by \fBtesting::internal::RangeGenerator< T, IncrementT >\fP, and \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBParamType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ParamGeneratorInterface\fP ()"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< T > * \fBBegin\fP () const =0"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< T > * \fBEnd\fP () const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class testing::internal::ParamGeneratorInterface< T >"
.PP
Definition at line \fB162\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef T \fBtesting::internal::ParamGeneratorInterface\fP< T >::\fBParamType\fP"

.PP
Definition at line \fB164\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > virtual \fBtesting::internal::ParamGeneratorInterface\fP< T >::~\fBParamGeneratorInterface\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB166\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > virtual \fBParamIteratorInterface\fP< T > * \fBtesting::internal::ParamGeneratorInterface\fP< T >::Begin () const\fC [pure virtual]\fP"

.PP
Implemented in \fBtesting::internal::RangeGenerator< T, IncrementT >\fP, and \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP\&.
.SS "template<typename T > virtual \fBParamIteratorInterface\fP< T > * \fBtesting::internal::ParamGeneratorInterface\fP< T >::End () const\fC [pure virtual]\fP"

.PP
Implemented in \fBtesting::internal::RangeGenerator< T, IncrementT >\fP, and \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
