.TH "testing::internal::RE" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::RE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRE\fP (const \fBRE\fP &other)"
.br
.ti -1c
.RI "\fBRE\fP (const ::std::string &regex)"
.br
.ti -1c
.RI "\fBRE\fP (const char *regex)"
.br
.ti -1c
.RI "\fB~RE\fP ()"
.br
.ti -1c
.RI "const char * \fBpattern\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBFullMatch\fP (const ::std::string &str, const \fBRE\fP &re)"
.br
.ti -1c
.RI "static bool \fBPartialMatch\fP (const ::std::string &str, const \fBRE\fP &re)"
.br
.ti -1c
.RI "static bool \fBFullMatch\fP (const char *str, const \fBRE\fP &re)"
.br
.ti -1c
.RI "static bool \fBPartialMatch\fP (const char *str, const \fBRE\fP &re)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1241\fP of file \fBgtest\-port\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::RE::RE (const \fBRE\fP & other)\fC [inline]\fP"

.PP
Definition at line \fB1245\fP of file \fBgtest\-port\&.h\fP\&.
.SS "testing::internal::RE::RE (const ::std::string & regex)\fC [inline]\fP"

.PP
Definition at line \fB1248\fP of file \fBgtest\-port\&.h\fP\&.
.SS "testing::internal::RE::RE (const char * regex)\fC [inline]\fP"

.PP
Definition at line \fB1256\fP of file \fBgtest\-port\&.h\fP\&.
.SS "testing::internal::RE::~RE ()"

.SH "Member Function Documentation"
.PP 
.SS "static bool testing::internal::RE::FullMatch (const ::std::string & str, const \fBRE\fP & re)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1269\fP of file \fBgtest\-port\&.h\fP\&.
.SS "static bool testing::internal::RE::FullMatch (const char * str, const \fBRE\fP & re)\fC [static]\fP"

.SS "static bool testing::internal::RE::PartialMatch (const ::std::string & str, const \fBRE\fP & re)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1272\fP of file \fBgtest\-port\&.h\fP\&.
.SS "static bool testing::internal::RE::PartialMatch (const char * str, const \fBRE\fP & re)\fC [static]\fP"

.SS "const char * testing::internal::RE::pattern () const\fC [inline]\fP"

.PP
Definition at line \fB1260\fP of file \fBgtest\-port\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
