.TH "testing::internal::edit_distance" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::edit_distance
.SH SYNOPSIS
.br
.PP
.SS "Enumeraciones"

.in +1c
.ti -1c
.RI "enum \fBEditType\fP { \fBkMatch\fP, \fBkAdd\fP, \fBkRemove\fP, \fBkReplace\fP }"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "\fBGTEST_API_\fP std::vector< \fBEditType\fP > \fBCalculateOptimalEdits\fP (const std::vector< size_t > &left, const std::vector< size_t > &right)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP std::vector< \fBEditType\fP > \fBCalculateOptimalEdits\fP (const std::vector< std::string > &left, const std::vector< std::string > &right)"
.br
.ti -1c
.RI "\fBGTEST_API_\fP std::string \fBCreateUnifiedDiff\fP (const std::vector< std::string > &left, const std::vector< std::string > &right, size_t context=2)"
.br
.in -1c
.SH "Documentación de las enumeraciones"
.PP 
.SS "enum \fBtesting::internal::edit_distance::EditType\fP"

.PP
\fBValores de enumeraciones\fP
.in +1c
.TP
\fB\fIkMatch \fP\fP
.TP
\fB\fIkAdd \fP\fP
.TP
\fB\fIkRemove \fP\fP
.TP
\fB\fIkReplace \fP\fP
.PP
Definición en la línea \fB168\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de las funciones"
.PP 
.SS "\fBGTEST_API_\fP std::vector< \fBEditType\fP > testing::internal::edit_distance::CalculateOptimalEdits (const std::vector< size_t > & left, const std::vector< size_t > & right)"

.SS "\fBGTEST_API_\fP std::vector< \fBEditType\fP > testing::internal::edit_distance::CalculateOptimalEdits (const std::vector< std::string > & left, const std::vector< std::string > & right)"

.SS "\fBGTEST_API_\fP std::string testing::internal::edit_distance::CreateUnifiedDiff (const std::vector< std::string > & left, const std::vector< std::string > & right, size_t context = \fC2\fP)"

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
