.TH "testing::internal::scoped_ptr< T >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::scoped_ptr< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef T \fBelement_type\fP"
.br
.in -1c
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBscoped_ptr\fP (T *p=NULL)"
.br
.ti -1c
.RI "\fB~scoped_ptr\fP ()"
.br
.ti -1c
.RI "T & \fBoperator*\fP () const"
.br
.ti -1c
.RI "T * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "T * \fBget\fP () const"
.br
.ti -1c
.RI "T * \fBrelease\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP (T *p=NULL)"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "void \fBswap\fP (\fBscoped_ptr\fP &a, \fBscoped_ptr\fP &b)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
class testing::internal::scoped_ptr< T >"
.PP
Definición en la línea \fB1196\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename T > typedef T \fBtesting::internal::scoped_ptr\fP< T >::\fBelement_type\fP"

.PP
Definición en la línea \fB1198\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename T > \fBtesting::internal::scoped_ptr\fP< T >::\fBscoped_ptr\fP (T * p = \fCNULL\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definición en la línea \fB1200\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > \fBtesting::internal::scoped_ptr\fP< T >::~\fBscoped_ptr\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB1201\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename T > T * \fBtesting::internal::scoped_ptr\fP< T >::get () const\fC [inline]\fP"

.PP
Definición en la línea \fB1205\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > T & \fBtesting::internal::scoped_ptr\fP< T >::operator* () const\fC [inline]\fP"

.PP
Definición en la línea \fB1203\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > T * \fBtesting::internal::scoped_ptr\fP< T >::operator\-> () const\fC [inline]\fP"

.PP
Definición en la línea \fB1204\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > T * \fBtesting::internal::scoped_ptr\fP< T >::release ()\fC [inline]\fP"

.PP
Definición en la línea \fB1207\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > void \fBtesting::internal::scoped_ptr\fP< T >::reset (T * p = \fCNULL\fP)\fC [inline]\fP"

.PP
Definición en la línea \fB1213\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación de las funciones relacionadas y clases amigas"
.PP 
.SS "template<typename T > void swap (\fBscoped_ptr\fP< T > & a, \fBscoped_ptr\fP< T > & b)\fC [friend]\fP"

.PP
Definición en la línea \fB1222\fP del archivo \fBgtest\-port\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
