.TH "testing::internal::ValuesInIteratorRangeGenerator< T >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ValuesInIteratorRangeGenerator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.PP
Inherits \fBtesting::internal::ParamGeneratorInterface< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename ForwardIterator > \fBValuesInIteratorRangeGenerator\fP (ForwardIterator begin, ForwardIterator end)"
.br
.ti -1c
.RI "virtual \fB~ValuesInIteratorRangeGenerator\fP ()"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< T > * \fBBegin\fP () const"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< T > * \fBEnd\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class testing::internal::ValuesInIteratorRangeGenerator< T >"
.PP
Definition at line \fB288\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > template<typename ForwardIterator > \fBtesting::internal::ValuesInIteratorRangeGenerator\fP< T >::\fBValuesInIteratorRangeGenerator\fP (ForwardIterator begin, ForwardIterator end)\fC [inline]\fP"

.PP
Definition at line \fB291\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > virtual \fBtesting::internal::ValuesInIteratorRangeGenerator\fP< T >::~\fBValuesInIteratorRangeGenerator\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB293\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > virtual \fBParamIteratorInterface\fP< T > * \fBtesting::internal::ValuesInIteratorRangeGenerator\fP< T >::Begin () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::internal::ParamGeneratorInterface< T >\fP\&.
.PP
Definition at line \fB295\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > virtual \fBParamIteratorInterface\fP< T > * \fBtesting::internal::ValuesInIteratorRangeGenerator\fP< T >::End () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::internal::ParamGeneratorInterface< T >\fP\&.
.PP
Definition at line \fB298\fP of file \fBgtest\-param\-util\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
