.TH "testing::internal::IsHashTable< T >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IsHashTable< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP = sizeof(test<T>(0, 0)) == sizeof(int)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
struct testing::internal::IsHashTable< T >"
.PP
Definición en la línea \fB973\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<typename T > const bool \fBtesting::internal::IsHashTable\fP< T >::value = sizeof(test<T>(0, 0)) == sizeof(int)\fC [static]\fP"

.PP
Definición en la línea \fB983\fP del archivo \fBgtest\-internal\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
