.TH "testing::internal::AssertHelper" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::AssertHelper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBAssertHelper\fP (\fBTestPartResult::Type\fP type, const char *file, int line, const char *message)"
.br
.ti -1c
.RI "\fB~AssertHelper\fP ()"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBMessage\fP &message) const"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB1719\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "testing::internal::AssertHelper::AssertHelper (\fBTestPartResult::Type\fP type, const char * file, int line, const char * message)"

.SS "testing::internal::AssertHelper::~AssertHelper ()"

.SH "Documentación de las funciones miembro"
.PP 
.SS "void testing::internal::AssertHelper::operator= (const \fBMessage\fP & message) const"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
