.TH "testing::internal::GTestLog" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::GTestLog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGTestLog\fP (\fBGTestLogSeverity\fP severity, const char *file, int line)"
.br
.ti -1c
.RI "\fB~GTestLog\fP ()"
.br
.ti -1c
.RI "::std::ostream & \fBGetStream\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1341\fP of file \fBgtest\-port\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::GTestLog::GTestLog (\fBGTestLogSeverity\fP severity, const char * file, int line)"

.SS "testing::internal::GTestLog::~GTestLog ()"

.SH "Member Function Documentation"
.PP 
.SS "::std::ostream & testing::internal::GTestLog::GetStream ()\fC [inline]\fP"

.PP
Definition at line \fB1348\fP of file \fBgtest\-port\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
