.TH "testing::internal::IsSame< T, T >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IsSame< T, T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "enum { \fBvalue\fP = true }"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
struct testing::internal::IsSame< T, T >"
.PP
Definición en la línea \fB1168\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación de las enumeraciones miembro de la clase"
.PP 
.SS "template<typename T > anonymous enum"

.PP
\fBValores de enumeraciones\fP
.in +1c
.TP
\fB\fIvalue \fP\fP
.PP
Definición en la línea \fB1169\fP del archivo \fBgtest\-port\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
