.TH "testing::TestParamInfo< ParamType >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestParamInfo< ParamType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestParamInfo\fP (const ParamType &a_param, size_t an_index)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ParamType \fBparam\fP"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ParamType>
.br
struct testing::TestParamInfo< ParamType >"
.PP
Definition at line \fB55\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ParamType > \fBtesting::TestParamInfo\fP< ParamType >::\fBTestParamInfo\fP (const ParamType & a_param, size_t an_index)\fC [inline]\fP"

.PP
Definition at line \fB56\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class ParamType > size_t \fBtesting::TestParamInfo\fP< ParamType >::index"

.PP
Definition at line \fB60\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SS "template<class ParamType > ParamType \fBtesting::TestParamInfo\fP< ParamType >::param"

.PP
Definition at line \fB59\fP of file \fBgtest\-param\-util\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
