.TH "testing::internal::TypeWithSize< 4 >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TypeWithSize< 4 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef int \fBInt\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBUInt\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB2617\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "typedef int \fBtesting::internal::TypeWithSize\fP< 4 >::\fBInt\fP"

.PP
Definición en la línea \fB2623\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "typedef unsigned int \fBtesting::internal::TypeWithSize\fP< 4 >::\fBUInt\fP"

.PP
Definición en la línea \fB2624\fP del archivo \fBgtest\-port\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
