.TH "testing::internal::IteratorTraits< Iterator >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IteratorTraits< Iterator >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef Iterator::value_type \fBvalue_type\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename Iterator>
.br
struct testing::internal::IteratorTraits< Iterator >"
.PP
Definición en la línea \fB2365\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename Iterator > typedef Iterator::value_type \fBtesting::internal::IteratorTraits\fP< Iterator >::\fBvalue_type\fP"

.PP
Definición en la línea \fB2366\fP del archivo \fBgtest\-port\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
