.TH "testing::internal::WrapPrinterType< type >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::WrapPrinterType< type >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-printers\&.h>\fP
.SH "Descripción detallada"
.PP 

.SS "template<\fBDefaultPrinterType\fP type>
.br
struct testing::internal::WrapPrinterType< type >"
.PP
Definición en la línea \fB411\fP del archivo \fBgtest\-printers\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
