.TH "testing::internal::FormatForComparison< ToPrint, OtherOperand >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::FormatForComparison< ToPrint, OtherOperand >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-printers\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "::std::string \fBFormat\fP (const ToPrint &value)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename ToPrint, typename OtherOperand>
.br
class testing::internal::FormatForComparison< ToPrint, OtherOperand >"
.PP
Definition at line \fB311\fP of file \fBgtest\-printers\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename ToPrint , typename OtherOperand > ::std::string \fBtesting::internal::FormatForComparison\fP< ToPrint, OtherOperand >::Format (const ToPrint & value)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB313\fP of file \fBgtest\-printers\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
