.TH "testing::internal::ParamIterator< T >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamIterator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef const T & \fBreference\fP"
.br
.ti -1c
.RI "typedef ptrdiff_t \fBdifference_type\fP"
.br
.in -1c
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBParamIterator\fP (const \fBParamIterator\fP &other)"
.br
.ti -1c
.RI "\fBParamIterator\fP & \fBoperator=\fP (const \fBParamIterator\fP &other)"
.br
.ti -1c
.RI "const T & \fBoperator*\fP () const"
.br
.ti -1c
.RI "const T * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "\fBParamIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBParamIterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBParamIterator\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBParamIterator\fP &other) const"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "class \fBParamGenerator< T >\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
class testing::internal::ParamIterator< T >"
.PP
Definición en la línea \fB119\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename T > typedef ptrdiff_t \fBtesting::internal::ParamIterator\fP< T >::\fBdifference_type\fP"

.PP
Definición en la línea \fB123\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > typedef const T& \fBtesting::internal::ParamIterator\fP< T >::\fBreference\fP"

.PP
Definición en la línea \fB122\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > typedef T \fBtesting::internal::ParamIterator\fP< T >::\fBvalue_type\fP"

.PP
Definición en la línea \fB121\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename T > \fBtesting::internal::ParamIterator\fP< T >::\fBParamIterator\fP (const \fBParamIterator\fP< T > & other)\fC [inline]\fP"

.PP
Definición en la línea \fB126\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename T > bool \fBtesting::internal::ParamIterator\fP< T >::operator!= (const \fBParamIterator\fP< T > & other) const\fC [inline]\fP"

.PP
Definición en la línea \fB149\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > const T & \fBtesting::internal::ParamIterator\fP< T >::operator* () const\fC [inline]\fP"

.PP
Definición en la línea \fB133\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > \fBParamIterator\fP & \fBtesting::internal::ParamIterator\fP< T >::operator++ ()\fC [inline]\fP"

.PP
Definición en la línea \fB136\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > \fBParamIterator\fP \fBtesting::internal::ParamIterator\fP< T >::operator++ (int)\fC [inline]\fP"

.PP
Definición en la línea \fB141\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > const T * \fBtesting::internal::ParamIterator\fP< T >::operator\-> () const\fC [inline]\fP"

.PP
Definición en la línea \fB134\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > \fBParamIterator\fP & \fBtesting::internal::ParamIterator\fP< T >::operator= (const \fBParamIterator\fP< T > & other)\fC [inline]\fP"

.PP
Definición en la línea \fB127\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > bool \fBtesting::internal::ParamIterator\fP< T >::operator== (const \fBParamIterator\fP< T > & other) const\fC [inline]\fP"

.PP
Definición en la línea \fB146\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de las funciones relacionadas y clases amigas"
.PP 
.SS "template<typename T > friend class \fBParamGenerator\fP< T >\fC [friend]\fP"

.PP
Definición en la línea \fB149\fP del archivo \fBgtest\-param\-util\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
