.TH "testing::internal::ConstCharPtr" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ConstCharPtr
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBConstCharPtr\fP (const char *str)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "const char * \fBvalue\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB777\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "testing::internal::ConstCharPtr::ConstCharPtr (const char * str)\fC [inline]\fP"

.PP
Definición en la línea \fB778\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "testing::internal::ConstCharPtr::operator bool () const\fC [inline]\fP"

.PP
Definición en la línea \fB779\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "const char* testing::internal::ConstCharPtr::value"

.PP
Definición en la línea \fB780\fP del archivo \fBgtest\-internal\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
