.TH "testing::internal::ThreadLocal< T >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ThreadLocal< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBThreadLocal\fP ()"
.br
.ti -1c
.RI "\fBThreadLocal\fP (const T &value)"
.br
.ti -1c
.RI "T * \fBpointer\fP ()"
.br
.ti -1c
.RI "const T * \fBpointer\fP () const"
.br
.ti -1c
.RI "const T & \fBget\fP () const"
.br
.ti -1c
.RI "void \fBset\fP (const T &value)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
class testing::internal::ThreadLocal< T >"
.PP
Definición en la línea \fB2300\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename T > \fBtesting::internal::ThreadLocal\fP< T >::\fBThreadLocal\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB2302\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > \fBtesting::internal::ThreadLocal\fP< T >::\fBThreadLocal\fP (const T & value)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definición en la línea \fB2303\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename T > const T & \fBtesting::internal::ThreadLocal\fP< T >::get () const\fC [inline]\fP"

.PP
Definición en la línea \fB2306\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > T * \fBtesting::internal::ThreadLocal\fP< T >::pointer ()\fC [inline]\fP"

.PP
Definición en la línea \fB2304\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > const T * \fBtesting::internal::ThreadLocal\fP< T >::pointer () const\fC [inline]\fP"

.PP
Definición en la línea \fB2305\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > void \fBtesting::internal::ThreadLocal\fP< T >::set (const T & value)\fC [inline]\fP"

.PP
Definición en la línea \fB2307\fP del archivo \fBgtest\-port\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
