.TH "testing::internal::ImplicitlyConvertible< From, To >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ImplicitlyConvertible< From, To >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename From, typename To>
.br
class testing::internal::ImplicitlyConvertible< From, To >"
.PP
Definition at line \fB866\fP of file \fBgtest\-internal\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename From , typename To > const bool \fBtesting::internal::ImplicitlyConvertible\fP< From, To >::value\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
      sizeof(Helper(ImplicitlyConvertible::MakeFrom())) == 1
.fi
.PP
Definition at line \fB902\fP of file \fBgtest\-internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
