.TH "testing::TestEventListener" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestEventListener
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.PP
Heredado por \fBtesting::EmptyTestEventListener\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "virtual \fB~TestEventListener\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnTestProgramStart\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestIterationStart\fP (const \fBUnitTest\fP &unit_test, int iteration)=0"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsSetUpStart\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsSetUpEnd\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestCaseStart\fP (const \fBTestCase\fP &test_case)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestStart\fP (const \fBTestInfo\fP &test_info)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestPartResult\fP (const TestPartResult &test_part_result)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestEnd\fP (const \fBTestInfo\fP &test_info)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestCaseEnd\fP (const \fBTestCase\fP &test_case)=0"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsTearDownStart\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.ti -1c
.RI "virtual void \fBOnEnvironmentsTearDownEnd\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestIterationEnd\fP (const \fBUnitTest\fP &unit_test, int iteration)=0"
.br
.ti -1c
.RI "virtual void \fBOnTestProgramEnd\fP (const \fBUnitTest\fP &unit_test)=0"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB1044\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "virtual testing::TestEventListener::~TestEventListener ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definición en la línea \fB1046\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "virtual void testing::TestEventListener::OnEnvironmentsSetUpEnd (const \fBUnitTest\fP & unit_test)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnEnvironmentsSetUpStart (const \fBUnitTest\fP & unit_test)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnEnvironmentsTearDownEnd (const \fBUnitTest\fP & unit_test)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnEnvironmentsTearDownStart (const \fBUnitTest\fP & unit_test)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnTestCaseEnd (const \fBTestCase\fP & test_case)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnTestCaseStart (const \fBTestCase\fP & test_case)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnTestEnd (const \fBTestInfo\fP & test_info)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnTestIterationEnd (const \fBUnitTest\fP & unit_test, int iteration)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnTestIterationStart (const \fBUnitTest\fP & unit_test, int iteration)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnTestPartResult (const TestPartResult & test_part_result)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnTestProgramEnd (const \fBUnitTest\fP & unit_test)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnTestProgramStart (const \fBUnitTest\fP & unit_test)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.
.SS "virtual void testing::TestEventListener::OnTestStart (const \fBTestInfo\fP & test_info)\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::EmptyTestEventListener\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
