.TH "testing::internal::ParamNameGenFunc< ParamType >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamNameGenFunc< ParamType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef std::string \fBType\fP(const \fBTestParamInfo\fP< ParamType > &)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<class ParamType>
.br
struct testing::internal::ParamNameGenFunc< ParamType >"
.PP
Definición en la línea \fB390\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<class ParamType > typedef std::string \fBtesting::internal::ParamNameGenFunc\fP< ParamType >::\fBType\fP(const \fBTestParamInfo\fP< ParamType > &)"

.PP
Definición en la línea \fB391\fP del archivo \fBgtest\-param\-util\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
