.TH "testing::internal::Mutex" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::Mutex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutex\fP ()"
.br
.ti -1c
.RI "void \fBLock\fP ()"
.br
.ti -1c
.RI "void \fBUnlock\fP ()"
.br
.ti -1c
.RI "void \fBAssertHeld\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2274\fP of file \fBgtest\-port\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::Mutex::Mutex ()\fC [inline]\fP"

.PP
Definition at line \fB2276\fP of file \fBgtest\-port\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void testing::internal::Mutex::AssertHeld () const\fC [inline]\fP"

.PP
Definition at line \fB2279\fP of file \fBgtest\-port\&.h\fP\&.
.SS "void testing::internal::Mutex::Lock ()\fC [inline]\fP"

.PP
Definition at line \fB2277\fP of file \fBgtest\-port\&.h\fP\&.
.SS "void testing::internal::Mutex::Unlock ()\fC [inline]\fP"

.PP
Definition at line \fB2278\fP of file \fBgtest\-port\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
