.TH "testing::internal::RE" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::RE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBRE\fP (const \fBRE\fP &other)"
.br
.ti -1c
.RI "\fBRE\fP (const ::std::string &regex)"
.br
.ti -1c
.RI "\fBRE\fP (const char *regex)"
.br
.ti -1c
.RI "\fB~RE\fP ()"
.br
.ti -1c
.RI "const char * \fBpattern\fP () const"
.br
.in -1c
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static bool \fBFullMatch\fP (const ::std::string &str, const \fBRE\fP &re)"
.br
.ti -1c
.RI "static bool \fBPartialMatch\fP (const ::std::string &str, const \fBRE\fP &re)"
.br
.ti -1c
.RI "static bool \fBFullMatch\fP (const char *str, const \fBRE\fP &re)"
.br
.ti -1c
.RI "static bool \fBPartialMatch\fP (const char *str, const \fBRE\fP &re)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB1241\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "testing::internal::RE::RE (const \fBRE\fP & other)\fC [inline]\fP"

.PP
Definición en la línea \fB1245\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "testing::internal::RE::RE (const ::std::string & regex)\fC [inline]\fP"

.PP
Definición en la línea \fB1248\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "testing::internal::RE::RE (const char * regex)\fC [inline]\fP"

.PP
Definición en la línea \fB1256\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "testing::internal::RE::~RE ()"

.SH "Documentación de las funciones miembro"
.PP 
.SS "static bool testing::internal::RE::FullMatch (const ::std::string & str, const \fBRE\fP & re)\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB1269\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "static bool testing::internal::RE::FullMatch (const char * str, const \fBRE\fP & re)\fC [static]\fP"

.SS "static bool testing::internal::RE::PartialMatch (const ::std::string & str, const \fBRE\fP & re)\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB1272\fP del archivo \fBgtest\-port\&.h\fP\&.
.SS "static bool testing::internal::RE::PartialMatch (const char * str, const \fBRE\fP & re)\fC [static]\fP"

.SS "const char * testing::internal::RE::pattern () const\fC [inline]\fP"

.PP
Definición en la línea \fB1260\fP del archivo \fBgtest\-port\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
