.TH "testing::internal::FloatingPoint< RawType >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::FloatingPoint< RawType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef \fBTypeWithSize\fP< sizeof(RawType)>::UInt \fBBits\fP"
.br
.in -1c
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBFloatingPoint\fP (const RawType &x)"
.br
.ti -1c
.RI "const \fBBits\fP & \fBbits\fP () const"
.br
.ti -1c
.RI "\fBBits\fP \fBexponent_bits\fP () const"
.br
.ti -1c
.RI "\fBBits\fP \fBfraction_bits\fP () const"
.br
.ti -1c
.RI "\fBBits\fP \fBsign_bit\fP () const"
.br
.ti -1c
.RI "bool \fBis_nan\fP () const"
.br
.ti -1c
.RI "bool \fBAlmostEquals\fP (const \fBFloatingPoint\fP &rhs) const"
.br
.ti -1c
.RI "float \fBMax\fP ()"
.br
.ti -1c
.RI "double \fBMax\fP ()"
.br
.in -1c
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static RawType \fBReinterpretBits\fP (const \fBBits\fP \fBbits\fP)"
.br
.ti -1c
.RI "static RawType \fBInfinity\fP ()"
.br
.ti -1c
.RI "static RawType \fBMax\fP ()"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static const size_t \fBkBitCount\fP = 8*sizeof(RawType)"
.br
.ti -1c
.RI "static const size_t \fBkFractionBitCount\fP"
.br
.ti -1c
.RI "static const size_t \fBkExponentBitCount\fP = \fBkBitCount\fP \- 1 \- \fBkFractionBitCount\fP"
.br
.ti -1c
.RI "static const \fBBits\fP \fBkSignBitMask\fP = static_cast<\fBBits\fP>(1) << (\fBkBitCount\fP \- 1)"
.br
.ti -1c
.RI "static const \fBBits\fP \fBkFractionBitMask\fP"
.br
.ti -1c
.RI "static const \fBBits\fP \fBkExponentBitMask\fP = ~(\fBkSignBitMask\fP | \fBkFractionBitMask\fP)"
.br
.ti -1c
.RI "static const size_t \fBkMaxUlps\fP = 4"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename RawType>
.br
class testing::internal::FloatingPoint< RawType >"
.PP
Definición en la línea \fB250\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename RawType > typedef \fBTypeWithSize\fP<sizeof(RawType)>::UInt \fBtesting::internal::FloatingPoint\fP< RawType >::\fBBits\fP"

.PP
Definición en la línea \fB254\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename RawType > \fBtesting::internal::FloatingPoint\fP< RawType >::\fBFloatingPoint\fP (const RawType & x)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definición en la línea \fB298\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename RawType > bool \fBtesting::internal::FloatingPoint\fP< RawType >::AlmostEquals (const \fBFloatingPoint\fP< RawType > & rhs) const\fC [inline]\fP"

.PP
Definición en la línea \fB346\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > const \fBBits\fP & \fBtesting::internal::FloatingPoint\fP< RawType >::bits () const\fC [inline]\fP"

.PP
Definición en la línea \fB322\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > \fBBits\fP \fBtesting::internal::FloatingPoint\fP< RawType >::exponent_bits () const\fC [inline]\fP"

.PP
Definición en la línea \fB325\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > \fBBits\fP \fBtesting::internal::FloatingPoint\fP< RawType >::fraction_bits () const\fC [inline]\fP"

.PP
Definición en la línea \fB328\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > static RawType \fBtesting::internal::FloatingPoint\fP< RawType >::Infinity ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB312\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > bool \fBtesting::internal::FloatingPoint\fP< RawType >::is_nan () const\fC [inline]\fP"

.PP
Definición en la línea \fB334\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > static RawType \fBtesting::internal::FloatingPoint\fP< RawType >::Max ()\fC [static]\fP"

.SS "float \fBtesting::internal::FloatingPoint\fP< float >::Max ()\fC [inline]\fP"

.PP
Definición en la línea \fB402\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "double \fBtesting::internal::FloatingPoint\fP< double >::Max ()\fC [inline]\fP"

.PP
Definición en la línea \fB404\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > static RawType \fBtesting::internal::FloatingPoint\fP< RawType >::ReinterpretBits (const \fBBits\fP bits)\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB305\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > \fBBits\fP \fBtesting::internal::FloatingPoint\fP< RawType >::sign_bit () const\fC [inline]\fP"

.PP
Definición en la línea \fB331\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<typename RawType > const size_t \fBtesting::internal::FloatingPoint\fP< RawType >::kBitCount = 8*sizeof(RawType)\fC [static]\fP"

.PP
Definición en la línea \fB259\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > const size_t \fBtesting::internal::FloatingPoint\fP< RawType >::kExponentBitCount = \fBkBitCount\fP \- 1 \- \fBkFractionBitCount\fP\fC [static]\fP"

.PP
Definición en la línea \fB266\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > const \fBBits\fP \fBtesting::internal::FloatingPoint\fP< RawType >::kExponentBitMask = ~(\fBkSignBitMask\fP | \fBkFractionBitMask\fP)\fC [static]\fP"

.PP
Definición en la línea \fB276\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > const size_t \fBtesting::internal::FloatingPoint\fP< RawType >::kFractionBitCount\fC [static]\fP"
\fBValor inicial:\fP
.PP
.nf
=
    std::numeric_limits<RawType>::digits - 1
.fi
.PP
Definición en la línea \fB262\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > const \fBBits\fP \fBtesting::internal::FloatingPoint\fP< RawType >::kFractionBitMask\fC [static]\fP"
\fBValor inicial:\fP
.PP
.nf
=
    ~static_cast<Bits>(0) >> (kExponentBitCount + 1)
.fi
.PP
Definición en la línea \fB272\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > const size_t \fBtesting::internal::FloatingPoint\fP< RawType >::kMaxUlps = 4\fC [static]\fP"

.PP
Definición en la línea \fB290\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename RawType > const \fBBits\fP \fBtesting::internal::FloatingPoint\fP< RawType >::kSignBitMask = static_cast<\fBBits\fP>(1) << (\fBkBitCount\fP \- 1)\fC [static]\fP"

.PP
Definición en la línea \fB269\fP del archivo \fBgtest\-internal\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
