.TH "testing::internal::CodeLocation" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::CodeLocation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCodeLocation\fP (const std::string &a_file, int a_line)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfile\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB492\fP of file \fBgtest\-internal\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::CodeLocation::CodeLocation (const std::string & a_file, int a_line)\fC [inline]\fP"

.PP
Definition at line \fB493\fP of file \fBgtest\-internal\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string testing::internal::CodeLocation::file"

.PP
Definition at line \fB496\fP of file \fBgtest\-internal\&.h\fP\&.
.SS "int testing::internal::CodeLocation::line"

.PP
Definition at line \fB497\fP of file \fBgtest\-internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
