.TH "testing::Test" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::Test
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.PP
Heredado por \fBtesting::TestWithParam< T >\fP\&.
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef internal::SetUpTestCaseFunc \fBSetUpTestCaseFunc\fP"
.br
.ti -1c
.RI "typedef internal::TearDownTestCaseFunc \fBTearDownTestCaseFunc\fP"
.br
.in -1c
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "virtual \fB~Test\fP ()"
.br
.in -1c
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static void \fBSetUpTestCase\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestCase\fP ()"
.br
.ti -1c
.RI "static bool \fBHasFatalFailure\fP ()"
.br
.ti -1c
.RI "static bool \fBHasNonfatalFailure\fP ()"
.br
.ti -1c
.RI "static bool \fBHasFailure\fP ()"
.br
.ti -1c
.RI "static void \fBRecordProperty\fP (const std::string &key, const std::string &value)"
.br
.ti -1c
.RI "static void \fBRecordProperty\fP (const std::string &key, int value)"
.br
.in -1c
.SS "Métodos protegidos"

.in +1c
.ti -1c
.RI "\fBTest\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "class \fBTestInfo\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB409\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "typedef internal::SetUpTestCaseFunc \fBtesting::Test::SetUpTestCaseFunc\fP"

.PP
Definición en la línea \fB415\fP del archivo \fBgtest\&.h\fP\&.
.SS "typedef internal::TearDownTestCaseFunc \fBtesting::Test::TearDownTestCaseFunc\fP"

.PP
Definición en la línea \fB416\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "virtual testing::Test::~Test ()\fC [virtual]\fP"

.SS "testing::Test::Test ()\fC [protected]\fP"

.SH "Documentación de las funciones miembro"
.PP 
.SS "static bool testing::Test::HasFailure ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB445\fP del archivo \fBgtest\&.h\fP\&.
.SS "static bool testing::Test::HasFatalFailure ()\fC [static]\fP"

.SS "static bool testing::Test::HasNonfatalFailure ()\fC [static]\fP"

.SS "static void testing::Test::RecordProperty (const std::string & key, const std::string & value)\fC [static]\fP"

.SS "static void testing::Test::RecordProperty (const std::string & key, int value)\fC [static]\fP"

.SS "virtual void testing::Test::SetUp ()\fC [protected]\fP, \fC [virtual]\fP"

.SS "static void testing::Test::SetUpTestCase ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB427\fP del archivo \fBgtest\&.h\fP\&.
.SS "virtual void testing::Test::TearDown ()\fC [protected]\fP, \fC [virtual]\fP"

.SS "static void testing::Test::TearDownTestCase ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB435\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación de las funciones relacionadas y clases amigas"
.PP 
.SS "friend class \fBTestInfo\fP\fC [friend]\fP"

.PP
Definición en la línea \fB411\fP del archivo \fBgtest\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
