.TH "testing::TestProperty" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestProperty
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBTestProperty\fP (const std::string &a_key, const std::string &a_value)"
.br
.ti -1c
.RI "const char * \fBkey\fP () const"
.br
.ti -1c
.RI "const char * \fBvalue\fP () const"
.br
.ti -1c
.RI "void \fBSetValue\fP (const std::string &new_value)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB524\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "testing::TestProperty::TestProperty (const std::string & a_key, const std::string & a_value)\fC [inline]\fP"

.PP
Definición en la línea \fB529\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "const char * testing::TestProperty::key () const\fC [inline]\fP"

.PP
Definición en la línea \fB534\fP del archivo \fBgtest\&.h\fP\&.
.SS "void testing::TestProperty::SetValue (const std::string & new_value)\fC [inline]\fP"

.PP
Definición en la línea \fB544\fP del archivo \fBgtest\&.h\fP\&.
.SS "const char * testing::TestProperty::value () const\fC [inline]\fP"

.PP
Definición en la línea \fB539\fP del archivo \fBgtest\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
