.TH "testing::internal::CodeLocation" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::CodeLocation
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBCodeLocation\fP (const std::string &a_file, int a_line)"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "std::string \fBfile\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB492\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "testing::internal::CodeLocation::CodeLocation (const std::string & a_file, int a_line)\fC [inline]\fP"

.PP
Definición en la línea \fB493\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "std::string testing::internal::CodeLocation::file"

.PP
Definición en la línea \fB496\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "int testing::internal::CodeLocation::line"

.PP
Definición en la línea \fB497\fP del archivo \fBgtest\-internal\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
