.TH "testing::internal::ParameterizedTestCaseRegistry" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParameterizedTestCaseRegistry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterizedTestCaseRegistry\fP ()"
.br
.ti -1c
.RI "\fB~ParameterizedTestCaseRegistry\fP ()"
.br
.ti -1c
.RI "template<class \fBTestCase\fP > \fBParameterizedTestCaseInfo\fP< \fBTestCase\fP > * \fBGetTestCasePatternHolder\fP (const char *test_case_name, \fBCodeLocation\fP code_location)"
.br
.ti -1c
.RI "void \fBRegisterTests\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB663\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::internal::ParameterizedTestCaseRegistry::ParameterizedTestCaseRegistry ()\fC [inline]\fP"

.PP
Definition at line \fB665\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SS "testing::internal::ParameterizedTestCaseRegistry::~ParameterizedTestCaseRegistry ()\fC [inline]\fP"

.PP
Definition at line \fB666\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class \fBTestCase\fP > \fBParameterizedTestCaseInfo\fP< \fBTestCase\fP > * testing::internal::ParameterizedTestCaseRegistry::GetTestCasePatternHolder (const char * test_case_name, \fBCodeLocation\fP code_location)\fC [inline]\fP"

.PP
Definition at line \fB676\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SS "void testing::internal::ParameterizedTestCaseRegistry::RegisterTests ()\fC [inline]\fP"

.PP
Definition at line \fB706\fP of file \fBgtest\-param\-util\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
