.TH "testing::PrintToStringParamName" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::PrintToStringParamName
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "template<class ParamType > std::string \fBoperator()\fP (const \fBTestParamInfo\fP< ParamType > &info) const"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB65\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<class ParamType > std::string testing::PrintToStringParamName::operator() (const \fBTestParamInfo\fP< ParamType > & info) const\fC [inline]\fP"

.PP
Definición en la línea \fB67\fP del archivo \fBgtest\-param\-util\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
