.TH "testing::internal::ParamGenerator< T >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamGenerator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef \fBParamIterator\fP< T > \fBiterator\fP"
.br
.in -1c
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBParamGenerator\fP (\fBParamGeneratorInterface\fP< T > *impl)"
.br
.ti -1c
.RI "\fBParamGenerator\fP (const \fBParamGenerator\fP &other)"
.br
.ti -1c
.RI "\fBParamGenerator\fP & \fBoperator=\fP (const \fBParamGenerator\fP &other)"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP () const"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
class testing::internal::ParamGenerator< T >"
.PP
Definición en la línea \fB179\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename T > typedef \fBParamIterator\fP<T> \fBtesting::internal::ParamGenerator\fP< T >::\fBiterator\fP"

.PP
Definición en la línea \fB181\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename T > \fBtesting::internal::ParamGenerator\fP< T >::\fBParamGenerator\fP (\fBParamGeneratorInterface\fP< T > * impl)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definición en la línea \fB183\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > \fBtesting::internal::ParamGenerator\fP< T >::\fBParamGenerator\fP (const \fBParamGenerator\fP< T > & other)\fC [inline]\fP"

.PP
Definición en la línea \fB184\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename T > \fBiterator\fP \fBtesting::internal::ParamGenerator\fP< T >::begin () const\fC [inline]\fP"

.PP
Definición en la línea \fB191\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > \fBiterator\fP \fBtesting::internal::ParamGenerator\fP< T >::end () const\fC [inline]\fP"

.PP
Definición en la línea \fB192\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > \fBParamGenerator\fP & \fBtesting::internal::ParamGenerator\fP< T >::operator= (const \fBParamGenerator\fP< T > & other)\fC [inline]\fP"

.PP
Definición en la línea \fB186\fP del archivo \fBgtest\-param\-util\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
