.TH "testing::TestParamInfo< ParamType >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestParamInfo< ParamType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBTestParamInfo\fP (const ParamType &a_param, size_t an_index)"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "ParamType \fBparam\fP"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<class ParamType>
.br
struct testing::TestParamInfo< ParamType >"
.PP
Definición en la línea \fB55\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<class ParamType > \fBtesting::TestParamInfo\fP< ParamType >::\fBTestParamInfo\fP (const ParamType & a_param, size_t an_index)\fC [inline]\fP"

.PP
Definición en la línea \fB56\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<class ParamType > size_t \fBtesting::TestParamInfo\fP< ParamType >::index"

.PP
Definición en la línea \fB60\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<class ParamType > ParamType \fBtesting::TestParamInfo\fP< ParamType >::param"

.PP
Definición en la línea \fB59\fP del archivo \fBgtest\-param\-util\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
