.TH "testing::internal::ValuesInIteratorRangeGenerator< T >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ValuesInIteratorRangeGenerator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.PP
Herencias \fBtesting::internal::ParamGeneratorInterface< T >\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "template<typename ForwardIterator > \fBValuesInIteratorRangeGenerator\fP (ForwardIterator begin, ForwardIterator end)"
.br
.ti -1c
.RI "virtual \fB~ValuesInIteratorRangeGenerator\fP ()"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< T > * \fBBegin\fP () const"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< T > * \fBEnd\fP () const"
.br
.in -1c
.SS "Otros miembros heredados"
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
class testing::internal::ValuesInIteratorRangeGenerator< T >"
.PP
Definición en la línea \fB288\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename T > template<typename ForwardIterator > \fBtesting::internal::ValuesInIteratorRangeGenerator\fP< T >::\fBValuesInIteratorRangeGenerator\fP (ForwardIterator begin, ForwardIterator end)\fC [inline]\fP"

.PP
Definición en la línea \fB291\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > virtual \fBtesting::internal::ValuesInIteratorRangeGenerator\fP< T >::~\fBValuesInIteratorRangeGenerator\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definición en la línea \fB293\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename T > virtual \fBParamIteratorInterface\fP< T > * \fBtesting::internal::ValuesInIteratorRangeGenerator\fP< T >::Begin () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implementa \fBtesting::internal::ParamGeneratorInterface< T >\fP\&.
.PP
Definición en la línea \fB295\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > virtual \fBParamIteratorInterface\fP< T > * \fBtesting::internal::ValuesInIteratorRangeGenerator\fP< T >::End () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implementa \fBtesting::internal::ParamGeneratorInterface< T >\fP\&.
.PP
Definición en la línea \fB298\fP del archivo \fBgtest\-param\-util\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
