.TH "testing::internal::VoidT< T >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::VoidT< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBvalue_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct testing::internal::VoidT< T >"
.PP
Definition at line \fB990\fP of file \fBgtest\-internal\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef void \fBtesting::internal::VoidT\fP< T >::\fBvalue_type\fP"

.PP
Definition at line \fB991\fP of file \fBgtest\-internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
