.TH "testing::internal::IsRecursiveContainer< C >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IsRecursiveContainer< C >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.PP
Inherits IsRecursiveContainerImpl::type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename C>
.br
struct testing::internal::IsRecursiveContainer< C >"
.PP
Definition at line \fB1033\fP of file \fBgtest\-internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
