.TH "testing::TestProperty" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestProperty
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestProperty\fP (const std::string &a_key, const std::string &a_value)"
.br
.ti -1c
.RI "const char * \fBkey\fP () const"
.br
.ti -1c
.RI "const char * \fBvalue\fP () const"
.br
.ti -1c
.RI "void \fBSetValue\fP (const std::string &new_value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB524\fP of file \fBgtest\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "testing::TestProperty::TestProperty (const std::string & a_key, const std::string & a_value)\fC [inline]\fP"

.PP
Definition at line \fB529\fP of file \fBgtest\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const char * testing::TestProperty::key () const\fC [inline]\fP"

.PP
Definition at line \fB534\fP of file \fBgtest\&.h\fP\&.
.SS "void testing::TestProperty::SetValue (const std::string & new_value)\fC [inline]\fP"

.PP
Definition at line \fB544\fP of file \fBgtest\&.h\fP\&.
.SS "const char * testing::TestProperty::value () const\fC [inline]\fP"

.PP
Definition at line \fB539\fP of file \fBgtest\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
