.TH "testing::TestEventListeners" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::TestEventListeners
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBTestEventListeners\fP ()"
.br
.ti -1c
.RI "\fB~TestEventListeners\fP ()"
.br
.ti -1c
.RI "void \fBAppend\fP (\fBTestEventListener\fP *listener)"
.br
.ti -1c
.RI "\fBTestEventListener\fP * \fBRelease\fP (\fBTestEventListener\fP *listener)"
.br
.ti -1c
.RI "\fBTestEventListener\fP * \fBdefault_result_printer\fP () const"
.br
.ti -1c
.RI "\fBTestEventListener\fP * \fBdefault_xml_generator\fP () const"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "class \fBTestCase\fP"
.br
.ti -1c
.RI "class \fBTestInfo\fP"
.br
.ti -1c
.RI "class \fBinternal::DefaultGlobalTestPartResultReporter\fP"
.br
.ti -1c
.RI "class \fBinternal::NoExecDeathTest\fP"
.br
.ti -1c
.RI "class \fBinternal::TestEventListenersAccessor\fP"
.br
.ti -1c
.RI "class \fBinternal::UnitTestImpl\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB1119\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "testing::TestEventListeners::TestEventListeners ()"

.SS "testing::TestEventListeners::~TestEventListeners ()"

.SH "Documentación de las funciones miembro"
.PP 
.SS "void testing::TestEventListeners::Append (\fBTestEventListener\fP * listener)"

.SS "\fBTestEventListener\fP * testing::TestEventListeners::default_result_printer () const\fC [inline]\fP"

.PP
Definición en la línea \fB1139\fP del archivo \fBgtest\&.h\fP\&.
.SS "\fBTestEventListener\fP * testing::TestEventListeners::default_xml_generator () const\fC [inline]\fP"

.PP
Definición en la línea \fB1150\fP del archivo \fBgtest\&.h\fP\&.
.SS "\fBTestEventListener\fP * testing::TestEventListeners::Release (\fBTestEventListener\fP * listener)"

.SH "Documentación de las funciones relacionadas y clases amigas"
.PP 
.SS "friend class internal::DefaultGlobalTestPartResultReporter\fC [friend]\fP"

.PP
Definición en la línea \fB1157\fP del archivo \fBgtest\&.h\fP\&.
.SS "friend class internal::NoExecDeathTest\fC [friend]\fP"

.PP
Definición en la línea \fB1158\fP del archivo \fBgtest\&.h\fP\&.
.SS "friend class internal::TestEventListenersAccessor\fC [friend]\fP"

.PP
Definición en la línea \fB1159\fP del archivo \fBgtest\&.h\fP\&.
.SS "friend class internal::UnitTestImpl\fC [friend]\fP"

.PP
Definición en la línea \fB1160\fP del archivo \fBgtest\&.h\fP\&.
.SS "friend class \fBTestCase\fP\fC [friend]\fP"

.PP
Definición en la línea \fB1155\fP del archivo \fBgtest\&.h\fP\&.
.SS "friend class \fBTestInfo\fP\fC [friend]\fP"

.PP
Definición en la línea \fB1156\fP del archivo \fBgtest\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
