.TH "testing::internal::RemoveConst< const T[N]>" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::RemoveConst< const T[N]>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBRemoveConst\fP< T >::type \fBtype\fP[N]"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, size_t N>
.br
struct testing::internal::RemoveConst< const T[N]>"
.PP
Definition at line \fB839\fP of file \fBgtest\-internal\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T , size_t N> typedef \fBRemoveConst\fP<T>::type \fBtesting::internal::RemoveConst\fP< const T[N]>::type[N]"

.PP
Definition at line \fB840\fP of file \fBgtest\-internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
