.TH "testing::internal::ParamIteratorInterface< T >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamIteratorInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "virtual \fB~ParamIteratorInterface\fP ()"
.br
.ti -1c
.RI "virtual const \fBParamGeneratorInterface\fP< T > * \fBBaseGenerator\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBAdvance\fP ()=0"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP * \fBClone\fP () const =0"
.br
.ti -1c
.RI "virtual const T * \fBCurrent\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBEquals\fP (const \fBParamIteratorInterface\fP &other) const =0"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
class testing::internal::ParamIteratorInterface< T >"
.PP
Definición en la línea \fB89\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename T > virtual \fBtesting::internal::ParamIteratorInterface\fP< T >::~\fBParamIteratorInterface\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definición en la línea \fB91\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename T > virtual void \fBtesting::internal::ParamIteratorInterface\fP< T >::Advance ()\fC [pure virtual]\fP"

.SS "template<typename T > virtual const \fBParamGeneratorInterface\fP< T > * \fBtesting::internal::ParamIteratorInterface\fP< T >::BaseGenerator () const\fC [pure virtual]\fP"

.SS "template<typename T > virtual \fBParamIteratorInterface\fP * \fBtesting::internal::ParamIteratorInterface\fP< T >::Clone () const\fC [pure virtual]\fP"

.SS "template<typename T > virtual const T * \fBtesting::internal::ParamIteratorInterface\fP< T >::Current () const\fC [pure virtual]\fP"

.SS "template<typename T > virtual bool \fBtesting::internal::ParamIteratorInterface\fP< T >::Equals (const \fBParamIteratorInterface\fP< T > & other) const\fC [pure virtual]\fP"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
