.TH "testing::internal::TypeWithSize< size >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TypeWithSize< size >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBUInt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<size_t size>
.br
class testing::internal::TypeWithSize< size >"
.PP
Definition at line \fB2608\fP of file \fBgtest\-port\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<size_t size> typedef void \fBtesting::internal::TypeWithSize\fP< size >::\fBUInt\fP"

.PP
Definition at line \fB2612\fP of file \fBgtest\-port\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
