.TH "testing::internal::bool_constant< bool_value >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::bool_constant< bool_value >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.PP
Heredado por \fBtesting::internal::HasValueType< T, typename >\fP, \fBtesting::internal::HasValueType< T, VoidT< typename T::value_type > >\fP, \fBtesting::internal::IsRecursiveContainerImpl< C, false, HV >\fP, \fBtesting::internal::IsRecursiveContainerImpl< C, true, false >\fP, \fBtesting::internal::is_pointer< T >\fP, \fBtesting::internal::is_pointer< T * >\fP, \fBtesting::internal::is_same< T, U >\fP y \fBtesting::internal::is_same< T, T >\fP\&.
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef \fBbool_constant\fP< bool_value > \fBtype\fP"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP = bool_value"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<bool bool_value>
.br
struct testing::internal::bool_constant< bool_value >"
.PP
Definición en la línea \fB2342\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<bool bool_value> typedef \fBbool_constant\fP<bool_value> \fBtesting::internal::bool_constant\fP< bool_value >::\fBtype\fP"

.PP
Definición en la línea \fB2343\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "template<bool bool_value> const bool \fBtesting::internal::bool_constant\fP< bool_value >::value = bool_value\fC [static]\fP"

.PP
Definición en la línea \fB2344\fP del archivo \fBgtest\-port\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
