.TH "testing::internal::ParamGeneratorInterface< T >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamGeneratorInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.PP
Heredado por \fBtesting::internal::RangeGenerator< T, IncrementT >\fP y \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP\&.
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef T \fBParamType\fP"
.br
.in -1c
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "virtual \fB~ParamGeneratorInterface\fP ()"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< T > * \fBBegin\fP () const =0"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP< T > * \fBEnd\fP () const =0"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
class testing::internal::ParamGeneratorInterface< T >"
.PP
Definición en la línea \fB162\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename T > typedef T \fBtesting::internal::ParamGeneratorInterface\fP< T >::\fBParamType\fP"

.PP
Definición en la línea \fB164\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename T > virtual \fBtesting::internal::ParamGeneratorInterface\fP< T >::~\fBParamGeneratorInterface\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definición en la línea \fB166\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename T > virtual \fBParamIteratorInterface\fP< T > * \fBtesting::internal::ParamGeneratorInterface\fP< T >::Begin () const\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::internal::RangeGenerator< T, IncrementT >\fP y \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP\&.
.SS "template<typename T > virtual \fBParamIteratorInterface\fP< T > * \fBtesting::internal::ParamGeneratorInterface\fP< T >::End () const\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::internal::RangeGenerator< T, IncrementT >\fP y \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
