.TH "testing::internal::FormatForComparison< ToPrint[N], OtherOperand >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::FormatForComparison< ToPrint[N], OtherOperand >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-printers\&.h>\fP
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "::std::string \fBFormat\fP (const ToPrint *value)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename ToPrint, size_t N, typename OtherOperand>
.br
class testing::internal::FormatForComparison< ToPrint[N], OtherOperand >"
.PP
Definición en la línea \fB320\fP del archivo \fBgtest\-printers\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename ToPrint , size_t N, typename OtherOperand > ::std::string \fBtesting::internal::FormatForComparison\fP< ToPrint[N], OtherOperand >::Format (const ToPrint * value)\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB322\fP del archivo \fBgtest\-printers\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
