.TH "testing::internal::StaticAssertTypeEqHelper< T, T >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::StaticAssertTypeEqHelper< T, T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBvalue\fP = true }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct testing::internal::StaticAssertTypeEqHelper< T, T >"
.PP
Definition at line \fB1158\fP of file \fBgtest\-port\&.h\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "template<typename T > anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIvalue \fP\fP
.PP
Definition at line \fB1159\fP of file \fBgtest\-port\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
