.TH "testing::internal::IsRecursiveContainerImpl< C, true, true >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IsRecursiveContainerImpl< C, true, true >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBIteratorTraits\fP< typenameC::iterator >::\fBvalue_type\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef \fBis_same\fP< \fBvalue_type\fP, C > \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename C>
.br
struct testing::internal::IsRecursiveContainerImpl< C, true, true >"
.PP
Definition at line \fB1016\fP of file \fBgtest\-internal\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename C > typedef \fBis_same\fP<\fBvalue_type\fP, C> \fBtesting::internal::IsRecursiveContainerImpl\fP< C, true, true >::\fBtype\fP"

.PP
Definition at line \fB1023\fP of file \fBgtest\-internal\&.h\fP\&.
.SS "template<typename C > typedef \fBIteratorTraits\fP<typenameC::iterator>::\fBvalue_type\fP \fBtesting::internal::IsRecursiveContainerImpl\fP< C, true, true >::\fBvalue_type\fP"

.PP
Definition at line \fB1021\fP of file \fBgtest\-internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
