.TH "testing::internal::linked_ptr_internal" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::linked_ptr_internal
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-linked_ptr\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBjoin_new\fP ()"
.br
.ti -1c
.RI "void \fBjoin\fP (\fBlinked_ptr_internal\fP const *ptr) \fBGTEST_LOCK_EXCLUDED_\fP(g_linked_ptr_mutex)"
.br
.ti -1c
.RI "bool \fBdepart\fP () \fBGTEST_LOCK_EXCLUDED_\fP(g_linked_ptr_mutex)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB89\fP del archivo \fBgtest\-linked_ptr\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "bool testing::internal::linked_ptr_internal::depart ()\fC [inline]\fP"

.PP
Definición en la línea \fB125\fP del archivo \fBgtest\-linked_ptr\&.h\fP\&.
.SS "void testing::internal::linked_ptr_internal::join (\fBlinked_ptr_internal\fP const * ptr)\fC [inline]\fP"

.PP
Definición en la línea \fB108\fP del archivo \fBgtest\-linked_ptr\&.h\fP\&.
.SS "void testing::internal::linked_ptr_internal::join_new ()\fC [inline]\fP"

.PP
Definición en la línea \fB92\fP del archivo \fBgtest\-linked_ptr\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
