.TH "testing::internal::ConstRef< T & >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ConstRef< T & >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef T & \fBtype\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
struct testing::internal::ConstRef< T & >"
.PP
Definición en la línea \fB1427\fP del archivo \fBgtest\-port\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename T > typedef T& \fBtesting::internal::ConstRef\fP< T & >::\fBtype\fP"

.PP
Definición en la línea \fB1427\fP del archivo \fBgtest\-port\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
