.TH "testing::internal::Random" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::Random
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBRandom\fP (\fBUInt32\fP seed)"
.br
.ti -1c
.RI "void \fBReseed\fP (\fBUInt32\fP seed)"
.br
.ti -1c
.RI "\fBUInt32\fP \fBGenerate\fP (\fBUInt32\fP range)"
.br
.in -1c
.SS "Atributos públicos estáticos"

.in +1c
.ti -1c
.RI "static const \fBUInt32\fP \fBkMaxRange\fP = 1u << 31"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB788\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "testing::internal::Random::Random (\fBUInt32\fP seed)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definición en la línea \fB792\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "\fBUInt32\fP testing::internal::Random::Generate (\fBUInt32\fP range)"

.SS "void testing::internal::Random::Reseed (\fBUInt32\fP seed)\fC [inline]\fP"

.PP
Definición en la línea \fB794\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "const \fBUInt32\fP testing::internal::Random::kMaxRange = 1u << 31\fC [static]\fP"

.PP
Definición en la línea \fB790\fP del archivo \fBgtest\-internal\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
