.TH "testing::internal::EqHelper< true >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::EqHelper< true >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T1 , typename T2 > static AssertionResult \fBCompare\fP (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs, typename \fBEnableIf\fP<!\fBis_pointer\fP< T2 >::value >::type *=0)"
.br
.ti -1c
.RI "template<typename T > static AssertionResult \fBCompare\fP (const char *lhs_expression, const char *rhs_expression, Secret *, T *rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1492\fP of file \fBgtest\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T1 , typename T2 > static AssertionResult \fBtesting::internal::EqHelper\fP< true >::Compare (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs, typename \fBEnableIf\fP<!\fBis_pointer\fP< T2 >::value >::type * = \fC0\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1499\fP of file \fBgtest\&.h\fP\&.
.SS "template<typename T > static AssertionResult \fBtesting::internal::EqHelper\fP< true >::Compare (const char * lhs_expression, const char * rhs_expression, Secret *, T * rhs)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1516\fP of file \fBgtest\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
