.TH "testing::internal::UniversalPrinter< T[N]>" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::UniversalPrinter< T[N]>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-printers\&.h>\fP
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static void \fBPrint\fP (const T(&a)[N], ::std::ostream *os)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T, size_t N>
.br
class testing::internal::UniversalPrinter< T[N]>"
.PP
Definición en la línea \fB850\fP del archivo \fBgtest\-printers\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename T , size_t N> static void \fBtesting::internal::UniversalPrinter\fP< T[N]>::Print (const T(&) a[N], ::std::ostream * os)\fC [inline]\fP, \fC [static]\fP"

.PP
Definición en la línea \fB854\fP del archivo \fBgtest\-printers\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
