.TH "testing::internal::ParamGenerator< T >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamGenerator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBParamIterator\fP< T > \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParamGenerator\fP (\fBParamGeneratorInterface\fP< T > *impl)"
.br
.ti -1c
.RI "\fBParamGenerator\fP (const \fBParamGenerator\fP &other)"
.br
.ti -1c
.RI "\fBParamGenerator\fP & \fBoperator=\fP (const \fBParamGenerator\fP &other)"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class testing::internal::ParamGenerator< T >"
.PP
Definition at line \fB179\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > typedef \fBParamIterator\fP<T> \fBtesting::internal::ParamGenerator\fP< T >::\fBiterator\fP"

.PP
Definition at line \fB181\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBtesting::internal::ParamGenerator\fP< T >::\fBParamGenerator\fP (\fBParamGeneratorInterface\fP< T > * impl)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB183\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > \fBtesting::internal::ParamGenerator\fP< T >::\fBParamGenerator\fP (const \fBParamGenerator\fP< T > & other)\fC [inline]\fP"

.PP
Definition at line \fB184\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBiterator\fP \fBtesting::internal::ParamGenerator\fP< T >::begin () const\fC [inline]\fP"

.PP
Definition at line \fB191\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > \fBiterator\fP \fBtesting::internal::ParamGenerator\fP< T >::end () const\fC [inline]\fP"

.PP
Definition at line \fB192\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SS "template<typename T > \fBParamGenerator\fP & \fBtesting::internal::ParamGenerator\fP< T >::operator= (const \fBParamGenerator\fP< T > & other)\fC [inline]\fP"

.PP
Definition at line \fB186\fP of file \fBgtest\-param\-util\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
