.TH "testing::internal::ParameterizedTestCaseInfoBase" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParameterizedTestCaseInfoBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.PP
Heredado por \fBtesting::internal::ParameterizedTestCaseInfo< TestCase >\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "virtual \fB~ParameterizedTestCaseInfoBase\fP ()"
.br
.ti -1c
.RI "virtual const std::string & \fBGetTestCaseName\fP () const =0"
.br
.ti -1c
.RI "virtual \fBTypeId\fP \fBGetTestCaseTypeId\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBRegisterTests\fP ()=0"
.br
.in -1c
.SS "Métodos protegidos"

.in +1c
.ti -1c
.RI "\fBParameterizedTestCaseInfoBase\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB466\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "virtual testing::internal::ParameterizedTestCaseInfoBase::~ParameterizedTestCaseInfoBase ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definición en la línea \fB468\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SS "testing::internal::ParameterizedTestCaseInfoBase::ParameterizedTestCaseInfoBase ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definición en la línea \fB481\fP del archivo \fBgtest\-param\-util\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "virtual const std::string & testing::internal::ParameterizedTestCaseInfoBase::GetTestCaseName () const\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::internal::ParameterizedTestCaseInfo< TestCase >\fP\&.
.SS "virtual \fBTypeId\fP testing::internal::ParameterizedTestCaseInfoBase::GetTestCaseTypeId () const\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::internal::ParameterizedTestCaseInfo< TestCase >\fP\&.
.SS "virtual void testing::internal::ParameterizedTestCaseInfoBase::RegisterTests ()\fC [pure virtual]\fP"

.PP
Implementado en \fBtesting::internal::ParameterizedTestCaseInfo< TestCase >\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
