.TH "testing::internal::UniversalPrinter< T & >" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::UniversalPrinter< T & >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-printers\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBPrint\fP (const T &value, ::std::ostream *os)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class testing::internal::UniversalPrinter< T & >"
.PP
Definition at line \fB861\fP of file \fBgtest\-printers\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static void \fBtesting::internal::UniversalPrinter\fP< T & >::Print (const T & value, ::std::ostream * os)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB867\fP of file \fBgtest\-printers\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
