.TH "testing::internal::EqHelper< lhs_is_null_literal >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::EqHelper< lhs_is_null_literal >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T1 , typename T2 > static AssertionResult \fBCompare\fP (const char *lhs_expression, const char *rhs_expression, const T1 &lhs, const T2 &rhs)"
.br
.ti -1c
.RI "static AssertionResult \fBCompare\fP (const char *lhs_expression, const char *rhs_expression, \fBBiggestInt\fP lhs, \fBBiggestInt\fP rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool lhs_is_null_literal>
.br
class testing::internal::EqHelper< lhs_is_null_literal >"
.PP
Definition at line \fB1464\fP of file \fBgtest\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<bool lhs_is_null_literal> static AssertionResult \fBtesting::internal::EqHelper\fP< lhs_is_null_literal >::Compare (const char * lhs_expression, const char * rhs_expression, \fBBiggestInt\fP lhs, \fBBiggestInt\fP rhs)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1481\fP of file \fBgtest\&.h\fP\&.
.SS "template<bool lhs_is_null_literal> template<typename T1 , typename T2 > static AssertionResult \fBtesting::internal::EqHelper\fP< lhs_is_null_literal >::Compare (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line \fB1468\fP of file \fBgtest\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
