.TH "testing::internal::RemoveConst< const T[N]>" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::RemoveConst< const T[N]>
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef \fBRemoveConst\fP< T >::type \fBtype\fP[N]"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T, size_t N>
.br
struct testing::internal::RemoveConst< const T[N]>"
.PP
Definición en la línea \fB839\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename T , size_t N> typedef \fBRemoveConst\fP<T>::type \fBtesting::internal::RemoveConst\fP< const T[N]>::type[N]"

.PP
Definición en la línea \fB840\fP del archivo \fBgtest\-internal\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
