.TH "testing::internal::StaticAssertTypeEqHelper< T1, T2 >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::StaticAssertTypeEqHelper< T1, T2 >
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename T1, typename T2>
.br
struct testing::internal::StaticAssertTypeEqHelper< T1, T2 >"
.PP
Definition at line \fB1155\fP of file \fBgtest\-port\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
