.TH "testing::Message" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::Message
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-message\&.h>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBMessage\fP ()"
.br
.ti -1c
.RI "\fBMessage\fP (const \fBMessage\fP &msg)"
.br
.ti -1c
.RI "\fBMessage\fP (const char *str)"
.br
.ti -1c
.RI "template<typename T > \fBMessage\fP & \fBoperator<<\fP (const T &val)"
.br
.ti -1c
.RI "template<typename T > \fBMessage\fP & \fBoperator<<\fP (T *const &pointer)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (BasicNarrowIoManip val)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (bool b)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (const wchar_t *wide_c_str)"
.br
.ti -1c
.RI "\fBMessage\fP & \fBoperator<<\fP (wchar_t *wide_c_str)"
.br
.ti -1c
.RI "std::string \fBGetString\fP () const"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB89\fP del archivo \fBgtest\-message\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "testing::Message::Message ()"

.SS "testing::Message::Message (const \fBMessage\fP & msg)\fC [inline]\fP"

.PP
Definición en la línea \fB100\fP del archivo \fBgtest\-message\&.h\fP\&.
.SS "testing::Message::Message (const char * str)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definición en la línea \fB105\fP del archivo \fBgtest\-message\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "std::string testing::Message::GetString () const"

.SS "\fBMessage\fP & testing::Message::operator<< (BasicNarrowIoManip val)\fC [inline]\fP"

.PP
Definición en la línea \fB169\fP del archivo \fBgtest\-message\&.h\fP\&.
.SS "\fBMessage\fP & testing::Message::operator<< (bool b)\fC [inline]\fP"

.PP
Definición en la línea \fB175\fP del archivo \fBgtest\-message\&.h\fP\&.
.SS "template<typename T > \fBMessage\fP & testing::Message::operator<< (const T & val)\fC [inline]\fP"

.PP
Definición en la línea \fB119\fP del archivo \fBgtest\-message\&.h\fP\&.
.SS "\fBMessage\fP & testing::Message::operator<< (const wchar_t * wide_c_str)"

.SS "template<typename T > \fBMessage\fP & testing::Message::operator<< (T *const & pointer)\fC [inline]\fP"

.PP
Definición en la línea \fB153\fP del archivo \fBgtest\-message\&.h\fP\&.
.SS "\fBMessage\fP & testing::Message::operator<< (wchar_t * wide_c_str)"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
