.TH "testing::internal::NativeArray< Element >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::NativeArray< Element >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef Element \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef Element * \fBiterator\fP"
.br
.ti -1c
.RI "typedef const Element * \fBconst_iterator\fP"
.br
.in -1c
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBNativeArray\fP (const Element *array, size_t count, \fBRelationToSourceReference\fP)"
.br
.ti -1c
.RI "\fBNativeArray\fP (const Element *array, size_t count, \fBRelationToSourceCopy\fP)"
.br
.ti -1c
.RI "\fBNativeArray\fP (const \fBNativeArray\fP &rhs)"
.br
.ti -1c
.RI "\fB~NativeArray\fP ()"
.br
.ti -1c
.RI "size_t \fBsize\fP () const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBend\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBNativeArray\fP &rhs) const"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename Element>
.br
class testing::internal::NativeArray< Element >"
.PP
Definición en la línea \fB1127\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename Element > typedef const Element* \fBtesting::internal::NativeArray\fP< Element >::\fBconst_iterator\fP"

.PP
Definición en la línea \fB1132\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename Element > typedef Element* \fBtesting::internal::NativeArray\fP< Element >::\fBiterator\fP"

.PP
Definición en la línea \fB1131\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename Element > typedef Element \fBtesting::internal::NativeArray\fP< Element >::\fBvalue_type\fP"

.PP
Definición en la línea \fB1130\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename Element > \fBtesting::internal::NativeArray\fP< Element >::\fBNativeArray\fP (const Element * array, size_t count, \fBRelationToSourceReference\fP)\fC [inline]\fP"

.PP
Definición en la línea \fB1135\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename Element > \fBtesting::internal::NativeArray\fP< Element >::\fBNativeArray\fP (const Element * array, size_t count, \fBRelationToSourceCopy\fP)\fC [inline]\fP"

.PP
Definición en la línea \fB1140\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename Element > \fBtesting::internal::NativeArray\fP< Element >::\fBNativeArray\fP (const \fBNativeArray\fP< Element > & rhs)\fC [inline]\fP"

.PP
Definición en la línea \fB1145\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename Element > \fBtesting::internal::NativeArray\fP< Element >::~\fBNativeArray\fP ()\fC [inline]\fP"

.PP
Definición en la línea \fB1149\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename Element > \fBconst_iterator\fP \fBtesting::internal::NativeArray\fP< Element >::begin () const\fC [inline]\fP"

.PP
Definición en la línea \fB1156\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename Element > \fBconst_iterator\fP \fBtesting::internal::NativeArray\fP< Element >::end () const\fC [inline]\fP"

.PP
Definición en la línea \fB1157\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename Element > bool \fBtesting::internal::NativeArray\fP< Element >::operator== (const \fBNativeArray\fP< Element > & rhs) const\fC [inline]\fP"

.PP
Definición en la línea \fB1158\fP del archivo \fBgtest\-internal\&.h\fP\&.
.SS "template<typename Element > size_t \fBtesting::internal::NativeArray\fP< Element >::size () const\fC [inline]\fP"

.PP
Definición en la línea \fB1155\fP del archivo \fBgtest\-internal\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
