.TH "testing::internal::ValueArray2< T1, T2 >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ValueArray2< T1, T2 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\-generated\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValueArray2\fP (T1 v1, T2 v2)"
.br
.ti -1c
.RI "template<typename T > \fBoperator ParamGenerator< T >\fP () const"
.br
.ti -1c
.RI "\fBValueArray2\fP (const \fBValueArray2\fP &other)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T1, typename T2>
.br
class testing::internal::ValueArray2< T1, T2 >"
.PP
Definition at line \fB93\fP of file \fBgtest\-param\-util\-generated\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T1 , typename T2 > \fBtesting::internal::ValueArray2\fP< T1, T2 >::\fBValueArray2\fP (T1 v1, T2 v2)\fC [inline]\fP"

.PP
Definition at line \fB95\fP of file \fBgtest\-param\-util\-generated\&.h\fP\&.
.SS "template<typename T1 , typename T2 > \fBtesting::internal::ValueArray2\fP< T1, T2 >::\fBValueArray2\fP (const \fBValueArray2\fP< T1, T2 > & other)\fC [inline]\fP"

.PP
Definition at line \fB103\fP of file \fBgtest\-param\-util\-generated\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T1 , typename T2 > template<typename T > \fBtesting::internal::ValueArray2\fP< T1, T2 >::operator \fBParamGenerator\fP< T > () const\fC [inline]\fP"

.PP
Definition at line \fB98\fP of file \fBgtest\-param\-util\-generated\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
