.TH "testing::WithParamInterface< T >" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::WithParamInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\&.h>\fP
.PP
Heredado por \fBtesting::TestWithParam< T >\fP\&.
.SS "Tipos públicos"

.in +1c
.ti -1c
.RI "typedef T \fBParamType\fP"
.br
.in -1c
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "virtual \fB~WithParamInterface\fP ()"
.br
.ti -1c
.RI "const \fBParamType\fP & \fBGetParam\fP () const"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "template<class TestClass > class \fBinternal::ParameterizedTestFactory\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SS "template<typename T>
.br
class testing::WithParamInterface< T >"
.PP
Definición en la línea \fB1795\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación de los 'Typedef' miembros de la clase"
.PP 
.SS "template<typename T > typedef T \fBtesting::WithParamInterface\fP< T >::\fBParamType\fP"

.PP
Definición en la línea \fB1797\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "template<typename T > virtual \fBtesting::WithParamInterface\fP< T >::~\fBWithParamInterface\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definición en la línea \fB1798\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "template<typename T > const \fBParamType\fP & \fBtesting::WithParamInterface\fP< T >::GetParam () const\fC [inline]\fP"

.PP
Definición en la línea \fB1805\fP del archivo \fBgtest\&.h\fP\&.
.SH "Documentación de las funciones relacionadas y clases amigas"
.PP 
.SS "template<typename T > template<class TestClass > friend class \fBinternal::ParameterizedTestFactory\fP\fC [friend]\fP"

.PP
Definición en la línea \fB1823\fP del archivo \fBgtest\&.h\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
