.TH "testing::internal::ParameterizedTestFactory< TestClass >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParameterizedTestFactory< TestClass >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.PP
Inherits \fBtesting::internal::TestFactoryBase\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef TestClass::ParamType \fBParamType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterizedTestFactory\fP (\fBParamType\fP parameter)"
.br
.ti -1c
.RI "virtual \fBTest\fP * \fBCreateTest\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<class TestClass>
.br
class testing::internal::ParameterizedTestFactory< TestClass >"
.PP
Definition at line \fB404\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class TestClass > typedef TestClass::ParamType \fBtesting::internal::ParameterizedTestFactory\fP< TestClass >::\fBParamType\fP"

.PP
Definition at line \fB406\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class TestClass > \fBtesting::internal::ParameterizedTestFactory\fP< TestClass >::\fBParameterizedTestFactory\fP (\fBParamType\fP parameter)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB407\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class TestClass > virtual \fBTest\fP * \fBtesting::internal::ParameterizedTestFactory\fP< TestClass >::CreateTest ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBtesting::internal::TestFactoryBase\fP\&.
.PP
Definition at line \fB409\fP of file \fBgtest\-param\-util\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
