.TH "testing::internal::TypeWithSize< 8 >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::TypeWithSize< 8 >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef long long \fBInt\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBUInt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2629\fP of file \fBgtest\-port\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef long long \fBtesting::internal::TypeWithSize\fP< 8 >::\fBInt\fP"

.PP
Definition at line \fB2635\fP of file \fBgtest\-port\&.h\fP\&.
.SS "typedef unsigned long long \fBtesting::internal::TypeWithSize\fP< 8 >::\fBUInt\fP"

.PP
Definition at line \fB2636\fP of file \fBgtest\-port\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
