.TH "testing::internal::HasValueType< T, typename >" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::HasValueType< T, typename >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-internal\&.h>\fP
.PP
Inherits \fBtesting::internal::bool_constant< bool_value >\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename = void>
.br
struct testing::internal::HasValueType< T, typename >"
.PP
Definition at line \fB995\fP of file \fBgtest\-internal\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
