.TH "Tool" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tool
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <$tool\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTool\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "int \fBaddArg\fP (const char *arg)"
.br
.ti -1c
.RI "int \fBaddArg\fP (const char *name, const char *value)"
.br
.ti -1c
.RI "int \fBgetArgc\fP ()"
.br
.ti -1c
.RI "char * \fBmystrdup\fP (const char *str)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char ** \fBargv\fP = nullptr"
.br
.ti -1c
.RI "int \fBargc\fP = 0"
.br
.ti -1c
.RI "struct tm \fBnow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fB$tool\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Tool::Tool ()"

.PP
Definition at line \fB6\fP of file \fB$tool\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int Tool::addArg (const char * arg)"

.PP
Definition at line \fB35\fP of file \fB$tool\&.cpp\fP\&.
.SS "int Tool::addArg (const char * name, const char * value)"

.PP
Definition at line \fB42\fP of file \fB$tool\&.cpp\fP\&.
.SS "int Tool::getArgc ()"

.PP
Definition at line \fB29\fP of file \fB$tool\&.cpp\fP\&.
.SS "char * Tool::mystrdup (const char * str)\fC [inline]\fP"

.PP
Definition at line \fB17\fP of file \fB$tool\&.cpp\fP\&.
.SS "void Tool::reset ()"

.PP
Definition at line \fB24\fP of file \fB$tool\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Tool::argc = 0"

.PP
Definition at line \fB17\fP of file \fB$tool\&.hpp\fP\&.
.SS "char** Tool::argv = nullptr"

.PP
Definition at line \fB16\fP of file \fB$tool\&.hpp\fP\&.
.SS "struct tm Tool::now"

.PP
Definition at line \fB18\fP of file \fB$tool\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
