.TH "Tool" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tool
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <$tool\&.hpp>\fP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBTool\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "int \fBaddArg\fP (const char *arg)"
.br
.ti -1c
.RI "int \fBaddArg\fP (const char *name, const char *value)"
.br
.ti -1c
.RI "int \fBgetArgc\fP ()"
.br
.ti -1c
.RI "char * \fBmystrdup\fP (const char *str)"
.br
.in -1c
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "char ** \fBargv\fP = nullptr"
.br
.ti -1c
.RI "int \fBargc\fP = 0"
.br
.ti -1c
.RI "struct tm \fBnow\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB14\fP del archivo \fB$tool\&.hpp\fP\&.
.SH "Documentación del constructor y destructor"
.PP 
.SS "Tool::Tool ()"

.PP
Definición en la línea \fB6\fP del archivo \fB$tool\&.cpp\fP\&.
.SH "Documentación de las funciones miembro"
.PP 
.SS "int Tool::addArg (const char * arg)"

.PP
Definición en la línea \fB35\fP del archivo \fB$tool\&.cpp\fP\&.
.SS "int Tool::addArg (const char * name, const char * value)"

.PP
Definición en la línea \fB42\fP del archivo \fB$tool\&.cpp\fP\&.
.SS "int Tool::getArgc ()"

.PP
Definición en la línea \fB29\fP del archivo \fB$tool\&.cpp\fP\&.
.SS "char * Tool::mystrdup (const char * str)\fC [inline]\fP"

.PP
Definición en la línea \fB17\fP del archivo \fB$tool\&.cpp\fP\&.
.SS "void Tool::reset ()"

.PP
Definición en la línea \fB24\fP del archivo \fB$tool\&.cpp\fP\&.
.SH "Documentación de los datos miembro"
.PP 
.SS "int Tool::argc = 0"

.PP
Definición en la línea \fB17\fP del archivo \fB$tool\&.hpp\fP\&.
.SS "char** Tool::argv = nullptr"

.PP
Definición en la línea \fB16\fP del archivo \fB$tool\&.hpp\fP\&.
.SS "struct tm Tool::now"

.PP
Definición en la línea \fB18\fP del archivo \fB$tool\&.hpp\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
