.TH "testcmdline/TypesTest.cpp" 3 "Fri Nov 5 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcmdline/TypesTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'pch\&.h'\fP
.br
\fC#include '$tool\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (Types, \fBSTRING\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, string)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, char)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, \fBNUMBER\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, LONG)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, INT)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, long)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, int)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, \fBDECIMAL\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, FLOAT)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, float)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, \fBDATE\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, \fBTIME\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, \fBDATETIME\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (Types, \fBTMS\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (Types, char)"

.PP
Definition at line \fB24\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, \fBDATE\fP)"

.PP
Definition at line \fB105\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, \fBDATETIME\fP)"

.PP
Definition at line \fB127\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, \fBDECIMAL\fP)"

.PP
Definition at line \fB78\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, FLOAT)"

.PP
Definition at line \fB87\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, float)"

.PP
Definition at line \fB96\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, INT)"

.PP
Definition at line \fB51\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, int)"

.PP
Definition at line \fB69\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, LONG)"

.PP
Definition at line \fB42\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, long)"

.PP
Definition at line \fB60\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, \fBNUMBER\fP)"

.PP
Definition at line \fB33\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, \fBSTRING\fP)"

.PP
Definition at line \fB5\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, string)"

.PP
Definition at line \fB15\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, \fBTIME\fP)"

.PP
Definition at line \fB116\fP of file \fBTypesTest\&.cpp\fP\&.
.SS "TEST (Types, \fBTMS\fP)"

.PP
Definition at line \fB138\fP of file \fBTypesTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
