.TH "libcmdline/include/types.hpp" 3 "Viernes, 5 de Noviembre de 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcmdline/include/types.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <filesystem>\fP
.br
\fC#include <unordered_map>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcmdline\fP"
.br
.in -1c
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fB__CMDLINE_TYPESCPP__\fP"
.br
.in -1c
.SS "Enumeraciones"

.in +1c
.ti -1c
.RI "enum class \fBcmdline::Type\fP { \fBcmdline::Type::STRING\fP =0, \fBcmdline::Type::CHAR\fP, \fBcmdline::Type::BOOL\fP, \fBcmdline::Type::NUMBER\fP, \fBcmdline::Type::DECIMAL\fP, \fBcmdline::Type::LONGNUMBER\fP, \fBcmdline::Type::LONGDECIMAL\fP, \fBcmdline::Type::DATE\fP, \fBcmdline::Type::TIME\fP, \fBcmdline::Type::DATETIME\fP, \fBcmdline::Type::TMS\fP, \fBcmdline::Type::DIR\fP, \fBcmdline::Type::DIR_EXISTS\fP, \fBcmdline::Type::FILE\fP, \fBcmdline::Type::FILE_EXISTS\fP, \fBcmdline::Type::FLAG\fP, \fBcmdline::Type::STRING\fP =0, \fBcmdline::Type::CHAR\fP, \fBcmdline::Type::BOOL\fP, \fBcmdline::Type::NUMBER\fP, \fBcmdline::Type::DECIMAL\fP, \fBcmdline::Type::LONGNUMBER\fP, \fBcmdline::Type::LONGDECIMAL\fP, \fBcmdline::Type::DATE\fP, \fBcmdline::Type::TIME\fP, \fBcmdline::Type::DATETIME\fP, \fBcmdline::Type::TMS\fP, \fBcmdline::Type::DIR\fP, \fBcmdline::Type::DIR_EXISTS\fP, \fBcmdline::Type::FILE\fP, \fBcmdline::Type::FILE_EXISTS\fP, \fBcmdline::Type::FLAG\fP }"
.br
.RI "Define el tipo de dato esperado del parametro\&. "
.ti -1c
.RI "enum class \fBcmdline::Source\fP { \fBcmdline::DEFAULT\fP, \fBcmdline::ENV\fP, \fBcmdline::CMDLINE\fP, \fBcmdline::CODE\fP, \fBcmdline::AUTO\fP, \fBcmdline::DEFAULT\fP, \fBcmdline::ENV\fP, \fBcmdline::CMDLINE\fP, \fBcmdline::CODE\fP, \fBcmdline::AUTO\fP }"
.br
.in -1c
.SH "Documentación de los 'defines'"
.PP 
.SS "#define __CMDLINE_TYPESCPP__"

.PP
Definición en la línea \fB6\fP del archivo \fBtypes\&.hpp\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Command Line Processor del código fuente\&.
