.TH "testcmdline/validationsTest.cpp" 3 "Mon Nov 8 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcmdline/validationsTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'pch\&.h'\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <regex>\fP
.br
\fC#include '\&.\&./libcmdline/include/validations\&.hpp'\fP
.br
\fC#include '\&.\&./libcmdline/include/cmdline_exceptions\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (Validations, Times_OK)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Times_KO)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Dates_OK)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Dates_KO)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Datetimes_OK)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Datetimes_KO)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Timestamp_OK)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Timestamp_KO)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Numbers_OK)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Numbers_KO)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, LongNumbers_OK)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, LongNumbers_KO)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Decimals_OK)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, Decimals_KO)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, LongDecimals_OK)"
.br
.ti -1c
.RI "\fBTEST\fP (Validations, LongDecimals_KO)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (Validations, Dates_KO)"

.PP
Definition at line \fB47\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Dates_OK)"

.PP
Definition at line \fB32\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Datetimes_KO)"

.PP
Definition at line \fB67\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Datetimes_OK)"

.PP
Definition at line \fB58\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Decimals_KO)"

.PP
Definition at line \fB154\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Decimals_OK)"

.PP
Definition at line \fB142\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, LongDecimals_KO)"

.PP
Definition at line \fB172\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, LongDecimals_OK)"

.PP
Definition at line \fB160\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, LongNumbers_KO)"

.PP
Definition at line \fB132\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, LongNumbers_OK)"

.PP
Definition at line \fB121\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Numbers_KO)"

.PP
Definition at line \fB111\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Numbers_OK)"

.PP
Definition at line \fB100\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Times_KO)"

.PP
Definition at line \fB22\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Times_OK)"

.PP
Definition at line \fB11\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Timestamp_KO)"

.PP
Definition at line \fB90\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SS "TEST (Validations, Timestamp_OK)"

.PP
Definition at line \fB83\fP of file \fBvalidationsTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
