.TH "_cmdline::Define" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cmdline::Define
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <defines\&.hpp>\fP
.PP
Inherits \fB_cmdline::Argument\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefine\fP ()=\fBdelete\fP"
.br
.ti -1c
.RI "\fBDefine\fP (const char *\fBname\fP, const char *value)"
.br
.ti -1c
.RI "\fBDefine\fP (const char *\fBname\fP)"
.br
.ti -1c
.RI "\fB~Define\fP ()"
.br
.ti -1c
.RI "void \fBinitValues\fP (vector< string > \fBvalues\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBdefines\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_cmdline::Define::Define ()\fC [delete]\fP"

.SS "_cmdline::Define::Define (const char * name, const char * value)\fC [inline]\fP"

.PP
Definition at line \fB11\fP of file \fBdefines\&.hpp\fP\&.
.SS "_cmdline::Define::Define (const char * name)\fC [inline]\fP"

.PP
Definition at line \fB12\fP of file \fBdefines\&.hpp\fP\&.
.SS "_cmdline::Define::~Define ()\fC [inline]\fP"

.PP
Definition at line \fB16\fP of file \fBdefines\&.hpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void _cmdline::Define::initValues (vector< string > values)\fC [inline]\fP"

.PP
Definition at line \fB19\fP of file \fBdefines\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
