.TH "_cmdline::Argument" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cmdline::Argument
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <argument\&.hpp>\fP
.PP
Inherited by \fB_cmdline::Define\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArgument\fP ()=\fBdelete\fP"
.br
.ti -1c
.RI "\fB~Argument\fP ()"
.br
.ti -1c
.RI "\fBArgument\fP (\fBArgument\fP *arg)"
.br
.ti -1c
.RI "\fBArgument\fP (\fBParm\fP *parm)"
.br
.ti -1c
.RI "\fBArgument\fP (const char *\fBname\fP, const char *value)"
.br
.ti -1c
.RI "\fBArgument\fP (const char *\fBname\fP, const char *value, \fBSource\fP \fBsource\fP)"
.br
.ti -1c
.RI "\fBArgument\fP (const char *\fBname\fP, const char *value, \fBType\fP \fBtype\fP)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBsetFromEnv\fP (const char *value)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBsetValue\fP (bool value)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBsetValue\fP (const char *value)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBsetValue\fP (std::string value)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBaddValue\fP (std::string value)"
.br
.ti -1c
.RI "const char * \fBgetValue\fP ()"
.br
.ti -1c
.RI "vector< const char * > \fBgetValues\fP ()"
.br
.ti -1c
.RI "bool \fBgetBoolean\fP ()"
.br
.ti -1c
.RI "\fBArgument\fP & \fBinitValues\fP (vector< string > \fBvalues\fP)"
.br
.ti -1c
.RI "\fBArgument\fP & \fBmakeUpper\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "\fBSource\fP \fBsource\fP = \fBSource::DEFAULT\fP"
.br
.ti -1c
.RI "\fBType\fP \fBtype\fP = \fBType::STRING\fP"
.br
.ti -1c
.RI "bool \fBmultiple\fP = false"
.br
.ti -1c
.RI "string \fBdefValue\fP"
.br
.ti -1c
.RI "set< string > \fBvalues\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBArgument\fP & \fBaddValues\fP (vector< string > \fBvalues\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBargument\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_cmdline::Argument::Argument ()\fC [delete]\fP"

.SS "_cmdline::Argument::~Argument ()"

.PP
Definition at line \fB55\fP of file \fBargument\&.cpp\fP\&.
.SS "_cmdline::Argument::Argument (\fBArgument\fP * arg)"

.PP
Definition at line \fB22\fP of file \fBargument\&.cpp\fP\&.
.SS "_cmdline::Argument::Argument (\fBParm\fP * parm)"

.PP
Definition at line \fB14\fP of file \fBargument\&.cpp\fP\&.
.SS "_cmdline::Argument::Argument (const char * name, const char * value)"

.PP
Definition at line \fB34\fP of file \fBargument\&.cpp\fP\&.
.SS "_cmdline::Argument::Argument (const char * name, const char * value, \fBSource\fP source)"

.PP
Definition at line \fB39\fP of file \fBargument\&.cpp\fP\&.
.SS "_cmdline::Argument::Argument (const char * name, const char * value, \fBType\fP type)"

.PP
Definition at line \fB51\fP of file \fBargument\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBArgument\fP & _cmdline::Argument::addValue (std::string value)"

.PP
Definition at line \fB114\fP of file \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & _cmdline::Argument::addValues (vector< string > values)\fC [protected]\fP"

.PP
Definition at line \fB119\fP of file \fBargument\&.cpp\fP\&.
.SS "bool _cmdline::Argument::getBoolean ()"

.PP
Definition at line \fB71\fP of file \fBargument\&.cpp\fP\&.
.SS "const char * _cmdline::Argument::getValue ()"

.PP
Definition at line \fB59\fP of file \fBargument\&.cpp\fP\&.
.SS "vector< const char * > _cmdline::Argument::getValues ()"

.PP
Definition at line \fB62\fP of file \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & _cmdline::Argument::initValues (vector< string > values)"

.PP
Definition at line \fB85\fP of file \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & _cmdline::Argument::makeUpper ()"

.PP
Definition at line \fB124\fP of file \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & _cmdline::Argument::setFromEnv (const char * value)"

.PP
Definition at line \fB92\fP of file \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & _cmdline::Argument::setValue (bool value)"

.PP
Definition at line \fB103\fP of file \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & _cmdline::Argument::setValue (const char * value)"

.PP
Definition at line \fB98\fP of file \fBargument\&.cpp\fP\&.
.SS "\fBArgument\fP & _cmdline::Argument::setValue (std::string value)"

.PP
Definition at line \fB109\fP of file \fBargument\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string _cmdline::Argument::defValue"

.PP
Definition at line \fB15\fP of file \fBargument\&.hpp\fP\&.
.SS "bool _cmdline::Argument::multiple = false"

.PP
Definition at line \fB14\fP of file \fBargument\&.hpp\fP\&.
.SS "string _cmdline::Argument::name"

.PP
Definition at line \fB11\fP of file \fBargument\&.hpp\fP\&.
.SS "\fBSource\fP _cmdline::Argument::source = \fBSource::DEFAULT\fP"

.PP
Definition at line \fB12\fP of file \fBargument\&.hpp\fP\&.
.SS "\fBType\fP _cmdline::Argument::type = \fBType::STRING\fP"

.PP
Definition at line \fB13\fP of file \fBargument\&.hpp\fP\&.
.SS "set<string> _cmdline::Argument::values"

.PP
Definition at line \fB16\fP of file \fBargument\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
