.TH "_cmdline::_CommandLine" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cmdline::_CommandLine
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <commandline\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_CommandLine\fP (int argc, char **argv, \fBParameters\fP \fBparms\fP, bool sensitive=false, bool strict=false)"
.br
.ti -1c
.RI "vector< const char * > \fBgetArgs\fP ()"
.br
.ti -1c
.RI "bool \fBhasFlag\fP (const char *flag)"
.br
.ti -1c
.RI "\fBFlags\fP \fBgetDefaultFlags\fP (bool all)"
.br
.ti -1c
.RI "\fBFlags\fP \fBgetCurrentFlags\fP (bool all)"
.br
.ti -1c
.RI "int \fBgetOptionNumValues\fP (const char *name)"
.br
.ti -1c
.RI "bool \fBhasOption\fP (const char *name)"
.br
.ti -1c
.RI "bool \fBisOptionMultiple\fP (const char *name)"
.br
.ti -1c
.RI "\fBOptions\fP \fBgetDefaultOptions\fP ()"
.br
.ti -1c
.RI "\fBOptions\fP \fBgetCurrentOptions\fP ()"
.br
.ti -1c
.RI "const char * \fBgetOption\fP (const char *name)"
.br
.ti -1c
.RI "vector< const char * > \fBgetOptionValues\fP (const char *name)"
.br
.ti -1c
.RI "bool \fBhasDefinition\fP (const char *def)"
.br
.ti -1c
.RI "bool \fBisDefinitionMultiple\fP (const char *name)"
.br
.ti -1c
.RI "const char * \fBgetDefinition\fP (const char *name)"
.br
.ti -1c
.RI "vector< const char * > \fBgetDefinitionValues\fP (const char *name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBcommandline\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "_cmdline::_CommandLine::_CommandLine (int argc, char ** argv, \fBParameters\fP parms, bool sensitive = \fCfalse\fP, bool strict = \fCfalse\fP)"

.PP
Definition at line \fB42\fP of file \fBcommandline\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "vector< const char * > _cmdline::_CommandLine::getArgs ()"

.PP
Definition at line \fB49\fP of file \fBcommandline\&.cpp\fP\&.
.SS "\fBFlags\fP _cmdline::_CommandLine::getCurrentFlags (bool all)"

.PP
Definition at line \fB59\fP of file \fBcommandline\&.cpp\fP\&.
.SS "\fBOptions\fP _cmdline::_CommandLine::getCurrentOptions ()"

.PP
Definition at line \fB85\fP of file \fBcommandline\&.cpp\fP\&.
.SS "\fBFlags\fP _cmdline::_CommandLine::getDefaultFlags (bool all)"

.PP
Definition at line \fB56\fP of file \fBcommandline\&.cpp\fP\&.
.SS "\fBOptions\fP _cmdline::_CommandLine::getDefaultOptions ()"

.PP
Definition at line \fB82\fP of file \fBcommandline\&.cpp\fP\&.
.SS "const char * _cmdline::_CommandLine::getDefinition (const char * name)\fC [inline]\fP"

.PP
Definition at line \fB34\fP of file \fBcommandline\&.hpp\fP\&.
.SS "vector< const char * > _cmdline::_CommandLine::getDefinitionValues (const char * name)"

.PP
Definition at line \fB96\fP of file \fBcommandline\&.cpp\fP\&.
.SS "const char * _cmdline::_CommandLine::getOption (const char * name)"

.PP
Definition at line \fB78\fP of file \fBcommandline\&.cpp\fP\&.
.SS "int _cmdline::_CommandLine::getOptionNumValues (const char * name)"

.PP
Definition at line \fB74\fP of file \fBcommandline\&.cpp\fP\&.
.SS "vector< const char * > _cmdline::_CommandLine::getOptionValues (const char * name)"

.PP
Definition at line \fB70\fP of file \fBcommandline\&.cpp\fP\&.
.SS "bool _cmdline::_CommandLine::hasDefinition (const char * def)"

.PP
Definition at line \fB88\fP of file \fBcommandline\&.cpp\fP\&.
.SS "bool _cmdline::_CommandLine::hasFlag (const char * flag)"

.PP
Definition at line \fB52\fP of file \fBcommandline\&.cpp\fP\&.
.SS "bool _cmdline::_CommandLine::hasOption (const char * name)"

.PP
Definition at line \fB62\fP of file \fBcommandline\&.cpp\fP\&.
.SS "bool _cmdline::_CommandLine::isDefinitionMultiple (const char * name)"

.PP
Definition at line \fB92\fP of file \fBcommandline\&.cpp\fP\&.
.SS "bool _cmdline::_CommandLine::isOptionMultiple (const char * name)"

.PP
Definition at line \fB66\fP of file \fBcommandline\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
