.TH "_cmdline" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cmdline
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_CommandLine\fP"
.br
.ti -1c
.RI "class \fBArgument\fP"
.br
.ti -1c
.RI "class \fBDefine\fP"
.br
.ti -1c
.RI "class \fBGroup\fP"
.br
.ti -1c
.RI "class \fBParameterTree\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadd2tree\fP (\fBParameterTree\fP *root[], const char *word)"
.br
.ti -1c
.RI "char * \fBmakeChar\fP (std::string str)"
.br
.ti -1c
.RI "bool \fBmakeBoolean\fP (const char *value)"
.br
.ti -1c
.RI "bool \fBmakeBoolean\fP (std::string value)"
.br
.ti -1c
.RI "char * \fBstrUpper\fP (const char *str)"
.br
.ti -1c
.RI "vector< std::string > \fBsplitArgument\fP (const char *parm)"
.br
.ti -1c
.RI "vector< std::string > \fBtokenize\fP (const char *src, const char *pat)"
.br
.ti -1c
.RI "vector< int > \fBtokenizeNumber\fP (const char *src, const char *pat)"
.br
.ti -1c
.RI "char * \fBmyStrdup\fP (const char *s, int size)"
.br
.ti -1c
.RI "char * \fBmyStrdup\fP (const char *s)"
.br
.ti -1c
.RI "void \fBdefaultDate\fP (char *aux)"
.br
.ti -1c
.RI "void \fBvalidateEntry\fP (const char *parm, const char *prev)"
.br
.ti -1c
.RI "void \fBvalidateValue\fP (const char *value, \fBcmdline::Type\fP type)"
.br
.ti -1c
.RI "long \fBvalidateNumber\fP (const char *value)"
.br
.ti -1c
.RI "double \fBvalidateDecimal\fP (const char *value)"
.br
.ti -1c
.RI "long long \fBvalidateLongNumber\fP (const char *value)"
.br
.ti -1c
.RI "long double \fBvalidateLongDecimal\fP (const char *value)"
.br
.ti -1c
.RI "filesystem::path \fBvalidateDir\fP (const char *value)"
.br
.ti -1c
.RI "filesystem::path \fBvalidateDirExist\fP (const char *value)"
.br
.ti -1c
.RI "filesystem::path \fBvalidateFile\fP (const char *value)"
.br
.ti -1c
.RI "filesystem::path \fBvalidateFileExist\fP (const char *value)"
.br
.ti -1c
.RI "struct tm * \fBvalidateTime\fP (const char *value)"
.br
.ti -1c
.RI "struct tm * \fBvalidateDate\fP (const char *value, int fmt=\-1)"
.br
.ti -1c
.RI "struct tm * \fBvalidateDateTime\fP (const char *value)"
.br
.ti -1c
.RI "char * \fBvalidateTimestamp\fP (const char *value)"
.br
.ti -1c
.RI "int \fBmakeInteger\fP (const char *value)"
.br
.ti -1c
.RI "float \fBmakeFloat\fP (const char *value)"
.br
.ti -1c
.RI "struct tm \fBmakeTm\fP (const char *value)"
.br
.ti -1c
.RI "char * \fBmakeUpper\fP (const char *str)"
.br
.ti -1c
.RI "\fBParameterTree\fP * \fBcreateTree\fP (const char *word)"
.br
.ti -1c
.RI "\fBParameterTree\fP * \fBjoinTree\fP (\fBParameterTree\fP *root, const char *word)"
.br
.ti -1c
.RI "char * \fBmakeChar\fP (string str)"
.br
.ti -1c
.RI "bool \fBmakeBoolean\fP (string value)"
.br
.ti -1c
.RI "struct tm * \fBmakeDateTime\fP (char *sdate, char *stime)"
.br
.ti -1c
.RI "int \fBisLeap\fP (int year)"
.br
.ti -1c
.RI "double \fBvalidateDecimal2\fP (const char *value)"
.br
.ti -1c
.RI "long double \fBvalidateLongDecimal2\fP (const char *value)"
.br
.ti -1c
.RI "void \fBvalidateDateValue\fP (const char *value, vector< int > dt)"
.br
.ti -1c
.RI "template<typename T > T \fBgetValue\fP (const char *value, \fBType\fP type)"
.br
.ti -1c
.RI "template<typename T > void \fBcheckValue\fP (auto value)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBParameterTree\fP * \fBrootOptions\fP [128]"
.br
.ti -1c
.RI "\fBParameterTree\fP * \fBrootFlags\fP [128]"
.br
.ti -1c
.RI "char \fB_upper\fP [64] = ''"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _cmdline::add2tree (\fBParameterTree\fP * root[], const char * word)"

.PP
Definition at line \fB49\fP of file \fBtools\&.cpp\fP\&.
.SS "template<typename T > void _cmdline::checkValue (auto value)"

.PP
Definition at line \fB347\fP of file \fBvalidations\&.cpp\fP\&.
.SS "\fBParameterTree\fP * _cmdline::createTree (const char * word)"

.PP
Definition at line \fB12\fP of file \fBtools\&.cpp\fP\&.
.SS "void _cmdline::defaultDate (char * aux)"

.PP
Definition at line \fB159\fP of file \fBtools\&.cpp\fP\&.
.SS "template<typename T > T _cmdline::getValue (const char * value, \fBType\fP type)"

.PP
Definition at line \fB330\fP of file \fBvalidations\&.cpp\fP\&.
.SS "int _cmdline::isLeap (int year)"

.PP
Definition at line \fB56\fP of file \fBvalidations\&.cpp\fP\&.
.SS "\fBParameterTree\fP * _cmdline::joinTree (\fBParameterTree\fP * root, const char * word)"

.PP
Definition at line \fB23\fP of file \fBtools\&.cpp\fP\&.
.SS "bool _cmdline::makeBoolean (const char * value)"

.PP
Definition at line \fB71\fP of file \fBtools\&.cpp\fP\&.
.SS "bool _cmdline::makeBoolean (std::string value)"

.SS "bool _cmdline::makeBoolean (string value)"

.PP
Definition at line \fB78\fP of file \fBtools\&.cpp\fP\&.
.SS "char * _cmdline::makeChar (std::string str)"

.SS "char * _cmdline::makeChar (string str)"

.PP
Definition at line \fB65\fP of file \fBtools\&.cpp\fP\&.
.SS "struct tm * _cmdline::makeDateTime (char * sdate, char * stime)"

.PP
Definition at line \fB26\fP of file \fBvalidations\&.cpp\fP\&.
.SS "float _cmdline::makeFloat (const char * value)"

.PP
Definition at line \fB357\fP of file \fBvalidations\&.cpp\fP\&.
.SS "int _cmdline::makeInteger (const char * value)"

.PP
Definition at line \fB352\fP of file \fBvalidations\&.cpp\fP\&.
.SS "struct tm _cmdline::makeTm (const char * value)"

.PP
Definition at line \fB362\fP of file \fBvalidations\&.cpp\fP\&.
.SS "char * _cmdline::makeUpper (const char * str)"

.PP
Definition at line \fB36\fP of file \fBcommandline\&.cpp\fP\&.
.SS "char * _cmdline::myStrdup (const char * s)"

.PP
Definition at line \fB156\fP of file \fBtools\&.cpp\fP\&.
.SS "char * _cmdline::myStrdup (const char * s, int size)"

.PP
Definition at line \fB147\fP of file \fBtools\&.cpp\fP\&.
.SS "vector< string > _cmdline::splitArgument (const char * parm)"

.PP
Definition at line \fB81\fP of file \fBtools\&.cpp\fP\&.
.SS "char * _cmdline::strUpper (const char * str)"

.PP
Definition at line \fB139\fP of file \fBtools\&.cpp\fP\&.
.SS "vector< string > _cmdline::tokenize (const char * src, const char * pat)"

.PP
Definition at line \fB123\fP of file \fBtools\&.cpp\fP\&.
.SS "vector< int > _cmdline::tokenizeNumber (const char * src, const char * pat)"

.PP
Definition at line \fB132\fP of file \fBtools\&.cpp\fP\&.
.SS "struct tm * _cmdline::validateDate (const char * value, int fmt = \fC\-1\fP)"

.PP
Definition at line \fB189\fP of file \fBvalidations\&.cpp\fP\&.
.SS "struct tm * _cmdline::validateDateTime (const char * value)"

.PP
Definition at line \fB219\fP of file \fBvalidations\&.cpp\fP\&.
.SS "void _cmdline::validateDateValue (const char * value, vector< int > dt)"

.PP
Definition at line \fB180\fP of file \fBvalidations\&.cpp\fP\&.
.SS "double _cmdline::validateDecimal (const char * value)"

.PP
Definition at line \fB117\fP of file \fBvalidations\&.cpp\fP\&.
.SS "double _cmdline::validateDecimal2 (const char * value)"

.PP
Definition at line \fB62\fP of file \fBvalidations\&.cpp\fP\&.
.SS "filesystem::path _cmdline::validateDir (const char * value)"

.PP
Definition at line \fB264\fP of file \fBvalidations\&.cpp\fP\&.
.SS "filesystem::path _cmdline::validateDirExist (const char * value)"

.PP
Definition at line \fB286\fP of file \fBvalidations\&.cpp\fP\&.
.SS "void _cmdline::validateEntry (const char * parm, const char * prev)"

.PP
Definition at line \fB89\fP of file \fBvalidations\&.cpp\fP\&.
.SS "filesystem::path _cmdline::validateFile (const char * value)"

.PP
Definition at line \fB297\fP of file \fBvalidations\&.cpp\fP\&.
.SS "filesystem::path _cmdline::validateFileExist (const char * value)"

.PP
Definition at line \fB305\fP of file \fBvalidations\&.cpp\fP\&.
.SS "long double _cmdline::validateLongDecimal (const char * value)"

.PP
Definition at line \fB142\fP of file \fBvalidations\&.cpp\fP\&.
.SS "long double _cmdline::validateLongDecimal2 (const char * value)"

.PP
Definition at line \fB75\fP of file \fBvalidations\&.cpp\fP\&.
.SS "long long _cmdline::validateLongNumber (const char * value)"

.PP
Definition at line \fB105\fP of file \fBvalidations\&.cpp\fP\&.
.SS "long _cmdline::validateNumber (const char * value)"

.PP
Definition at line \fB93\fP of file \fBvalidations\&.cpp\fP\&.
.SS "struct tm * _cmdline::validateTime (const char * value)"

.PP
Definition at line \fB168\fP of file \fBvalidations\&.cpp\fP\&.
.SS "char * _cmdline::validateTimestamp (const char * value)"

.PP
Definition at line \fB239\fP of file \fBvalidations\&.cpp\fP\&.
.SS "void _cmdline::validateValue (const char * value, \fBcmdline::Type\fP type)"

.PP
Definition at line \fB312\fP of file \fBvalidations\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char _cmdline::_upper[64] = ''"

.PP
Definition at line \fB34\fP of file \fBcommandline\&.cpp\fP\&.
.SS "\fBParameterTree\fP* _cmdline::rootFlags[128]"

.PP
Definition at line \fB33\fP of file \fBcommandline\&.cpp\fP\&.
.SS "\fBParameterTree\fP* _cmdline::rootOptions[128]"

.PP
Definition at line \fB32\fP of file \fBcommandline\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
