.TH "testcmdline/caseTest.cpp" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcmdline/caseTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'pch\&.h'\fP
.br
\fC#include '$tool\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (Case, option_01)"
.br
.ti -1c
.RI "\fBTEST\fP (Case, options_02)"
.br
.ti -1c
.RI "\fBTEST\fP (Case, flag_01)"
.br
.ti -1c
.RI "\fBTEST\fP (Case, flag_02)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST (Case, flag_01)"

.PP
Definition at line \fB27\fP of file \fBcaseTest\&.cpp\fP\&.
.SS "TEST (Case, flag_02)"

.PP
Definition at line \fB40\fP of file \fBcaseTest\&.cpp\fP\&.
.SS "TEST (Case, option_01)"

.PP
Definition at line \fB5\fP of file \fBcaseTest\&.cpp\fP\&.
.SS "TEST (Case, options_02)"

.PP
Definition at line \fB16\fP of file \fBcaseTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
