.TH "cmdline::Parm" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline::Parm
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline\&.hpp>\fP
.PP
Inherited by \fBcmdline::ParmFlag\fP, and \fBcmdline::ParmOption\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParm\fP ()"
.br
.ti -1c
.RI "\fBParm\fP (const char *\fBname\fP)"
.br
.ti -1c
.RI "\fBParm\fP (const char *\fBname\fP, const char *\fBvalue\fP)"
.br
.ti -1c
.RI "\fBParm\fP (const char *\fBname\fP, const char *\fBvalue\fP, \fBType\fP \fBtype\fP, bool \fBmultiple\fP=false)"
.br
.ti -1c
.RI "\fBParm\fP (const char *\fBname\fP, bool \fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBinstanceOfFlag\fP ()"
.br
.ti -1c
.RI "bool \fBinstanceOfOption\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBType\fP \fBtype\fP = \fBType::STRING\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "bool \fBmultiple\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBcmdline\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cmdline::Parm::Parm ()\fC [inline]\fP"

.PP
Definition at line \fB27\fP of file \fBcmdline\&.hpp\fP\&.
.SS "cmdline::Parm::Parm (const char * name)"

.PP
Definition at line \fB5\fP of file \fBparameter\&.cpp\fP\&.
.SS "cmdline::Parm::Parm (const char * name, const char * value)"

.PP
Definition at line \fB12\fP of file \fBparameter\&.cpp\fP\&.
.SS "cmdline::Parm::Parm (const char * name, const char * value, \fBType\fP type, bool multiple = \fCfalse\fP)"

.PP
Definition at line \fB18\fP of file \fBparameter\&.cpp\fP\&.
.SS "cmdline::Parm::Parm (const char * name, bool value)"

.PP
Definition at line \fB25\fP of file \fBparameter\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool cmdline::Parm::instanceOfFlag ()"

.PP
Definition at line \fB32\fP of file \fBparameter\&.cpp\fP\&.
.SS "bool cmdline::Parm::instanceOfOption ()"

.PP
Definition at line \fB33\fP of file \fBparameter\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool cmdline::Parm::multiple"

.PP
Definition at line \fB26\fP of file \fBcmdline\&.hpp\fP\&.
.SS "const char* cmdline::Parm::name"

.PP
Definition at line \fB23\fP of file \fBcmdline\&.hpp\fP\&.
.SS "\fBType\fP cmdline::Parm::type = \fBType::STRING\fP"

.PP
Definition at line \fB24\fP of file \fBcmdline\&.hpp\fP\&.
.SS "char* cmdline::Parm::value"

.PP
Definition at line \fB25\fP of file \fBcmdline\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
