.TH "cmdline::CmdLineNotFoundException" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline::CmdLineNotFoundException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmdline_exceptions\&.hpp>\fP
.PP
Inherits std::runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCmdLineNotFoundException\fP ()=\fBdelete\fP"
.br
.ti -1c
.RI "\fBCmdLineNotFoundException\fP (const char *fmt,\&.\&.\&.)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBcmdline_exceptions\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cmdline::CmdLineNotFoundException::CmdLineNotFoundException ()\fC [delete]\fP"

.SS "cmdline::CmdLineNotFoundException::CmdLineNotFoundException (const char * fmt,  \&.\&.\&.)"

.PP
Definition at line \fB47\fP of file \fBcmdline_exceptions\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
