.TH "cmdline/include/cmdline.hpp" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline/include/cmdline.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <filesystem>\fP
.br
\fC#include 'cmdline_exceptions\&.hpp'\fP
.br
\fC#include 'validations\&.h'\fP
.br
\fC#include 'types\&.h'\fP
.br
\fC#include 'tools\&.h'\fP
.br
\fC#include <any>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcmdline::Parm\fP"
.br
.ti -1c
.RI "class \fBcmdline::ParmFlag\fP"
.br
.ti -1c
.RI "class \fBcmdline::ParmOption\fP"
.br
.ti -1c
.RI "class \fBcmdline::CmdLine\fP"
.br
.ti -1c
.RI "class \fBcmdline::CmdLineI\fP"
.br
.ti -1c
.RI "class \fBcmdline::CmdLineS\fP"
.br
.ti -1c
.RI "class \fBcmdline::CmdLineIS\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_cmdline\fP"
.br
.ti -1c
.RI "namespace \fBcmdline\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef vector< Parm > \fBcmdline::Parameters\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
