.TH "packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1.4/build/native/include/gtest/internal/gtest-param-util.h" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn.1.8.1.4/build/native/include/gtest/internal/gtest-param-util.h
.SH SYNOPSIS
.br
.PP
\fC#include <ctype\&.h>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <set>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'gtest/internal/gtest\-internal\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-linked_ptr\&.h'\fP
.br
\fC#include 'gtest/internal/gtest\-port\&.h'\fP
.br
\fC#include 'gtest/gtest\-printers\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtesting::TestParamInfo< ParamType >\fP"
.br
.ti -1c
.RI "struct \fBtesting::PrintToStringParamName\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParamIteratorInterface< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParamIterator< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParamGeneratorInterface< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParamGenerator< T >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::RangeGenerator< T, IncrementT >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ValuesInIteratorRangeGenerator< T >\fP"
.br
.ti -1c
.RI "struct \fBtesting::internal::ParamNameGenFunc< ParamType >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParameterizedTestFactory< TestClass >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::TestMetaFactoryBase< ParamType >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::TestMetaFactory< TestCase >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParameterizedTestCaseInfoBase\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParameterizedTestCaseInfo< TestCase >\fP"
.br
.ti -1c
.RI "class \fBtesting::internal::ParameterizedTestCaseRegistry\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtesting\fP"
.br
.ti -1c
.RI "namespace \fBtesting::internal\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGTEST_API_\fP void \fBtesting::internal::ReportInvalidTestCaseType\fP (const char *test_case_name, CodeLocation code_location)"
.br
.ti -1c
.RI "template<class ParamType > std::string \fBtesting::internal::DefaultParamName\fP (const TestParamInfo< ParamType > &info)"
.br
.ti -1c
.RI "template<class ParamType , class ParamNameGenFunctor > ParamNameGenFunctor \fBtesting::internal::GetParamNameGen\fP (ParamNameGenFunctor func)"
.br
.ti -1c
.RI "template<class ParamType > ParamNameGenFunc< ParamType >::\fBType\fP * \fBtesting::internal::GetParamNameGen\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
