.TH "cmdline/include/msg_locale.h" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline/include/msg_locale.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTXT_HELP\fP   'Help requested'"
.br
.ti -1c
.RI "#define \fBTXT_HELP_DETAIL\fP   'Help detailed requested'"
.br
.ti -1c
.RI "#define \fBTXT_ARG_INVALID\fP   'Invalid argument: '%s''"
.br
.ti -1c
.RI "#define \fBTXT_ARG_EXPECTED\fP   'Invalid argument: '%s'\&. Expected '%s''"
.br
.ti -1c
.RI "#define \fBTXT_VAL_INVALID\fP   'Invalid value: %s'"
.br
.ti -1c
.RI "#define \fBTXT_VAL_EXPECTED\fP   'Invalid value: %s\&. Expected '%s''"
.br
.ti -1c
.RI "#define \fBTXT_ARG_SET\fP   'Parameter already set: %s'"
.br
.ti -1c
.RI "#define \fBTXT_ARG_NFND\fP   ''%s' Not found'"
.br
.ti -1c
.RI "#define \fBTXT_ARG_NFND1\fP   ''%s' Not found\&. Maybe you tried '%s''"
.br
.ti -1c
.RI "#define \fBTXT_ARG_NFND2\fP   ''%s' Not found\&. Maybe you tried '%s%s''"
.br
.ti -1c
.RI "#define \fBTXT_ARG_NFND3\fP   ''%s' Not found\&. Maybe is  incomplete'"
.br
.ti -1c
.RI "#define \fBINV_DEFINITION\fP   'Invalid definition: '%s''"
.br
.ti -1c
.RI "#define \fBERR_ARG_MISSING\fP   'Missing value for: '%s''"
.br
.ti -1c
.RI "#define \fBERR_ARG_ERR\fP   'Invalid argument: '%s''"
.br
.ti -1c
.RI "#define \fBERR_INV_OPTION\fP   'Invalid option: '%s''"
.br
.ti -1c
.RI "#define \fBERR_NOT_FND\fP   'Parameter not found: '%s''"
.br
.ti -1c
.RI "#define \fBERR_INV_TYPE\fP   'Invalid type\&. Expected '%s''"
.br
.ti -1c
.RI "#define \fBERR_ARG_DUP\fP   'Parameter already set: '%s''"
.br
.ti -1c
.RI "#define \fBTXT_NO_DIR\fP   'Is not a directory'"
.br
.ti -1c
.RI "#define \fBTXT_DIR_NOTFND\fP   'Directory not found'"
.br
.ti -1c
.RI "#define \fBTXT_FILE_NOTFND\fP   'File not found'"
.br
.ti -1c
.RI "#define \fBTXT_FILE_DIR\fP   'Is a directory'"
.br
.ti -1c
.RI "#define \fBTXT_DATE\fP   'Date'"
.br
.ti -1c
.RI "#define \fBTXT_TIME\fP   'Time'"
.br
.ti -1c
.RI "#define \fBTXT_DATETIME\fP   'Datetime'"
.br
.ti -1c
.RI "#define \fBTXT_TMS\fP   'Timestamp'"
.br
.ti -1c
.RI "#define \fBTXT_NUMBER\fP   'Number'"
.br
.ti -1c
.RI "#define \fBTXT_DECIMAL\fP   'Decimal'"
.br
.ti -1c
.RI "#define \fBTXT_LONGNUMBER\fP   'Long Number'"
.br
.ti -1c
.RI "#define \fBTXT_LONGDECIMAL\fP   'Long Decimal'"
.br
.ti -1c
.RI "#define \fBTXT_DIR\fP   'Directory'"
.br
.ti -1c
.RI "#define \fBTXT_FILE\fP   'File'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ERR_ARG_DUP   'Parameter already set: '%s''"

.PP
Definition at line \fB20\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define ERR_ARG_ERR   'Invalid argument: '%s''"

.PP
Definition at line \fB16\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define ERR_ARG_MISSING   'Missing value for: '%s''"

.PP
Definition at line \fB15\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define ERR_INV_OPTION   'Invalid option: '%s''"

.PP
Definition at line \fB17\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define ERR_INV_TYPE   'Invalid type\&. Expected '%s''"

.PP
Definition at line \fB19\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define ERR_NOT_FND   'Parameter not found: '%s''"

.PP
Definition at line \fB18\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define INV_DEFINITION   'Invalid definition: '%s''"

.PP
Definition at line \fB14\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_ARG_EXPECTED   'Invalid argument: '%s'\&. Expected '%s''"

.PP
Definition at line \fB6\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_ARG_INVALID   'Invalid argument: '%s''"

.PP
Definition at line \fB5\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_ARG_NFND   ''%s' Not found'"

.PP
Definition at line \fB10\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_ARG_NFND1   ''%s' Not found\&. Maybe you tried '%s''"

.PP
Definition at line \fB11\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_ARG_NFND2   ''%s' Not found\&. Maybe you tried '%s%s''"

.PP
Definition at line \fB12\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_ARG_NFND3   ''%s' Not found\&. Maybe is  incomplete'"

.PP
Definition at line \fB13\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_ARG_SET   'Parameter already set: %s'"

.PP
Definition at line \fB9\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_DATE   'Date'"

.PP
Definition at line \fB26\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_DATETIME   'Datetime'"

.PP
Definition at line \fB28\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_DECIMAL   'Decimal'"

.PP
Definition at line \fB31\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_DIR   'Directory'"

.PP
Definition at line \fB34\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_DIR_NOTFND   'Directory not found'"

.PP
Definition at line \fB22\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_FILE   'File'"

.PP
Definition at line \fB35\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_FILE_DIR   'Is a directory'"

.PP
Definition at line \fB24\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_FILE_NOTFND   'File not found'"

.PP
Definition at line \fB23\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_HELP   'Help requested'"

.PP
Definition at line \fB3\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_HELP_DETAIL   'Help detailed requested'"

.PP
Definition at line \fB4\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_LONGDECIMAL   'Long Decimal'"

.PP
Definition at line \fB33\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_LONGNUMBER   'Long Number'"

.PP
Definition at line \fB32\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_NO_DIR   'Is not a directory'"

.PP
Definition at line \fB21\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_NUMBER   'Number'"

.PP
Definition at line \fB30\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_TIME   'Time'"

.PP
Definition at line \fB27\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_TMS   'Timestamp'"

.PP
Definition at line \fB29\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_VAL_EXPECTED   'Invalid value: %s\&. Expected '%s''"

.PP
Definition at line \fB8\fP of file \fBmsg_locale\&.h\fP\&.
.SS "#define TXT_VAL_INVALID   'Invalid value: %s'"

.PP
Definition at line \fB7\fP of file \fBmsg_locale\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
