.TH "testing::internal::IteratorTraits< Iterator >" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::IteratorTraits< Iterator >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Iterator::value_type \fBvalue_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Iterator>
.br
struct testing::internal::IteratorTraits< Iterator >"
.PP
Definition at line \fB2365\fP of file \fBgtest\-port\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename Iterator > typedef Iterator::value_type \fBtesting::internal::IteratorTraits\fP< Iterator >::\fBvalue_type\fP"

.PP
Definition at line \fB2366\fP of file \fBgtest\-port\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
