.TH "testing::internal::ThreadLocal< T >" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ThreadLocal< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-port\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThreadLocal\fP ()"
.br
.ti -1c
.RI "\fBThreadLocal\fP (const T &value)"
.br
.ti -1c
.RI "T * \fBpointer\fP ()"
.br
.ti -1c
.RI "const T * \fBpointer\fP () const"
.br
.ti -1c
.RI "const T & \fBget\fP () const"
.br
.ti -1c
.RI "void \fBset\fP (const T &value)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class testing::internal::ThreadLocal< T >"
.PP
Definition at line \fB2300\fP of file \fBgtest\-port\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBtesting::internal::ThreadLocal\fP< T >::\fBThreadLocal\fP ()\fC [inline]\fP"

.PP
Definition at line \fB2302\fP of file \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > \fBtesting::internal::ThreadLocal\fP< T >::\fBThreadLocal\fP (const T & value)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line \fB2303\fP of file \fBgtest\-port\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > const T & \fBtesting::internal::ThreadLocal\fP< T >::get () const\fC [inline]\fP"

.PP
Definition at line \fB2306\fP of file \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > T * \fBtesting::internal::ThreadLocal\fP< T >::pointer ()\fC [inline]\fP"

.PP
Definition at line \fB2304\fP of file \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > const T * \fBtesting::internal::ThreadLocal\fP< T >::pointer () const\fC [inline]\fP"

.PP
Definition at line \fB2305\fP of file \fBgtest\-port\&.h\fP\&.
.SS "template<typename T > void \fBtesting::internal::ThreadLocal\fP< T >::set (const T & value)\fC [inline]\fP"

.PP
Definition at line \fB2307\fP of file \fBgtest\-port\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
