.TH "testing::internal::ParamIteratorInterface< T >" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::internal::ParamIteratorInterface< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ParamIteratorInterface\fP ()"
.br
.ti -1c
.RI "virtual const \fBParamGeneratorInterface\fP< T > * \fBBaseGenerator\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBAdvance\fP ()=0"
.br
.ti -1c
.RI "virtual \fBParamIteratorInterface\fP * \fBClone\fP () const =0"
.br
.ti -1c
.RI "virtual const T * \fBCurrent\fP () const =0"
.br
.ti -1c
.RI "virtual bool \fBEquals\fP (const \fBParamIteratorInterface\fP &other) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class testing::internal::ParamIteratorInterface< T >"
.PP
Definition at line \fB89\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > virtual \fBtesting::internal::ParamIteratorInterface\fP< T >::~\fBParamIteratorInterface\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB91\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > virtual void \fBtesting::internal::ParamIteratorInterface\fP< T >::Advance ()\fC [pure virtual]\fP"

.SS "template<typename T > virtual const \fBParamGeneratorInterface\fP< T > * \fBtesting::internal::ParamIteratorInterface\fP< T >::BaseGenerator () const\fC [pure virtual]\fP"

.SS "template<typename T > virtual \fBParamIteratorInterface\fP * \fBtesting::internal::ParamIteratorInterface\fP< T >::Clone () const\fC [pure virtual]\fP"

.SS "template<typename T > virtual const T * \fBtesting::internal::ParamIteratorInterface\fP< T >::Current () const\fC [pure virtual]\fP"

.SS "template<typename T > virtual bool \fBtesting::internal::ParamIteratorInterface\fP< T >::Equals (const \fBParamIteratorInterface\fP< T > & other) const\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
