.TH "testing::PrintToStringParamName" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testing::PrintToStringParamName
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gtest\-param\-util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<class ParamType > std::string \fBoperator()\fP (const \fBTestParamInfo\fP< ParamType > &info) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB65\fP of file \fBgtest\-param\-util\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class ParamType > std::string testing::PrintToStringParamName::operator() (const \fBTestParamInfo\fP< ParamType > & info) const\fC [inline]\fP"

.PP
Definition at line \fB67\fP of file \fBgtest\-param\-util\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
