.TH "cmdline/include/tools.h" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline/include/tools.h
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_map>\fP
.br
\fC#include 'parameter_tree\&.hpp'\fP
.br
\fC#include 'msg_locale\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB_cmdline\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBstrdup\fP(a)   \fB_cmdline::myStrdup\fP(a)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_cmdline::add2tree\fP (ParameterTree *root[], const char *word)"
.br
.ti -1c
.RI "char * \fB_cmdline::makeChar\fP (std::string str)"
.br
.ti -1c
.RI "bool \fB_cmdline::makeBoolean\fP (const char *value)"
.br
.ti -1c
.RI "bool \fB_cmdline::makeBoolean\fP (std::string value)"
.br
.ti -1c
.RI "char * \fB_cmdline::strUpper\fP (const char *str)"
.br
.ti -1c
.RI "vector< std::string > \fB_cmdline::splitArgument\fP (const char *parm)"
.br
.ti -1c
.RI "vector< std::string > \fB_cmdline::tokenize\fP (const char *src, const char *pat)"
.br
.ti -1c
.RI "vector< int > \fB_cmdline::tokenizeNumber\fP (const char *src, const char *pat)"
.br
.ti -1c
.RI "char * \fB_cmdline::myStrdup\fP (const char *s, int size)"
.br
.ti -1c
.RI "char * \fB_cmdline::myStrdup\fP (const char *s)"
.br
.ti -1c
.RI "void \fB_cmdline::defaultDate\fP (char *aux)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define strdup(a)   \fB_cmdline::myStrdup\fP(a)"

.PP
Definition at line \fB15\fP of file \fBtools\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
