.TH "cmdline/include/types.h" 3 "Wed Nov 3 2021" "Version 0.2.3" "Command Line Processor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline/include/types.h
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_map>\fP
.br
\fC#include <filesystem>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcmdline\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CMDLINE_TYPES__\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBcmdline::TYPE_STRING\fP = std::string"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_BOOL\fP = bool"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_NUMBER\fP = long"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_LONG\fP = long"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_INT\fP = int"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_DECIMAL\fP = float"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_FLOAT\fP = float"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_DOUBLE\fP = double"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_LONGNUMBER\fP = long long"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_LONGDECIMAL\fP = float"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_DATE\fP = std::tm"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_TIME\fP = std::tm"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_DATETIME\fP = std::tm"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_TMS\fP = char *"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_DIR\fP = std::filesystem::path"
.br
.ti -1c
.RI "using \fBcmdline::TYPE_FILE\fP = std::filesystem::path"
.br
.ti -1c
.RI "using \fBcmdline::Flags\fP = std::unordered_map< std::string, bool >"
.br
.ti -1c
.RI "using \fBcmdline::Options\fP = std::unordered_map< std::string, std::string >"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBcmdline::Type\fP { \fBcmdline::STRING\fP, \fBcmdline::CHAR\fP, \fBcmdline::BOOL\fP, \fBcmdline::NUMBER\fP, \fBcmdline::DECIMAL\fP, \fBcmdline::LONGNUMBER\fP, \fBcmdline::LONGDECIMAL\fP, \fBcmdline::DATE\fP, \fBcmdline::TIME\fP, \fBcmdline::DATETIME\fP, \fBcmdline::TMS\fP, \fBcmdline::DIR\fP, \fBcmdline::DIR_EXISTS\fP, \fBcmdline::FILE\fP, \fBcmdline::FILE_EXISTS\fP }"
.br
.ti -1c
.RI "enum class \fBcmdline::Source\fP { \fBcmdline::DEFAULT\fP, \fBcmdline::ENV\fP, \fBcmdline::CMDLINE\fP, \fBcmdline::CODE\fP, \fBcmdline::AUTO\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __CMDLINE_TYPES__"

.PP
Definition at line \fB6\fP of file \fBtypes\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Command Line Processor from the source code\&.
